import "server-only";
import { Prisma,type RefundReasonCode } from "@prisma/client";
import { DomainError } from "@/lib/domain/errors";import { Money } from "@/lib/domain/money";import { executeIdempotent } from "@/lib/pos2/idempotency";import { requireCapability,type CommandActor } from "@/lib/pos2/authorization";import { requireActorBranch,requireActiveTerminal } from "@/lib/pos2/cash/guards";import { appendAuditEvent } from "@/lib/pos2/audit";import { appendOutboxEvent } from "@/lib/pos2/outbox";import { lockSale,requireCompensationSession } from "./compensationGuards";
type Allocation={paymentId:string;amount:string;reference?:string};
export async function createRefund(input:{saleId:string;amount:string;currency?:"MXN";reasonCode:RefundReasonCode;reasonText?:string;allocations:Allocation[];cashSessionId?:string;terminalId:string;actor:CommandActor;operationId:string;faultInjectionForTest?:"AFTER_DOCUMENT"|"AFTER_CASH"}){
 const payload={saleId:input.saleId,amount:input.amount,currency:input.currency??"MXN",reasonCode:input.reasonCode,reasonText:input.reasonText?.trim()||null,allocations:input.allocations,cashSessionId:input.cashSessionId??null};return executeIdempotent({operationId:input.operationId,command:"CreateRefund",payload,receiptContext:{actorId:input.actor.id},execute:async tx=>{
  const sale=await lockSale(tx,input.saleId);requireActorBranch(input.actor,sale.branchId);await requireCapability(tx,input.actor,"pos.refund.create",sale.branchId);await requireActiveTerminal(tx,{terminalId:input.terminalId,branchId:sale.branchId});if(sale.status==="CANCELLED"||sale.cancellation)throw new DomainError("INVALID_STATE_TRANSITION",{saleId:sale.id,status:sale.status});let amount:Money;try{amount=Money.nonNegative(input.amount);}catch{throw new DomainError("VALIDATION_ERROR",{field:"amount"});}if(amount.equals(Money.zero())||!input.allocations.length||new Set(input.allocations.map(a=>a.paymentId)).size!==input.allocations.length)throw new DomainError("VALIDATION_ERROR",{field:"allocations"});
  const prior=new Map<string,Prisma.Decimal>();for(const refund of sale.refunds)for(const allocation of refund.allocations)prior.set(allocation.paymentId,(prior.get(allocation.paymentId)??new Prisma.Decimal(0)).plus(allocation.amount));let allocated=Money.zero();const parsed=input.allocations.map((allocation,index)=>{const payment=sale.payments.find(p=>p.id===allocation.paymentId);let part:Money;try{part=Money.nonNegative(allocation.amount);}catch{throw new DomainError("VALIDATION_ERROR",{field:`allocations.${index}.amount`});}if(!payment||part.equals(Money.zero()))throw new DomainError("VALIDATION_ERROR",{field:`allocations.${index}`});if((prior.get(payment.id)??new Prisma.Decimal(0)).plus(part.toDecimal()).gt(payment.amount))throw new DomainError("REFUND_AMOUNT_EXCEEDED",{paymentId:payment.id});if(payment.method!=="CASH"&&!allocation.reference?.trim())throw new DomainError("VALIDATION_ERROR",{field:`allocations.${index}.reference`});allocated=allocated.add(part);return {input:allocation,payment,amount:part};});if(!allocated.equals(amount))throw new DomainError("PAYMENT_MISMATCH",{expected:amount.toString(),received:allocated.toString()});
  const totalPrior=sale.refunds.reduce((sum,r)=>sum.add(Money.from(r.amount)),Money.zero());if(totalPrior.add(amount).compare(Money.from(sale.payments.reduce((sum,p)=>sum.plus(p.amount),new Prisma.Decimal(0))))>0)throw new DomainError("REFUND_AMOUNT_EXCEEDED",{saleId:sale.id});for(const method of new Set(parsed.map(x=>x.payment.method)))await requireCapability(tx,input.actor,`pos.refund.${method.toLowerCase()}` as "pos.refund.cash"|"pos.refund.card"|"pos.refund.transfer",sale.branchId);
  const cash=parsed.filter(x=>x.payment.method==="CASH").reduce((sum,x)=>sum.add(x.amount),Money.zero());const session=cash.equals(Money.zero())?null:await requireCompensationSession(tx,{sale,cashSessionId:input.cashSessionId,terminalId:input.terminalId});const refund=await tx.pos2Refund.create({data:{saleId:sale.id,amount:amount.toDecimal(),currency:input.currency??"MXN",reasonCode:input.reasonCode,reasonText:input.reasonText?.trim()||null,actorId:input.actor.id,terminalId:input.terminalId,cashSessionId:session?.id??null,operationId:input.operationId}});for(const item of parsed)await tx.refundAllocation.create({data:{refundId:refund.id,paymentId:item.payment.id,method:item.payment.method,amount:item.amount.toDecimal(),currency:item.payment.currency,reference:item.input.reference?.trim()||null}});if(input.faultInjectionForTest==="AFTER_DOCUMENT"&&process.env.NODE_ENV!=="production")throw new Error("TEST_REFUND_AFTER_DOCUMENT");
  if(session)await tx.cashMovement.create({data:{cashSessionId:session.id,branchId:sale.branchId,registerId:session.registerId,type:"REFUND_CASH",direction:"OUT",amount:cash.toDecimal(),sourceType:"REFUND",sourceId:refund.id,actorId:input.actor.id,operationId:input.operationId,metadata:{saleId:sale.id,originalCashSessionId:sale.cashSessionId}}});if(input.faultInjectionForTest==="AFTER_CASH"&&process.env.NODE_ENV!=="production")throw new Error("TEST_REFUND_AFTER_CASH");
  await appendAuditEvent(tx,{actorId:input.actor.id,branchId:sale.branchId,terminalId:input.terminalId,action:"REFUND_CREATED",entityType:"Pos2Refund",entityId:refund.id,operationId:input.operationId,metadata:{saleId:sale.id,amount:amount.toString(),cashAmount:cash.toString()}});if(session)await appendAuditEvent(tx,{actorId:input.actor.id,branchId:sale.branchId,action:"CASH_REFUND_CREATED",entityType:"CashMovement",entityId:refund.id,operationId:input.operationId,metadata:{cashSessionId:session.id,amount:cash.toString()}});await appendOutboxEvent(tx,{topic:"REFUND_COMPLETED",aggregate:"Pos2Sale",aggregateId:sale.id,operationId:input.operationId,payload:{saleId:sale.id,refundId:refund.id,amount:amount.toString()}});return {type:"Pos2Refund",id:refund.id,saleId:sale.id,amount:amount.toString(),cashAmount:cash.toString()} as Prisma.InputJsonObject;
 }});}
