import "server-only";
import { Prisma,type CatalogBaseUnit,type InventoryDisposition,type ReturnReasonCode } from "@prisma/client";
import { DomainError } from "@/lib/domain/errors";
import { executeIdempotent } from "@/lib/pos2/idempotency";
import { requireCapability,type CommandActor } from "@/lib/pos2/authorization";
import { requireActorBranch,requireActiveTerminal } from "@/lib/pos2/cash/guards";
import { applyInventoryBatchInTransaction } from "@/lib/pos2/inventory/applyMovements";
import { groupInventoryDeltas } from "@/lib/pos2/inventory/domain";
import { appendAuditEvent } from "@/lib/pos2/audit";import { appendOutboxEvent } from "@/lib/pos2/outbox";import { lockSale } from "./compensationGuards";
type Line={saleLineId:string;quantity:string;unit:CatalogBaseUnit;disposition:InventoryDisposition;reasonText?:string};
export async function createReturn(input:{saleId:string;reasonCode:ReturnReasonCode;reasonText?:string;lines:Line[];terminalId:string;actor:CommandActor;operationId:string;faultInjectionForTest?:"AFTER_DOCUMENT"|"AFTER_FIRST_RESTOCK"}){
 const payload={saleId:input.saleId,reasonCode:input.reasonCode,reasonText:input.reasonText?.trim()||null,lines:input.lines};return executeIdempotent({operationId:input.operationId,command:"CreateReturn",payload,receiptContext:{actorId:input.actor.id},execute:async tx=>{
  const sale=await lockSale(tx,input.saleId);requireActorBranch(input.actor,sale.branchId);await requireCapability(tx,input.actor,"pos.return.create",sale.branchId);await requireActiveTerminal(tx,{terminalId:input.terminalId,branchId:sale.branchId});if(sale.status==="CANCELLED"||sale.cancellation)throw new DomainError("INVALID_STATE_TRANSITION",{saleId:sale.id,status:sale.status});if(!input.lines.length)throw new DomainError("VALIDATION_ERROR",{field:"lines"});
  const ids=input.lines.map(l=>l.saleLineId);if(new Set(ids).size!==ids.length)throw new DomainError("VALIDATION_ERROR",{field:"lines"});const historical=new Map(sale.returns.flatMap(r=>r.lines).map(l=>[l.saleLineId,new Prisma.Decimal(0)]));for(const r of sale.returns)for(const l of r.lines)historical.set(l.saleLineId,(historical.get(l.saleLineId)??new Prisma.Decimal(0)).plus(l.quantity));
  const parsed=input.lines.map(line=>{const sold=sale.lines.find(l=>l.id===line.saleLineId);let quantity:Prisma.Decimal;try{quantity=new Prisma.Decimal(line.quantity);}catch{throw new DomainError("VALIDATION_ERROR",{field:"quantity"});}if(!sold||quantity.lte(0)||sold.unit!==line.unit)throw new DomainError("VALIDATION_ERROR",{field:"lines"});if((historical.get(sold.id)??new Prisma.Decimal(0)).plus(quantity).gt(sold.quantity))throw new DomainError("RETURN_QUANTITY_EXCEEDED",{saleLineId:sold.id});return {input:line,sold,quantity};});
  if(parsed.some(x=>x.input.disposition==="RESTOCK"))await requireCapability(tx,input.actor,"pos.return.restock",sale.branchId);
  const doc=await tx.pos2Return.create({data:{saleId:sale.id,reasonCode:input.reasonCode,reasonText:input.reasonText?.trim()||null,actorId:input.actor.id,terminalId:input.terminalId,operationId:input.operationId}});for(const item of parsed)await tx.returnLine.create({data:{returnId:doc.id,saleLineId:item.sold.id,quantity:item.quantity,unit:item.input.unit,disposition:item.input.disposition,reasonText:item.input.reasonText?.trim()||null}});if(input.faultInjectionForTest==="AFTER_DOCUMENT"&&process.env.NODE_ENV!=="production")throw new Error("TEST_RETURN_AFTER_DOCUMENT");
  const restock=parsed.filter(x=>x.input.disposition==="RESTOCK");const orderLineIds=restock.map(x=>x.sold.orderLineId);const originals=orderLineIds.length?await tx.inventoryMovement.findMany({where:{sourceType:"SALE",sourceId:sale.id,movementType:"SALE_CONSUMPTION",sourceLineId:{in:orderLineIds}}}):[];const raw=[];for(const item of restock){const matches=originals.filter(m=>m.sourceLineId===item.sold.orderLineId);if(!matches.length)throw new DomainError("INVENTORY_MAPPING_NOT_CONFIGURED",{saleLineId:item.sold.id});for(const m of matches)raw.push({inventoryProductId:m.inventoryProductId,quantityDelta:m.quantityDelta.abs().times(item.quantity).div(item.sold.quantity).toDecimalPlaces(6).toString(),unit:m.unit,movementType:"SALE_REVERSAL" as const,sourceType:"RETURN" as const,sourceId:doc.id,sourceLineId:item.sold.id,reasonCode:"CUSTOMER_RETURN",metadata:{originalMovementId:m.id}});}
  const movements=raw.length?groupInventoryDeltas(raw):[];if(movements.length)await applyInventoryBatchInTransaction(tx,{branchId:sale.branchId,movements,actorId:input.actor.id,operationId:input.operationId,failAfterFirstMovementForTest:input.faultInjectionForTest==="AFTER_FIRST_RESTOCK"});
  for(const item of parsed)historical.set(item.sold.id,(historical.get(item.sold.id)??new Prisma.Decimal(0)).plus(item.quantity));const allReturned=sale.lines.every(line=>(historical.get(line.id)??new Prisma.Decimal(0)).equals(line.quantity));const status=allReturned?"RETURNED":"PARTIALLY_RETURNED";await tx.pos2Sale.update({where:{id:sale.id},data:{status}});
  await appendAuditEvent(tx,{actorId:input.actor.id,branchId:sale.branchId,terminalId:input.terminalId,action:"RETURN_CREATED",entityType:"Pos2Return",entityId:doc.id,operationId:input.operationId,metadata:{saleId:sale.id,lineCount:parsed.length,status}});if(movements.length)await appendAuditEvent(tx,{actorId:input.actor.id,branchId:sale.branchId,action:"INVENTORY_RESTOCKED",entityType:"Pos2Return",entityId:doc.id,operationId:input.operationId,metadata:{movementCount:movements.length}});await appendOutboxEvent(tx,{topic:"RETURN_COMPLETED",aggregate:"Pos2Sale",aggregateId:sale.id,operationId:input.operationId,payload:{saleId:sale.id,returnId:doc.id,status}});return {type:"Pos2Return",id:doc.id,saleId:sale.id,status,inventoryMovements:movements.length} as Prisma.InputJsonObject;
 }});}
