"use client";
import type { OrderDto } from "@/lib/pos2/ui/types";
const currency=(value:string)=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(Number(value));
export default function CartPanel({order,busy,onQuantity,onRemove,onAdjust,onVoid,onPay}:{order:OrderDto|null;busy:boolean;onQuantity:(id:string,qty:number)=>void;onRemove:(id:string)=>void;onAdjust:()=>void;onVoid:()=>void;onPay:()=>void}){
 return <aside className="pos2-cart" aria-label="Orden actual"><div className="pos2-cart-head"><div><small>Orden actual</small><h2>{order?.orderNumber??"Nueva venta"}</h2></div><div className="pos2-cart-tools"><span>{order?.lines.length??0} artículos</span>{order?.lines.length?<button onClick={onVoid}>Anular</button>:null}</div></div>
  <div className="pos2-cart-lines">{!order?.lines.length?<div className="pos2-cart-empty"><span aria-hidden>◫</span><b>Tu orden está vacía</b><small>Toca un producto para agregarlo</small></div>:order.lines.map(line=><article key={line.id}><div className="pos2-line-main"><div><b>{line.displayName}</b><small>{currency(line.unitPrice)} × {line.quantity}</small></div><strong>{currency(line.lineTotal)}</strong></div><div className="pos2-line-actions"><div><button disabled={busy} onClick={()=>Number(line.quantity)<=1?onRemove(line.id):onQuantity(line.id,Number(line.quantity)-1)}>−</button><span>{Number(line.quantity)}</span><button disabled={busy} onClick={()=>onQuantity(line.id,Number(line.quantity)+1)}>+</button></div><button disabled={busy} onClick={()=>onRemove(line.id)}>Eliminar</button></div></article>)}</div>
  <div className="pos2-cart-summary">{order?.adjustments.map(item=><div className="pos2-adjustment-row" key={item.id}><span>{item.name}</span><b>−{currency(item.amount)}</b></div>)}<div><span>Subtotal</span><b>{currency(order?.subtotal??"0")}</b></div><div><span>Descuentos</span><b>−{currency(order?.discountTotal??"0")}</b></div><div className="pos2-total"><span>Total</span><strong>{currency(order?.total??"0")}</strong></div><button className="pos2-adjust" disabled={busy||!order?.lines.length||order.status!=="OPEN"} onClick={onAdjust}>Descuento o cortesía</button><button data-testid="pay-order" className="pos2-pay" disabled={busy||!order?.lines.length||order.status!=="OPEN"} onClick={onPay}>{busy?"Procesando…":"Cobrar"}<span>{currency(order?.total??"0")}</span></button></div>
 </aside>;
}
