"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import CatalogPanel, { type CatalogSelection } from "./CatalogPanel";
import CartPanel from "./CartPanel";
import PaymentFlow from "./PaymentFlow";
import type { AdjustmentRuleDto, CatalogCategoryDto, OrderDto, PersonDto, PosContextDto } from "@/lib/pos2/ui/types";
import type { CapabilityKey } from "@/lib/pos2/capabilityPolicy";
import { paymentSummary, type UiPayment } from "@/lib/pos2/ui/payment";
import { cashierIssue, readApiError } from "@/lib/pos2/ui/errors";
import { addLocalLine, localEstimatedTotal, queueLocalDraft, removeLocalLine, updateLocalLineQuantity } from "@/lib/pos2/offline/drafts";
import { createLocalDraft, getDraft, getMapping, listDrafts, saveDraft } from "@/lib/pos2/offline/store";
import { httpSyncTransport, processPos2Queue, withSyncLeader } from "@/lib/pos2/offline/coordinator";
import type { Pos2LocalDraft } from "@/lib/pos2/offline/types";
import { generateClientOperationId } from "@/lib/pos2/offline/canonical";
import styles from "./pos2.module.css";
import RecentSalesPanel from "./RecentSalesPanel";

type Notice={tone:"error"|"success"|"info";title:string;message:string}|null;
type SaleResult={id:string;saleNumber:string;total:string;receiptUrl:string;uiPayments:UiPayment[];change:string};
type SnapshotVariant={id:string;name:string;sku:string|null;active:boolean};
type SnapshotProduct={id:string;name:string;sku:string|null;internalCode:string|null;barcode:string|null;icon:string|null;imageAlt:string|null;effective:{available?:boolean;enabled?:boolean;availability?:string};variants:SnapshotVariant[]};
type SnapshotCategory={id:string;name:string;icon:string|null;products:SnapshotProduct[]};
type OpenOrderItem={id:string;orderNumber:string;status:string;total:string;lines:unknown[]};
const operationId=()=>generateClientOperationId();

export default function Pos2CashierApp({userId,userName,contexts,initialCatalog,rules,people,capabilities}:{userId:string;userName:string;contexts:PosContextDto[];initialCatalog:CatalogCategoryDto[];rules:AdjustmentRuleDto[];people:PersonDto[];capabilities:Record<CapabilityKey,boolean>}){
 const [contextIndex,setContextIndex]=useState(0),[credential,setCredential]=useState(""),[catalog,setCatalog]=useState(initialCatalog),[order,setOrder]=useState<OrderDto|null>(null),[localDraft,setLocalDraft]=useState<Pos2LocalDraft|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState<Notice>(null),[view,setView]=useState<"SALE"|"PAYMENT"|"SUCCESS"|"ORDERS"|"SALES"|"CASH">("SALE"),[online,setOnline]=useState(true),[adjustOpen,setAdjustOpen]=useState(false),[sale,setSale]=useState<SaleResult|null>(null),[completeId,setCompleteId]=useState<string|null>(null),[verifying,setVerifying]=useState(false);
 const context=contexts[contextIndex]??null;
 useEffect(()=>{const sync=()=>setOnline(navigator.onLine);sync();window.addEventListener("online",sync);window.addEventListener("offline",sync);return()=>{window.removeEventListener("online",sync);window.removeEventListener("offline",sync)}},[]);
 useEffect(()=>{if(!context)return;void listDrafts().then(drafts=>{const draft=drafts.filter(item=>item.branchId===context.branchId&&item.registerId===context.registerId&&item.lines.length&&item.state!=="SYNCED").sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0];if(draft){setLocalDraft(draft);setOrder(localOrder(draft));setNotice({tone:"info",title:"Carrito local recuperado",message:"Este borrador permanece en el dispositivo y puede sincronizarse al reconectar."})}})},[context]);
 const headers=useMemo(()=>({"Content-Type":"application/json","x-maestro-terminal-id":context?.terminalId??"","x-maestro-terminal-credential":credential}),[context,credential]);
 const api=useCallback(async(url:string,init?:RequestInit)=>{if(!credential.trim())throw Object.assign(new Error("TERMINAL_CREDENTIAL_REQUIRED"),{code:"TERMINAL_CREDENTIAL_REQUIRED"});const response=await fetch(url,{...init,headers:{...headers,...init?.headers}});if(!response.ok){const parsed=await readApiError(response);throw Object.assign(new Error(parsed.issue.message),{code:parsed.code,issue:parsed.issue});}return response.json()},[credential,headers]);
 function showError(error:unknown){const value=error as {code?:string;message?:string;issue?:{title:string;message:string}};if(value.code==="TERMINAL_CREDENTIAL_REQUIRED"){setNotice({tone:"info",title:"Conecta esta terminal",message:"Escribe la credencial vigente del dispositivo. Se mantendrá únicamente en memoria durante esta pantalla."});return;}const issue=value.issue??cashierIssue(value.code??"UNKNOWN",value.message);setNotice({tone:"error",title:issue.title,message:issue.message});}
 const refreshOrder=useCallback(async(id=order?.id)=>{if(!id)return null;const body=await api(`/api/pos2/orders/${id}`);setOrder(body.order);return body.order as OrderDto},[api,order?.id]);
 async function ensureOrder(){if(order)return order;if(!context?.cashSessionId)throw Object.assign(new Error(),{code:"CASH_SESSION_NOT_OPEN"});const created=await api("/api/pos2/orders",{method:"POST",body:JSON.stringify({operationId:operationId(),branchId:context.branchId,registerId:context.registerId,cashSessionId:context.cashSessionId})});return refreshOrder(created.id);}
 function localOrder(draft:Pos2LocalDraft):OrderDto{return{id:draft.localDraftId,orderNumber:"Borrador sin conexión",status:"OPEN",version:draft.localRevision,subtotal:localEstimatedTotal(draft),discountTotal:"0.00",total:localEstimatedTotal(draft),createdAt:draft.createdAt,adjustments:[],lines:draft.lines.map(line=>({id:line.localLineId,productId:line.productId??null,variantId:line.variantId??null,displayName:line.displayName,quantity:line.quantity,unit:line.unit,unitPrice:line.estimatedUnitPrice??"0.00",lineSubtotal:(Number(line.estimatedUnitPrice??0)*Number(line.quantity)).toFixed(2),discountTotal:"0.00",lineTotal:(Number(line.estimatedUnitPrice??0)*Number(line.quantity)).toFixed(2)}))}}
 async function addProduct(selection:CatalogSelection){setBusy(true);setNotice(null);try{if(!online){if(!context?.cashSessionId)throw Object.assign(new Error(),{code:"CASH_SESSION_NOT_OPEN"});const draft=localDraft??createLocalDraft({branchId:context.branchId,registerId:context.registerId,terminalId:context.terminalId,cashSessionId:context.cashSessionId,actorId:userId});const updated=addLocalLine(draft,{...(selection.variant?{variantId:selection.variant.id}:{productId:selection.product.id}),quantity:"1",unit:"UNIT",displayName:selection.variant?`${selection.product.name} · ${selection.variant.name}`:selection.product.name,estimatedUnitPrice:selection.variant?.price??selection.product.price});await saveDraft(updated);setLocalDraft(updated);setOrder(localOrder(updated));setNotice({tone:"info",title:"Carrito guardado sin conexión",message:"Puedes seguir preparando la orden. El cobro estará disponible después de sincronizar."});return;}const current=await ensureOrder();if(!current)return;await api(`/api/pos2/orders/${current.id}/lines`,{method:"POST",body:JSON.stringify({operationId:operationId(),expectedOrderVersion:current.version,quantity:"1",...(selection.variant?{variantId:selection.variant.id}:{productId:selection.product.id})})});await refreshOrder(current.id);}catch(error){showError(error)}finally{setBusy(false)}}
 async function changeLine(lineId:string,quantity?:number){if(!order)return;setBusy(true);try{if(localDraft){const updated=quantity?updateLocalLineQuantity(localDraft,lineId,String(quantity)):removeLocalLine(localDraft,lineId);await saveDraft(updated);setLocalDraft(updated);setOrder(localOrder(updated));return;}await api(`/api/pos2/orders/${order.id}/lines/${lineId}`,{method:quantity?"PATCH":"DELETE",body:JSON.stringify({operationId:operationId(),expectedOrderVersion:order.version,...(quantity?{quantity:String(quantity)}:{})})});await refreshOrder();}catch(error){showError(error)}finally{setBusy(false)}}
 async function syncOfflineDraft(){if(!localDraft||!online)return;setBusy(true);try{await queueLocalDraft(localDraft);await withSyncLeader(()=>processPos2Queue(httpSyncTransport(async()=>credential||null)));const mapping=await getMapping(localDraft.localDraftId);if(!mapping)throw new Error("El borrador requiere revisión antes de continuar.");const stored=await getDraft(localDraft.localDraftId);void stored;setLocalDraft(null);await refreshOrder(mapping.serverOrderId);setNotice({tone:"success",title:"Orden sincronizada",message:"El total fue recalculado por el servidor. Revísalo antes de cobrar."});}catch(error){showError(error)}finally{setBusy(false)}}
 async function voidCurrent(){if(!order||!confirm("¿Anular esta orden? Esta acción no puede deshacerse."))return;if(localDraft){const empty={...localDraft,lines:[],state:"DRAFT" as const,updatedAt:new Date().toISOString()};await saveDraft(empty);setLocalDraft(null);setOrder(null);return;}setBusy(true);try{await api(`/api/pos2/orders/${order.id}/transition`,{method:"POST",body:JSON.stringify({action:"VOID",reason:"Anulada por cajero",operationId:operationId(),expectedOrderVersion:order.version})});setOrder(null);setNotice({tone:"success",title:"Orden anulada",message:"Puedes iniciar una nueva venta."});}catch(error){showError(error)}finally{setBusy(false)}}
 async function beginPayment(){if(!order)return;if(localDraft){setNotice({tone:"info",title:online?"Sincroniza antes de cobrar":"Cobro disponible al reconectar",message:online?"Confirma la sincronización para recalcular precios y promociones en servidor.":"El borrador está seguro en este dispositivo. No se permite confirmar pagos sin conexión."});return;}setBusy(true);try{await api(`/api/pos2/orders/${order.id}/transition`,{method:"POST",body:JSON.stringify({action:"BEGIN_PAYMENT",operationId:operationId(),expectedOrderVersion:order.version})});await refreshOrder();setView("PAYMENT");}catch(error){showError(error)}finally{setBusy(false)}}
 async function leavePayment(){if(!order||busy)return;if(order.status==="PAYMENT_PENDING"){setBusy(true);try{await api(`/api/pos2/orders/${order.id}/transition`,{method:"POST",body:JSON.stringify({action:"RESUME",operationId:operationId(),expectedOrderVersion:order.version})});await refreshOrder();}catch(error){showError(error)}finally{setBusy(false)}}setView("SALE")}
 async function complete(payments:UiPayment[]){if(!order||!context?.cashSessionId)return;const id=completeId??operationId();setCompleteId(id);setBusy(true);setNotice(null);try{const result=await api(`/api/pos2/orders/${order.id}/complete`,{method:"POST",body:JSON.stringify({operationId:id,expectedOrderVersion:order.version,cashSessionId:context.cashSessionId,payments:payments.map(item=>({method:item.method,amount:item.amount,...(item.tendered?{cashTendered:item.tendered}:{}),...(item.reference?{reference:item.reference}:{})}))})});setSale({...result,uiPayments:payments,change:paymentSummary(order.total,payments).change});setOrder(null);setCompleteId(null);setVerifying(false);setView("SUCCESS");}catch(error){const value=error as {code?:string};if(!value.code||value.code.startsWith("HTTP_")){setVerifying(true);setNotice({tone:"info",title:"Resultado por confirmar",message:"La conexión se interrumpió. Conservamos la misma operación; usa “Consultar misma operación” para verificarla sin cobrar dos veces."});}else showError(error)}finally{setBusy(false)}}
 async function applyAdjustment(rule:AdjustmentRuleDto,beneficiaryId:string,reason:string,authorized:boolean){if(!order)return;setBusy(true);try{await api(`/api/pos2/orders/${order.id}/adjustments`,{method:"POST",body:JSON.stringify({action:rule.kind,ruleVersionId:rule.id,operationId:operationId(),expectedOrderVersion:order.version,...(beneficiaryId?{beneficiaryId}:{}),...((rule.requiresAuthorization||rule.kind==="COURTESY")&&authorized?{authorizedById:userId}:{}),...(reason?{reason}:{})})});await refreshOrder();setAdjustOpen(false);}catch(error){showError(error)}finally{setBusy(false)}}
 async function switchContext(index:number){setContextIndex(index);setOrder(null);setSale(null);setView("SALE");const next=contexts[index];if(!next||next.branchId===context?.branchId)return;setBusy(true);try{const response=await fetch(`/api/pos2/sync/snapshot?branchId=${encodeURIComponent(next.branchId)}`,{headers:{"x-maestro-terminal-id":next.terminalId,"x-maestro-terminal-credential":credential}});if(!response.ok)throw await readApiError(response);const data=await response.json() as {categories:SnapshotCategory[];prices:Record<string,{amount:string}|null>};const mapped:CatalogCategoryDto[]=[];for(const category of data.categories){const products:CatalogCategoryDto["products"]=[];for(const product of category.products){const available=product.effective.available??Boolean(product.effective.enabled&&product.effective.availability==="AVAILABLE");products.push({id:product.id,name:product.name,sku:product.sku,internalCode:product.internalCode,barcode:product.barcode,icon:product.icon,imageAlt:product.imageAlt,available,price:product.variants.length?null:data.prices[`PRODUCT:${product.id}`]?.amount??null,variants:product.variants.map(variant=>({id:variant.id,name:variant.name,sku:variant.sku,available:variant.active&&available,price:data.prices[`VARIANT:${variant.id}`]?.amount??null}))});}mapped.push({id:category.id,name:category.name,icon:category.icon,products});}setCatalog(mapped);}catch(error){showError(error)}finally{setBusy(false)}}
 function newSale(){setSale(null);setOrder(null);setCompleteId(null);setVerifying(false);setView("SALE")}
 if(!contexts.length)return <main className={styles.root}><div className="pos2-setup"><h1>POS 2.0 necesita configuración</h1><p>Crea un Register y enrola una Terminal activa en una sucursal para comenzar.</p><a href="/administration/pos2/cash">Abrir administración de caja</a></div></main>;
 return <main className={styles.root}>
  <header className="pos2-topbar"><div className="pos2-brand"><span>M</span><div><b>MAESTRO</b><small>Punto de Venta 2.0</small></div></div><div className="pos2-context"><select aria-label="Contexto de caja" value={contextIndex} onChange={event=>switchContext(Number(event.target.value))}>{contexts.map((item,index)=><option value={index} key={`${item.terminalId}-${item.registerId}`}>{item.branchName} · {item.registerName}</option>)}</select><span className={online?"online":"offline"}>{online?"● En línea":"● Sin conexión"}</span><label className={`pos2-credential ${credential?"connected":""}`}><span>{credential?"Terminal conectada":"Credencial de terminal"}</span><input aria-label="Credencial de terminal" type="password" value={credential} onChange={event=>setCredential(event.target.value.trim())} autoComplete="off" placeholder="Conectar dispositivo"/></label><div className="pos2-user"><span>{userName.slice(0,1).toUpperCase()}</span><b>{userName}</b></div></div></header>
  <nav className="pos2-nav"><button className={view==="SALE"||view==="PAYMENT"||view==="SUCCESS"?"active":""} onClick={()=>setView("SALE")}>Venta</button><button className={view==="ORDERS"?"active":""} onClick={()=>setView("ORDERS")}>Órdenes</button><button className={view==="SALES"?"active":""} onClick={()=>setView("SALES")}>Ventas recientes</button><button className={view==="CASH"?"active":""} onClick={()=>setView("CASH")}>Caja</button></nav>
  {notice&&<div className={`pos2-notice ${notice.tone}`} role="alert"><div><b>{notice.title}</b><span>{notice.message}</span></div>{localDraft&&online?<button className="pos2-sync-now" onClick={syncOfflineDraft}>Sincronizar ahora</button>:<button onClick={()=>setNotice(null)}>×</button>}</div>}
  {view==="SALE"&&<div className="pos2-workspace"><CatalogPanel categories={catalog} disabled={busy} onSelect={addProduct}/><CartPanel order={order} busy={busy} onQuantity={(id,qty)=>changeLine(id,qty)} onRemove={id=>changeLine(id)} onAdjust={()=>setAdjustOpen(true)} onVoid={voidCurrent} onPay={beginPayment}/></div>}
  {view==="PAYMENT"&&order&&<PaymentFlow total={order.total} busy={busy} verifying={verifying} onBack={leavePayment} onComplete={complete}/>}
  {view==="SUCCESS"&&sale&&<section className="pos2-success"><span>✓</span><small>Venta completada</small><h1>{sale.saleNumber}</h1><p>Total cobrado <b>{new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(Number(sale.total))}</b></p><ul>{sale.uiPayments.map((payment,index)=><li key={`${payment.method}-${index}`}><span>{payment.method==="CASH"?"Efectivo":payment.method==="CARD"?"Tarjeta":"Transferencia"}</span><b>{new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(Number(payment.amount))}</b></li>)}</ul>{Number(sale.change)>0&&<strong className="pos2-success-change"><span>Cambio</span>{new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(Number(sale.change))}</strong>}<div><a href={`/pos2/receipt/${sale.id}`} target="_blank">Ver recibo</a><button onClick={newSale}>Nueva venta</button></div></section>}
  {view==="ORDERS"&&<OperationalList title="Órdenes abiertas" subtitle="Recupera órdenes abiertas o pendientes de pago." button="Cargar órdenes" onLoad={async()=>api(`/api/pos2/orders?branchId=${context!.branchId}&registerId=${context!.registerId}`)} render={value=>((value as {orders?:OpenOrderItem[]}).orders??[]).map(item=><button key={item.id} onClick={async()=>{await refreshOrder(item.id);setView(item.status==="PAYMENT_PENDING"?"PAYMENT":"SALE")}}><span><b>{item.orderNumber}</b><small>{item.status} · {item.lines.length} artículos</small></span><strong>${Number(item.total).toFixed(2)}</strong></button>)}/>}
  {view==="SALES"&&<RecentSalesPanel branchId={context!.branchId} cashSessionId={context!.cashSessionId} api={api} capabilities={capabilities} onError={showError}/>}
  {view==="CASH"&&<CashPanel context={context!} credential={credential} capabilities={capabilities} onError={showError} onOpened={()=>location.reload()}/>}
  {adjustOpen&&<AdjustmentDialog rules={rules.filter(rule=>rule.kind==="DISCOUNT"?capabilities["pos.discount.apply"]:capabilities["pos.courtesy.apply"])} people={people} busy={busy} onClose={()=>setAdjustOpen(false)} onApply={applyAdjustment}/>}
 </main>;
}

function OperationalList({title,subtitle,button,onLoad,render}:{title:string;subtitle:string;button:string;onLoad:()=>Promise<unknown>;render:(data:unknown)=>React.ReactNode}){const [data,setData]=useState<unknown>(null),[error,setError]=useState("");async function load(){setError("");try{setData(await onLoad())}catch(value){setError((value as Error).message)}}return <section className="pos2-list"><header><div><h1>{title}</h1><p>{subtitle}</p></div><button onClick={load}>{button}</button></header>{error&&<p className="pos2-list-error">{error}</p>}<div>{data?render(data):<p className="pos2-muted">Pulsa “{button}” para consultar.</p>}</div></section>}
function AdjustmentDialog({rules,people,busy,onClose,onApply}:{rules:AdjustmentRuleDto[];people:PersonDto[];busy:boolean;onClose:()=>void;onApply:(rule:AdjustmentRuleDto,person:string,reason:string,authorized:boolean)=>void}){const [ruleId,setRuleId]=useState(rules[0]?.id??""),[person,setPerson]=useState(""),[reason,setReason]=useState(""),[authorized,setAuthorized]=useState(false);const rule=rules.find(item=>item.id===ruleId),needsAuthorization=Boolean(rule&&(rule.requiresAuthorization||rule.kind==="COURTESY"));return <div className="pos2-modal-backdrop"><div className="pos2-modal"><div className="pos2-modal-head"><div><small>Ajustar orden</small><h2>Descuento o cortesía</h2></div><button onClick={onClose}>×</button></div>{rules.length?<div className="pos2-form"><label>Regla<select value={ruleId} onChange={event=>{setRuleId(event.target.value);setAuthorized(false)}}>{rules.map(item=><option key={item.id} value={item.id}>{item.kind==="DISCOUNT"?"Descuento":"Cortesía"} · {item.name}</option>)}</select></label>{rule?.requiresBeneficiary&&<label>Beneficiario<select value={person} onChange={event=>setPerson(event.target.value)}><option value="">Selecciona…</option>{people.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<label>Motivo<input value={reason} onChange={event=>setReason(event.target.value)} placeholder="Motivo operativo"/></label>{needsAuthorization&&<label className="pos2-authorization"><input type="checkbox" checked={authorized} onChange={event=>setAuthorized(event.target.checked)}/><span><b>Autorizar con mi sesión</b><small>Tu identidad y permisos actuales quedarán registrados como autorización.</small></span></label>}<button className="pos2-pay" disabled={busy||!rule||(rule.requiresBeneficiary&&!person)||(needsAuthorization&&!authorized)||(rule.kind==="COURTESY"&&reason.trim().length<3)} onClick={()=>rule&&onApply(rule,person,reason,authorized)}>Aplicar ajuste</button></div>:<div className="pos2-empty"><b>No hay reglas disponibles</b><span>Tu perfil no tiene permisos o no existen reglas vigentes.</span></div>}</div></div>}
function CashPanel({context,credential,capabilities,onError,onOpened}:{context:PosContextDto;credential:string;capabilities:Record<CapabilityKey,boolean>;onError:(error:unknown)=>void;onOpened:()=>void}){const [amount,setAmount]=useState("0.00"),[reason,setReason]=useState(""),[kind,setKind]=useState<"CASH_IN"|"CASH_OUT">("CASH_IN"),[declared,setDeclared]=useState("0.00"),[busy,setBusy]=useState(false);const headers={"Content-Type":"application/json","x-maestro-terminal-id":context.terminalId,"x-maestro-terminal-credential":credential};async function command(path:string,body:Record<string,unknown>){setBusy(true);try{const response=await fetch(path,{method:"POST",headers,body:JSON.stringify({operationId:operationId(),...body})});if(!response.ok){const parsed=await readApiError(response);throw Object.assign(new Error(parsed.issue.message),{issue:parsed.issue})}onOpened()}catch(error){onError(error)}finally{setBusy(false)}}return <section className="pos2-list"><header><div><h1>Sesión de caja</h1><p>{context.branchName} · {context.registerName}</p></div><span className={context.cashSessionId?"pos2-pill-open":"pos2-pill-closed"}>{context.cashSessionId?"Abierta":"Cerrada"}</span></header>{context.cashSessionId?<div className="pos2-cash-card"><b>Caja lista para operar</b><span>Sesión {context.cashSessionId}</span>{(capabilities["cash.in.create"]||capabilities["cash.out.create"])&&<div className="pos2-form"><label>Movimiento<select value={kind} onChange={event=>setKind(event.target.value as "CASH_IN"|"CASH_OUT")}><option value="CASH_IN">Agregar efectivo</option><option value="CASH_OUT">Retirar efectivo</option></select></label><label>Monto<input inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)}/></label><label>Motivo<input value={reason} onChange={event=>setReason(event.target.value)}/></label><button className="pos2-adjust" disabled={busy||reason.trim().length<3} onClick={()=>command(`/api/pos2/cash-sessions/${context.cashSessionId}/movements`,{type:kind,amount,reason})}>Registrar movimiento</button></div>}{capabilities["cash.session.close"]&&<div className="pos2-form"><label>Efectivo declarado<input inputMode="decimal" value={declared} onChange={event=>setDeclared(event.target.value)}/></label><button className="pos2-pay" disabled={busy} onClick={()=>confirm("¿Cerrar la sesión de caja?")&&command(`/api/pos2/cash-sessions/${context.cashSessionId}/close`,{declaredCash:declared})}>Cerrar caja</button></div>}<a href="/administration/pos2/cash">Ver control administrativo</a></div>:<div className="pos2-cash-card"><label>Fondo inicial<input inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)}/></label><button className="pos2-pay" disabled={busy||!credential||!capabilities["cash.session.open"]} onClick={()=>command("/api/pos2/cash-sessions",{branchId:context.branchId,registerId:context.registerId,openingCash:amount})}>{busy?"Abriendo…":"Abrir sesión"}</button></div>}</section>}
