"use client";
import { useState } from "react";
import type { CapabilityKey } from "@/lib/pos2/capabilityPolicy";
import { generateClientOperationId } from "@/lib/pos2/offline/canonical";

type Api=(url:string,init?:RequestInit)=>Promise<unknown>;
type SaleRow={id:string;saleNumber:string;status:string;completedAt:string;total:string;cashier:{name:string};payments:Array<{method:string;amount:string}>};
type SaleLine={id:string;productNameSnapshot:string;variantNameSnapshot:string|null;quantity:string;unit:string;lineTotal:string};
type Payment={id:string;method:"CASH"|"CARD"|"TRANSFER";amount:string};
type Detail=SaleRow&{lines:SaleLine[];payments:Payment[];discountTotal:string;refundableAmount:string;returnableQuantities:Array<{saleLineId:string;returnable:string;unit:"UNIT"|"ML"}>;cancellation:unknown;returns:unknown[];refunds:unknown[]};
const currency=(value:string)=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(Number(value));
function refundAllocations(payments:Payment[],requested:string){let remaining=Number(requested);const result:Array<{paymentId:string;amount:string}>=[];for(const payment of payments){if(remaining<=0)break;const amount=Math.min(remaining,Number(payment.amount));if(amount>0)result.push({paymentId:payment.id,amount:amount.toFixed(2)});remaining-=amount}return result}

export default function RecentSalesPanel({branchId,cashSessionId,api,capabilities,onError}:{branchId:string;cashSessionId:string|null;api:Api;capabilities:Record<CapabilityKey,boolean>;onError:(error:unknown)=>void}){
 const [sales,setSales]=useState<SaleRow[]>([]),[detail,setDetail]=useState<Detail|null>(null),[query,setQuery]=useState(""),[busy,setBusy]=useState(false),[action,setAction]=useState<"CANCEL"|"RETURN"|"REFUND"|null>(null);
 async function load(){setBusy(true);try{const value=await api(`/api/pos2/sales?branchId=${branchId}${cashSessionId?`&cashSessionId=${cashSessionId}`:""}&take=100`) as {sales:SaleRow[]};setSales(value.sales)}catch(error){onError(error)}finally{setBusy(false)}}
 async function select(id:string){setBusy(true);try{setDetail(await api(`/api/pos2/sales/${id}`) as Detail)}catch(error){onError(error)}finally{setBusy(false)}}
 const shown=sales.filter(item=>item.saleNumber.toLowerCase().includes(query.toLowerCase()));
 return <section className="pos2-list pos2-sales"><header><div><h1>Ventas recientes</h1><p>Consulta recibos y realiza operaciones compensatorias autorizadas.</p></div><button onClick={load}>{busy?"Consultando…":"Cargar ventas"}</button></header>
  <div className="pos2-sales-layout"><aside><input aria-label="Buscar número de venta" placeholder="Buscar número de venta" value={query} onChange={event=>setQuery(event.target.value)}/>{shown.map(item=><button key={item.id} onClick={()=>select(item.id)}><span><b>{item.saleNumber}</b><small>{new Date(item.completedAt).toLocaleString("es-MX")} · {item.cashier.name}</small><small>{item.payments.map(payment=>payment.method).join(" + ")}</small></span><strong>{currency(item.total)}</strong></button>)}{!sales.length&&<p className="pos2-muted">Carga las ventas de esta caja para comenzar.</p>}</aside>
   <article>{detail?<><header><div><small>{detail.status}</small><h2>{detail.saleNumber}</h2></div><strong>{currency(detail.total)}</strong></header>{detail.lines.map(line=><div className="pos2-sale-line" key={line.id}><span>{line.productNameSnapshot}{line.variantNameSnapshot?` · ${line.variantNameSnapshot}`:""}<small>{Number(line.quantity)} {line.unit==="UNIT"?"pza":"ml"}</small></span><b>{currency(line.lineTotal)}</b></div>)}<div className="pos2-sale-meta"><span>Pagos: {detail.payments.map(item=>`${item.method} ${currency(item.amount)}`).join(" · ")}</span><span>Disponible para reembolso: {currency(detail.refundableAmount)}</span></div><div className="pos2-sale-actions"><a target="_blank" href={`/pos2/receipt/${detail.id}`}>Recibo</a>{capabilities["pos.sale.cancel"]&&!detail.cancellation&&<button onClick={()=>setAction("CANCEL")}>Cancelar venta</button>}{capabilities["pos.return.create"]&&detail.returnableQuantities.some(item=>Number(item.returnable)>0)&&<button onClick={()=>setAction("RETURN")}>Devolver</button>}{capabilities["pos.refund.create"]&&Number(detail.refundableAmount)>0&&<button onClick={()=>setAction("REFUND")}>Reembolsar</button>}</div></>:<div className="pos2-empty"><b>Selecciona una venta</b><span>Aquí verás artículos, pagos y operaciones disponibles.</span></div>}</article>
  </div>{detail&&action&&<CompensationDialog kind={action} sale={detail} cashSessionId={cashSessionId} busy={busy} onClose={()=>setAction(null)} onSubmit={async body=>{if(!confirm("Esta operación genera un documento compensatorio. ¿Deseas continuar?"))return;setBusy(true);try{const path=action==="CANCEL"?"cancel":action==="RETURN"?"returns":"refunds";await api(`/api/pos2/sales/${detail.id}/${path}`,{method:"POST",body:JSON.stringify({operationId:generateClientOperationId(),...body})});setAction(null);await select(detail.id);await load()}catch(error){onError(error)}finally{setBusy(false)}}}/>}</section>;
}

function CompensationDialog({kind,sale,cashSessionId,busy,onClose,onSubmit}:{kind:"CANCEL"|"RETURN"|"REFUND";sale:Detail;cashSessionId:string|null;busy:boolean;onClose:()=>void;onSubmit:(body:Record<string,unknown>)=>void}){
 const returnable=sale.returnableQuantities.find(item=>Number(item.returnable)>0),line=returnable? sale.lines.find(item=>item.id===returnable.saleLineId):null;
 const [quantity,setQuantity]=useState(returnable?.returnable??"1"),[disposition,setDisposition]=useState("RESTOCK"),[amount,setAmount]=useState(sale.refundableAmount),[reason,setReason]=useState("");
 function submit(){if(kind==="CANCEL")onSubmit({reasonCode:"CUSTOMER_REQUEST",reasonText:reason,cashSessionId});else if(kind==="RETURN"&&returnable)onSubmit({reasonCode:"CUSTOMER_RETURN",reasonText:reason,lines:[{saleLineId:returnable.saleLineId,quantity,unit:returnable.unit,disposition}]});else if(kind==="REFUND")onSubmit({amount,reasonCode:"RETURN",reasonText:reason,cashSessionId,allocations:refundAllocations(sale.payments,amount)});}
 return <div className="pos2-modal-backdrop"><div className="pos2-modal"><div className="pos2-modal-head"><div><small>Venta {sale.saleNumber}</small><h2>{kind==="CANCEL"?"Cancelar venta":kind==="RETURN"?"Registrar devolución":"Registrar reembolso"}</h2></div><button onClick={onClose}>×</button></div><div className="pos2-form">{kind==="RETURN"&&<><p>{line?.productNameSnapshot}</p><label>Cantidad máxima {returnable?.returnable}<input inputMode="decimal" value={quantity} onChange={event=>setQuantity(event.target.value)}/></label><label>Destino<select value={disposition} onChange={event=>setDisposition(event.target.value)}><option value="RESTOCK">Regresar a inventario</option><option value="DAMAGED">Dañado</option><option value="DISCARD">Desechar</option></select></label></>}{kind==="REFUND"&&<label>Monto disponible {currency(sale.refundableAmount)}<input inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)}/></label>}<label>Motivo<input value={reason} onChange={event=>setReason(event.target.value)} placeholder="Explica brevemente"/></label><button className="pos2-pay" disabled={busy||reason.trim().length<3} onClick={submit}>{busy?"Procesando…":"Confirmar operación"}</button></div></div></div>;
}
