import "server-only";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";

export async function resolveOrderInventoryAvailability(orderId: string) {
  const order = await prisma.pos2Order.findUniqueOrThrow({ where: { id: orderId }, include: { lines: true } }); const variantIds = order.lines.map((l) => l.variantId).filter((id): id is string => Boolean(id)); const variants = await prisma.posProductVariant.findMany({ where: { id: { in: variantIds } }, include: { product: true, ingredients: { include: { inventoryProduct: true } } } }); const map = new Map(variants.map((v) => [v.id, v])); const requirements = new Map<string, Prisma.Decimal>(); const classifications = [];
  for (const line of order.lines) { if (!line.variantId) { classifications.push({ lineId: line.id, classification: line.productId ? "UNCONFIGURED" : "NON_TRACKED" }); continue; } const variant = map.get(line.variantId); if (!variant?.product.inventoryTracked) { classifications.push({ lineId: line.id, classification: "NON_TRACKED" }); continue; } if (!variant.ingredients.length) { classifications.push({ lineId: line.id, classification: "UNCONFIGURED" }); continue; } classifications.push({ lineId: line.id, classification: variant.ingredients.length === 1 && variant.ingredients[0].quantity.equals(1) ? "DIRECT" : "RECIPE" }); for (const ingredient of variant.ingredients) requirements.set(ingredient.inventoryProductId, (requirements.get(ingredient.inventoryProductId) ?? new Prisma.Decimal(0)).plus(ingredient.quantity.times(line.quantity))); }
  const ids = [...requirements.keys()]; const balances = await prisma.inventoryBalance.findMany({ where: { branchId: order.branchId, inventoryProductId: { in: ids } } }); const balanceMap = new Map(balances.map((b) => [b.inventoryProductId, b])); return { orderId, informativeOnly: true, classifications, requirements: ids.map((id) => { const required = requirements.get(id)!; const available = balanceMap.get(id)?.quantity ?? new Prisma.Decimal(0); return { inventoryProductId: id, required: required.toFixed(6), available: available.toFixed(6), sufficient: available.greaterThanOrEqualTo(required) }; }) };
}
