import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { generateOperationId } from "@/lib/pos2/operationId";
import { publishAdjustmentAction } from "./actions";

export default async function PromotionsPage() {
  await requireAdmin();
  const [versions, branches] = await Promise.all([prisma.adjustmentVersion.findMany({ include: { definition: true, branch: { select: { name: true } }, termination: true }, orderBy: { createdAt: "desc" }, take: 100 }), prisma.branch.findMany({ where: { active: true }, select: { id: true, name: true }, orderBy: { name: "asc" } })]);
  const field = "rounded border border-outline-variant bg-background px-2 py-1";
  return <main className="mx-auto max-w-7xl space-y-6 p-6">
    <header><h1 className="text-2xl font-bold">Promociones y ajustes POS 2.0</h1><p className="text-sm text-on-surface-variant">Versiones inmutables. Pricing conserva el precio de lista; los descuentos, promociones y cortesías se registran por separado.</p></header>
    <form action={publishAdjustmentAction} className="grid gap-3 rounded-xl border p-4 text-sm md:grid-cols-3"><h2 className="font-semibold md:col-span-3">Publicar versión inmutable</h2><input type="hidden" name="operationId" value={generateOperationId()}/><input className={field} name="code" required placeholder="Código"/><input className={field} name="name" required placeholder="Nombre"/><select className={field} name="kind"><option>PROMOTION</option><option>DISCOUNT</option><option>COURTESY</option></select><select className={field} name="mechanic"><option>PERCENT_OFF</option><option>FIXED_AMOUNT_OFF</option><option>FIXED_BUNDLE_PRICE</option></select><input className={field} name="percentage" type="number" step="0.0001" placeholder="Porcentaje"/><input className={field} name="amount" type="number" step="0.01" placeholder="Monto / precio bundle"/><input className={field} name="bundleQuantity" type="number" step="0.000001" placeholder="Cantidad bundle (ej. 4)"/><select className={field} name="scope"><option>GLOBAL</option><option>BRANCH</option></select><select className={field} name="branchId"><option value="">Sucursal si aplica</option>{branches.map((branch)=><option key={branch.id} value={branch.id}>{branch.name}</option>)}</select><select className={field} name="targetType"><option>ENTIRE_ORDER</option><option>PRODUCT</option><option>VARIANT</option><option>CATEGORY</option></select><input className={field} name="targetId" placeholder="ID target si aplica"/><input className={field} name="priority" type="number" defaultValue="0"/><select className={field} name="stacking"><option>EXCLUSIVE</option><option>STACKABLE</option></select><input className={field} name="validFrom" type="datetime-local" required/><input className={field} name="validTo" type="datetime-local"/><input className={field} name="timezone" defaultValue="America/Mexico_City"/><label><input name="requiresBeneficiary" type="checkbox"/> Requiere beneficiario</label><label><input name="requiresAuthorization" type="checkbox"/> Requiere autorización</label><button className="rounded bg-primary px-3 py-2 text-on-primary">Publicar</button></form>
    <section className="space-y-2"><h2 className="text-lg font-semibold">Historial</h2>{versions.map((item) => <article className="grid gap-2 rounded-lg border p-3 text-sm md:grid-cols-4" key={item.id}><div><strong>{item.definition.name}</strong><br/><code>{item.definition.code}</code> · v{item.version}</div><div>{item.kind}<br/>{item.mechanic}</div><div>{item.scope === "GLOBAL" ? "Global" : item.branch?.name}<br/>prioridad {item.priority} · {item.stacking}</div><div>{item.validFrom.toLocaleString("es-MX")}<br/>{item.termination ? `Finalizada: ${item.termination.effectiveAt.toLocaleString("es-MX")}` : item.validTo ? `Hasta: ${item.validTo.toLocaleString("es-MX")}` : "Sin fin publicado"}</div></article>)}</section>
  </main>;
}
