import Link from "next/link";
import { Card } from "@/components/ui/Card";
import { listEmployees } from "@/lib/workforce/employment/service";

function money(value: { toString(): string }, currency: string | null) { return `${currency ?? "???"} ${Number(value.toString()).toFixed(2)}`; }

export default async function WorkforceEmployeesPage() {
  const employees = await listEmployees();
  return <section><div className="mb-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><Card><p className="text-xs text-on-surface-variant">Empleados</p><p className="text-2xl font-bold">{employees.length}</p></Card><Card><p className="text-xs text-on-surface-variant">Activos</p><p className="text-2xl font-bold">{employees.filter((e) => e.employments[0]?.status === "ACTIVE").length}</p></Card><Card><p className="text-xs text-on-surface-variant">Sin login</p><p className="text-2xl font-bold">{employees.filter((e) => !e.userId).length}</p></Card><Card><p className="text-xs text-on-surface-variant">Sin empleo</p><p className="text-2xl font-bold">{employees.filter((e) => e.employments.length === 0).length}</p></Card></div><div className="overflow-x-auto rounded-xl border border-outline-variant"><table className="min-w-[760px] w-full text-left text-sm"><thead className="bg-surface-container"><tr><th className="p-3">Nombre</th><th className="p-3">Estado</th><th className="p-3">HOME</th><th className="p-3">Tarifa vigente</th><th className="p-3">Identidad</th></tr></thead><tbody>{employees.map((employee) => { const employment=employee.employments[0]; const home=employment?.branchAssignments.find((a)=>a.type==="HOME"); const rate=employment?.payRates[0]; return <tr key={employee.id} className="border-t border-outline-variant"><td className="p-3"><Link className="font-semibold text-primary hover:underline" href={`/administration/workforce/employees/${employee.id}`}>{employee.displayName ?? "Sin nombre"}</Link><p className="text-xs text-on-surface-variant">{employee.employeeNumber ?? "Sin número"}</p></td><td className="p-3">{employment?.status ?? "SIN EMPLEO"}</td><td className="p-3">{home?.branch.name ?? "—"}</td><td className="p-3">{rate ? money(rate.amount,rate.currency) : "—"}</td><td className="p-3">{employee.user ? `@${employee.user.username}` : "Sin User"}</td></tr>; })}</tbody></table></div></section>;
}
