import { NextResponse } from "next/server";
import { DomainError } from "@/lib/domain/errors";
import { hashPayload } from "@/lib/pos2/payloadHash";
import { getCurrentCommandActor } from "@/lib/pos2/currentActor";
import { pos2ErrorResponse, requireOrderTerminal, requireTerminalBranch, requireTerminalRequest } from "@/lib/pos2/http";
import { addOrderLine, createOrder, removeOrderLine, updateOrderLineQuantity, voidOrder } from "@/lib/pos2/orders/manageOrders";
import { recordPos2OperationTrace, type Pos2OperationTrace } from "@/lib/pos2/operationTrace";

export const dynamic="force-dynamic";
export async function POST(request:Request){let actor:Awaited<ReturnType<typeof getCurrentCommandActor>>|undefined;let operationId:string|undefined;let trace:Pos2OperationTrace|undefined;try{actor=await getCurrentCommandActor();const body=await request.json() as Record<string,unknown>,payload=(body.payload??{}) as Record<string,unknown>,commandType=String(body.commandType);operationId=String(body.operationId);const branchId=String(body.branchId),orderId=typeof payload.orderId==="string"?payload.orderId:"";trace={actor,operation:commandType,operationId,branchId,orderId:orderId||undefined,terminalId:request.headers.get('x-maestro-terminal-id')??undefined,correlationId:request.headers.get('x-request-id')??request.headers.get('x-vercel-id')??undefined};await recordPos2OperationTrace({...trace,outcome:'ATTEMPTED'});const terminalId=await requireTerminalRequest(request);trace={...trace,terminalId};if(body.actorId!==actor.id||hashPayload(body.originalPayload)!==body.payloadHash)throw new DomainError("VALIDATION_ERROR",{field:"envelope"});await requireTerminalBranch(terminalId,branchId);if(orderId)await requireOrderTerminal(terminalId,orderId);const common={actor,operationId};const outcome=commandType==="CreateOrder"?await createOrder({...common,branchId,registerId:String(payload.registerId),terminalId,cashSessionId:String(payload.cashSessionId)}):commandType==="AddOrderLine"?await addOrderLine({...common,orderId,expectedOrderVersion:Number(payload.expectedOrderVersion),quantity:String(payload.quantity),...(payload.variantId?{variantId:String(payload.variantId)}:{productId:String(payload.productId)})}):commandType==="UpdateOrderLineQuantity"?await updateOrderLineQuantity({...common,orderId,lineId:String(payload.lineId),quantity:String(payload.quantity),expectedOrderVersion:Number(payload.expectedOrderVersion)}):commandType==="RemoveOrderLine"?await removeOrderLine({...common,orderId,lineId:String(payload.lineId),expectedOrderVersion:Number(payload.expectedOrderVersion)}):commandType==="VoidOrder"?await voidOrder({...common,orderId,expectedOrderVersion:Number(payload.expectedOrderVersion),reason:String(payload.reason??"")}):(()=>{throw new DomainError("VALIDATION_ERROR",{field:"commandType"});})();await recordPos2OperationTrace({...trace,outcome:'SUCCESS'});return NextResponse.json({replayed:outcome.replayed,result:outcome.result},{headers:{"Cache-Control":"no-store"}});}catch(error){if(actor&&trace)await recordPos2OperationTrace({...trace,outcome:'FAIL',error});return pos2ErrorResponse(error,operationId);}}
