import { NextResponse } from "next/server";
import { DomainError } from "@/lib/domain/errors";
import { hashPayload } from "@/lib/pos2/payloadHash";
import { getCurrentCommandActor } from "@/lib/pos2/currentActor";
import { pos2ErrorResponse, requireOrderTerminal, requireTerminalBranch, requireTerminalRequest } from "@/lib/pos2/http";
import { addOrderLine, createOrder, removeOrderLine, updateOrderLineQuantity, voidOrder } from "@/lib/pos2/orders/manageOrders";

export const dynamic="force-dynamic";
export async function POST(request:Request){try{const terminalId=await requireTerminalRequest(request),actor=await getCurrentCommandActor(),body=await request.json() as Record<string,unknown>,payload=(body.payload??{}) as Record<string,unknown>,commandType=String(body.commandType),operationId=String(body.operationId),branchId=String(body.branchId);if(body.actorId!==actor.id||hashPayload(body.originalPayload)!==body.payloadHash)throw new DomainError("VALIDATION_ERROR",{field:"envelope"});await requireTerminalBranch(terminalId,branchId);const orderId=typeof payload.orderId==="string"?payload.orderId:"";if(orderId)await requireOrderTerminal(terminalId,orderId);const common={actor,operationId};const outcome=commandType==="CreateOrder"?await createOrder({...common,branchId,registerId:String(payload.registerId),terminalId,cashSessionId:String(payload.cashSessionId)}):commandType==="AddOrderLine"?await addOrderLine({...common,orderId,expectedOrderVersion:Number(payload.expectedOrderVersion),quantity:String(payload.quantity),...(payload.variantId?{variantId:String(payload.variantId)}:{productId:String(payload.productId)})}):commandType==="UpdateOrderLineQuantity"?await updateOrderLineQuantity({...common,orderId,lineId:String(payload.lineId),quantity:String(payload.quantity),expectedOrderVersion:Number(payload.expectedOrderVersion)}):commandType==="RemoveOrderLine"?await removeOrderLine({...common,orderId,lineId:String(payload.lineId),expectedOrderVersion:Number(payload.expectedOrderVersion)}):commandType==="VoidOrder"?await voidOrder({...common,orderId,expectedOrderVersion:Number(payload.expectedOrderVersion),reason:String(payload.reason??"")}):(()=>{throw new DomainError("VALIDATION_ERROR",{field:"commandType"});})();return NextResponse.json({replayed:outcome.replayed,result:outcome.result},{headers:{"Cache-Control":"no-store"}});}catch(error){return pos2ErrorResponse(error);}}
