"use client";
import { useCallback, useEffect, useState } from "react";
import { checkReachability, getLocalSyncHealth } from "@/lib/pos2/offline/health";
import { httpSyncTransport, processPos2Queue, withSyncLeader } from "@/lib/pos2/offline/coordinator";
import { createLocalDraft, enqueuePos2Command, listCommands, listDrafts, saveDraft } from "@/lib/pos2/offline/store";
import type { Pos2CommandEnvelope, Pos2LocalDraft, Pos2NetworkState, Pos2SyncHealth } from "@/lib/pos2/offline/types";
import { POS2_OFFLINE_DRAFTS_ENABLED, POS2_SYNC_ENABLED } from "@/lib/pos2/offline/flags";
import { refreshPos2Snapshot } from "@/lib/pos2/offline/cache";

type Context={actorId:string;branchId:string;registerId:string;terminalId:string;cashSessionId:string};
export default function SyncDiagnosticsClient({contexts}:{contexts:Array<Context&{label:string}>}){const[context,setContext]=useState<(Context&{label:string})|null>(contexts[0]??null),[credential,setCredential]=useState(""),[network,setNetwork]=useState<Pos2NetworkState>("OFFLINE"),[health,setHealth]=useState<Pos2SyncHealth|null>(null),[drafts,setDrafts]=useState<Pos2LocalDraft[]>([]),[commands,setCommands]=useState<Pos2CommandEnvelope[]>([]),[busy,setBusy]=useState(false);
 const refresh=useCallback(async()=>{const reach=await checkReachability(),terminal=context?.terminalId??"";setNetwork(reach.state);const[d,q,h]=await Promise.all([listDrafts(),listCommands(),getLocalSyncHealth(terminal,reach.state)]);setDrafts(d);setCommands(q);setHealth(h);},[context]);
 useEffect(()=>{const startup=window.setTimeout(()=>void refresh(),0);const change=()=>void refresh();window.addEventListener("maestro:pos2-offline-changed",change);window.addEventListener("online",change);window.addEventListener("offline",change);const timer=window.setInterval(change,60_000);return()=>{window.removeEventListener("maestro:pos2-offline-changed",change);window.removeEventListener("online",change);window.removeEventListener("offline",change);window.clearInterval(timer);window.clearTimeout(startup);};},[refresh]);
 async function createDraft(){if(!context||!POS2_OFFLINE_DRAFTS_ENABLED)return;const draft=createLocalDraft(context);await saveDraft(draft);await enqueuePos2Command({commandType:"CreateOrder",localDraftId:draft.localDraftId,payload:{registerId:context.registerId,cashSessionId:context.cashSessionId},actorId:context.actorId,terminalId:context.terminalId,branchId:context.branchId});await refresh();}
 async function sync(){if(!POS2_SYNC_ENABLED)return;setBusy(true);try{setNetwork("SYNCING");await withSyncLeader(async()=>{await processPos2Queue(httpSyncTransport(async()=>credential||null));if(context&&credential)await refreshPos2Snapshot({branchId:context.branchId,terminalId:context.terminalId,credential});});await refresh();}finally{setBusy(false);}}
 const banner=network==="OFFLINE"?"Sin conexión — los carritos se guardan localmente. Ninguna venta ni pago ha sido confirmado.":network==="DEGRADED"?"Conexión degradada — los precios y promociones cacheados siguen siendo estimaciones.":network==="SYNC_ERROR"?"Error de sincronización — revisa los conflictos antes de continuar.":network==="SYNCING"?"Sincronizando intenciones locales…":"Servidor alcanzable — CompleteSale continúa requiriendo confirmación en línea.";
 return <div className="space-y-5"><div className="rounded-lg border border-amber-400 bg-amber-50 p-3 text-sm text-amber-950"><strong>{network}</strong> · {banner}</div><section className="grid gap-3 rounded-xl border p-4 md:grid-cols-3"><select className="rounded border p-2" value={context?.terminalId??""} onChange={event=>setContext(contexts.find(item=>item.terminalId===event.target.value)??null)}>{contexts.map(item=><option key={item.terminalId} value={item.terminalId}>{item.label}</option>)}</select><input className="rounded border p-2" type="password" autoComplete="off" value={credential} onChange={event=>setCredential(event.target.value)} placeholder="Credencial terminal (sólo memoria)"/><div className="flex gap-2"><button className="rounded border px-3" onClick={()=>void createDraft()}>Crear draft local</button><button disabled={busy||!credential} className="rounded bg-primary px-3 text-on-primary disabled:opacity-50" onClick={()=>void sync()}>Sincronizar</button></div></section>{health&&<section className="grid gap-2 text-sm sm:grid-cols-3 lg:grid-cols-6">{[["Pendientes",health.pending],["Conflictos",health.conflicts],["Permanentes",health.failedPermanent],["Reintentos",health.retries],["Último sync",health.lastSuccessfulSync?new Date(health.lastSuccessfulSync).toLocaleString("es-MX"):"Nunca"],["Catálogo cache",health.cachedCatalogAt?new Date(health.cachedCatalogAt).toLocaleString("es-MX"):"Vacío"]].map(([label,value])=><div className="rounded border p-3" key={String(label)}><div className="text-on-surface-variant">{label}</div><strong>{value}</strong></div>)}</section>}<section><h2 className="font-semibold">Drafts persistentes ({drafts.length})</h2>{drafts.map(item=><div className="mt-2 rounded border p-2 text-sm" key={item.localDraftId}><code>{item.localDraftId}</code> · {item.state} · revisión local {item.localRevision} · servidor {item.serverOrderId??"sin asociar"}<div>Precios/promociones: ESTIMADOS · Venta: NO CONFIRMADA</div></div>)}</section><section><h2 className="font-semibold">Command queue ({commands.length})</h2>{commands.sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).map(item=><div className="mt-2 grid gap-1 rounded border p-2 text-xs md:grid-cols-4" key={item.operationId}><code>{item.commandType}</code><span>{item.status}</span><span>intentos {item.attemptCount}</span><span>{item.lastError?.code??(item.acknowledgedAt?"ACK":"—")}</span></div>)}</section></div>}
