-- POS 2.0 Phase 3I: versioned promotions, discounts and courtesies.
CREATE TYPE "AdjustmentKind" AS ENUM ('PROMOTION','DISCOUNT','COURTESY');
CREATE TYPE "AdjustmentMechanic" AS ENUM ('PERCENT_OFF','FIXED_AMOUNT_OFF','FIXED_BUNDLE_PRICE');
CREATE TYPE "AdjustmentScope" AS ENUM ('GLOBAL','BRANCH');
CREATE TYPE "AdjustmentTargetType" AS ENUM ('PRODUCT','VARIANT','CATEGORY','ENTIRE_ORDER');
CREATE TYPE "AdjustmentStacking" AS ENUM ('STACKABLE','EXCLUSIVE');
CREATE TYPE "OrderAdjustmentStatus" AS ENUM ('APPLIED','REVOKED');
CREATE TABLE "AdjustmentDefinition" ("id" TEXT PRIMARY KEY,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT,"active" BOOLEAN NOT NULL DEFAULT true,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "AdjustmentVersion" ("id" TEXT PRIMARY KEY,"definitionId" TEXT NOT NULL,"version" INTEGER NOT NULL,"kind" "AdjustmentKind" NOT NULL,"mechanic" "AdjustmentMechanic" NOT NULL,"scope" "AdjustmentScope" NOT NULL,"branchId" TEXT,"targetType" "AdjustmentTargetType" NOT NULL,"targetId" TEXT,"percentage" DECIMAL(7,4),"amount" DECIMAL(18,2),"bundleQuantity" DECIMAL(18,6),"priority" INTEGER NOT NULL DEFAULT 0,"stacking" "AdjustmentStacking" NOT NULL DEFAULT 'EXCLUSIVE',"excludedProductIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],"excludedCategoryIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],"requiresBeneficiary" BOOLEAN NOT NULL DEFAULT false,"requiresAuthorization" BOOLEAN NOT NULL DEFAULT false,"maxAmount" DECIMAL(18,2),"validFrom" TIMESTAMP(3) NOT NULL,"validTo" TIMESTAMP(3),"weekdays" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],"startMinute" INTEGER,"endMinute" INTEGER,"timezone" TEXT NOT NULL DEFAULT 'America/Mexico_City',"createdById" TEXT NOT NULL,"operationId" UUID NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT "AdjustmentVersion_version_positive" CHECK ("version">0),CONSTRAINT "AdjustmentVersion_validity" CHECK ("validTo" IS NULL OR "validTo">"validFrom"),CONSTRAINT "AdjustmentVersion_percentage" CHECK ("percentage" IS NULL OR ("percentage">0 AND "percentage"<=100)),CONSTRAINT "AdjustmentVersion_amount" CHECK ("amount" IS NULL OR "amount">=0),CONSTRAINT "AdjustmentVersion_bundle" CHECK ("bundleQuantity" IS NULL OR "bundleQuantity">0),CONSTRAINT "AdjustmentVersion_max" CHECK ("maxAmount" IS NULL OR "maxAmount">=0),CONSTRAINT "AdjustmentVersion_minutes" CHECK (("startMinute" IS NULL AND "endMinute" IS NULL) OR ("startMinute">=0 AND "startMinute"<1440 AND "endMinute">0 AND "endMinute"<=1440 AND "endMinute">"startMinute")),CONSTRAINT "AdjustmentVersion_scope" CHECK (("scope"='GLOBAL' AND "branchId" IS NULL) OR ("scope"='BRANCH' AND "branchId" IS NOT NULL)),CONSTRAINT "AdjustmentVersion_target" CHECK (("targetType"='ENTIRE_ORDER' AND "targetId" IS NULL) OR ("targetType"<>'ENTIRE_ORDER' AND "targetId" IS NOT NULL)),CONSTRAINT "AdjustmentVersion_mechanic" CHECK (("mechanic"='PERCENT_OFF' AND "percentage" IS NOT NULL AND "amount" IS NULL AND "bundleQuantity" IS NULL) OR ("mechanic"='FIXED_AMOUNT_OFF' AND "amount" IS NOT NULL AND "percentage" IS NULL AND "bundleQuantity" IS NULL) OR ("mechanic"='FIXED_BUNDLE_PRICE' AND "amount" IS NOT NULL AND "bundleQuantity" IS NOT NULL AND "percentage" IS NULL)));
CREATE TABLE "OrderAdjustment" ("id" TEXT PRIMARY KEY,"orderId" TEXT NOT NULL,"orderLineId" TEXT,"ruleVersionId" TEXT NOT NULL,"kind" "AdjustmentKind" NOT NULL,"amount" DECIMAL(18,2) NOT NULL,"percentage" DECIMAL(7,4),"reason" TEXT,"automatic" BOOLEAN NOT NULL DEFAULT false,"beneficiaryId" TEXT,"authorizedById" TEXT,"status" "OrderAdjustmentStatus" NOT NULL DEFAULT 'APPLIED',"operationId" UUID NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"revokedAt" TIMESTAMP(3),"revokedById" TEXT,CONSTRAINT "OrderAdjustment_amount_nonnegative" CHECK ("amount">=0));
CREATE TABLE "SaleAdjustment" ("id" TEXT PRIMARY KEY,"saleId" TEXT NOT NULL,"saleLineId" TEXT,"orderAdjustmentId" TEXT NOT NULL,"ruleVersionId" TEXT NOT NULL,"kind" "AdjustmentKind" NOT NULL,"ruleCodeSnapshot" TEXT NOT NULL,"ruleNameSnapshot" TEXT NOT NULL,"mechanic" "AdjustmentMechanic" NOT NULL,"amount" DECIMAL(18,2) NOT NULL,"percentage" DECIMAL(7,4),"reason" TEXT,"beneficiaryId" TEXT,"authorizedById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "SaleAdjustment_amount_nonnegative" CHECK ("amount">=0));
CREATE UNIQUE INDEX "AdjustmentDefinition_code_key" ON "AdjustmentDefinition"("code");CREATE INDEX "AdjustmentDefinition_active_name_idx" ON "AdjustmentDefinition"("active","name");CREATE UNIQUE INDEX "AdjustmentVersion_operationId_key" ON "AdjustmentVersion"("operationId");CREATE UNIQUE INDEX "AdjustmentVersion_definitionId_version_key" ON "AdjustmentVersion"("definitionId","version");CREATE INDEX "AdjustmentVersion_kind_scope_branchId_validFrom_validTo_pri_idx" ON "AdjustmentVersion"("kind","scope","branchId","validFrom","validTo","priority");CREATE INDEX "AdjustmentVersion_targetType_targetId_idx" ON "AdjustmentVersion"("targetType","targetId");CREATE INDEX "OrderAdjustment_orderId_status_kind_idx" ON "OrderAdjustment"("orderId","status","kind");CREATE INDEX "OrderAdjustment_orderLineId_status_idx" ON "OrderAdjustment"("orderLineId","status");CREATE INDEX "OrderAdjustment_operationId_idx" ON "OrderAdjustment"("operationId");CREATE UNIQUE INDEX "SaleAdjustment_saleId_orderAdjustmentId_key" ON "SaleAdjustment"("saleId","orderAdjustmentId");CREATE INDEX "SaleAdjustment_saleId_kind_idx" ON "SaleAdjustment"("saleId","kind");CREATE INDEX "SaleAdjustment_saleLineId_idx" ON "SaleAdjustment"("saleLineId");CREATE INDEX "SaleAdjustment_ruleVersionId_idx" ON "SaleAdjustment"("ruleVersionId");
ALTER TABLE "AdjustmentDefinition" ADD FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "AdjustmentVersion" ADD FOREIGN KEY ("definitionId") REFERENCES "AdjustmentDefinition"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "AdjustmentVersion" ADD FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "AdjustmentVersion" ADD FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "OrderAdjustment" ADD FOREIGN KEY ("orderId") REFERENCES "Pos2Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "OrderAdjustment" ADD FOREIGN KEY ("ruleVersionId") REFERENCES "AdjustmentVersion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "OrderAdjustment" ADD FOREIGN KEY ("beneficiaryId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "OrderAdjustment" ADD FOREIGN KEY ("authorizedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "SaleAdjustment" ADD FOREIGN KEY ("saleId") REFERENCES "Pos2Sale"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "SaleAdjustment" ADD FOREIGN KEY ("saleLineId") REFERENCES "Pos2SaleLine"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "SaleAdjustment" ADD FOREIGN KEY ("ruleVersionId") REFERENCES "AdjustmentVersion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE FUNCTION pos2_adjustment_version_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'PUBLISHED_ADJUSTMENT_VERSION_IS_IMMUTABLE' USING ERRCODE='55000'; END $$;CREATE TRIGGER "AdjustmentVersion_immutable" BEFORE UPDATE OR DELETE ON "AdjustmentVersion" FOR EACH ROW EXECUTE FUNCTION pos2_adjustment_version_immutable();CREATE TRIGGER "SaleAdjustment_immutable" BEFORE UPDATE OR DELETE ON "SaleAdjustment" FOR EACH ROW EXECUTE FUNCTION pos2_adjustment_version_immutable();
CREATE FUNCTION pos2_order_adjustment_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP='DELETE' THEN RAISE EXCEPTION 'ORDER_ADJUSTMENT_CANNOT_BE_DELETED' USING ERRCODE='55000'; END IF;IF OLD."status"='APPLIED' AND NEW."status"='REVOKED' AND (to_jsonb(NEW)-ARRAY['status','revokedAt','revokedById'])=(to_jsonb(OLD)-ARRAY['status','revokedAt','revokedById']) THEN RETURN NEW;END IF;RAISE EXCEPTION 'INVALID_ORDER_ADJUSTMENT_MUTATION' USING ERRCODE='55000';END $$;CREATE TRIGGER "OrderAdjustment_guard" BEFORE UPDATE OR DELETE ON "OrderAdjustment" FOR EACH ROW EXECUTE FUNCTION pos2_order_adjustment_guard();
INSERT INTO "Capability" ("id","key","description","active","createdAt","updatedAt") VALUES ('cap-pos-discount-employee-apply','pos.discount.employee.apply','Aplicar descuento de empleado V2',true,NOW(),NOW()),('cap-pos-discount-manual-apply','pos.discount.manual.apply','Aplicar descuento manual V2',true,NOW(),NOW()),('cap-pos-promotion-manage','pos.promotion.manage','Administrar promociones V2',true,NOW(),NOW()),('cap-pos-discount-manage','pos.discount.manage','Administrar políticas de descuento V2',true,NOW(),NOW()),('cap-pos-courtesy-manage','pos.courtesy.manage','Administrar políticas de cortesía V2',true,NOW(),NOW());
INSERT INTO "CapabilityGrant" ("id","capabilityId","role","scope","validFrom","createdAt") SELECT 'grant-admin-'||replace("key",'.','-'),"id",'ADMIN','GLOBAL',NOW(),NOW() FROM "Capability" WHERE "key" IN ('pos.discount.employee.apply','pos.discount.manual.apply','pos.promotion.manage','pos.discount.manage','pos.courtesy.manage');
CREATE TABLE "AdjustmentVersionTermination" ("id" TEXT PRIMARY KEY,"versionId" TEXT NOT NULL,"effectiveAt" TIMESTAMP(3) NOT NULL,"reason" TEXT NOT NULL,"actorId" TEXT NOT NULL,"operationId" UUID NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AdjustmentVersionTermination_reason" CHECK(length(btrim("reason"))>=3));
CREATE UNIQUE INDEX "AdjustmentVersionTermination_versionId_key" ON "AdjustmentVersionTermination"("versionId");CREATE UNIQUE INDEX "AdjustmentVersionTermination_operationId_key" ON "AdjustmentVersionTermination"("operationId");CREATE INDEX "AdjustmentVersionTermination_effectiveAt_idx" ON "AdjustmentVersionTermination"("effectiveAt");ALTER TABLE "AdjustmentVersionTermination" ADD FOREIGN KEY ("versionId") REFERENCES "AdjustmentVersion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;CREATE TRIGGER "AdjustmentVersionTermination_immutable" BEFORE UPDATE OR DELETE ON "AdjustmentVersionTermination" FOR EACH ROW EXECUTE FUNCTION pos2_adjustment_version_immutable();
