"use server";
import { revalidatePath } from "next/cache";
import { requireAdminAction } from "@/lib/auth";
import { addOrderLine, beginPayment, createOrder, expireOrder, removeOrderLine, repriceOrder, resumeOrder, updateOrderLineQuantity, voidOrder } from "@/lib/pos2/orders/manageOrders";
async function actor() { const user = await requireAdminAction(); return { id: user.id, role: user.role, branchIds: null } as const; }
const refresh = () => revalidatePath("/administration/pos2/orders");
export async function createOrderAction(form: FormData) { await createOrder({ actor: await actor(), operationId: String(form.get("operationId")), branchId: String(form.get("branchId")), registerId: String(form.get("registerId")), terminalId: String(form.get("terminalId")), cashSessionId: String(form.get("cashSessionId")) }); refresh(); }
export async function addLineAction(form: FormData) { const [kind, id] = String(form.get("target")).split(":", 2); await addOrderLine({ ...(kind === "VARIANT" ? { variantId: id } : { productId: id }), actor: await actor(), operationId: String(form.get("operationId")), orderId: String(form.get("orderId")), quantity: String(form.get("quantity")), expectedOrderVersion: Number(form.get("version")) }); refresh(); }
export async function updateLineAction(form: FormData) { await updateOrderLineQuantity({ actor: await actor(), operationId: String(form.get("operationId")), orderId: String(form.get("orderId")), lineId: String(form.get("lineId")), quantity: String(form.get("quantity")), expectedOrderVersion: Number(form.get("version")) }); refresh(); }
export async function removeLineAction(form: FormData) { await removeOrderLine({ actor: await actor(), operationId: String(form.get("operationId")), orderId: String(form.get("orderId")), lineId: String(form.get("lineId")), expectedOrderVersion: Number(form.get("version")) }); refresh(); }
export async function transitionOrderAction(form: FormData) { const common = { actor: await actor(), operationId: String(form.get("operationId")), orderId: String(form.get("orderId")), expectedOrderVersion: Number(form.get("version")) }; const action = String(form.get("intent")); if (action === "REPRICE") await repriceOrder(common); else if (action === "BEGIN") await beginPayment(common); else if (action === "RESUME") await resumeOrder(common); else if (action === "VOID") await voidOrder({ ...common, reason: String(form.get("reason") || "Anulada desde administración") }); else if (action === "EXPIRE") await expireOrder(common); refresh(); }
