import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { generateOperationId } from "@/lib/pos2/operationId";
import { addLineAction, createOrderAction, removeLineAction, transitionOrderAction, updateLineAction } from "./actions";
const field = "rounded border border-outline-variant bg-background px-2 py-1";

export default async function OrdersAdministrationPage() {
  await requireAdmin();
  const [sessions, terminals, products, orders] = await Promise.all([
    prisma.cashSession.findMany({ where: { status: "OPEN" }, include: { branch: true, register: true }, orderBy: { openedAt: "desc" } }),
    prisma.terminal.findMany({ where: { status: "ACTIVE" }, orderBy: { name: "asc" } }),
    prisma.posProduct.findMany({ where: { active: true, sellable: true, archivedAt: null }, include: { variants: { where: { active: true } } }, orderBy: { name: "asc" } }),
    prisma.pos2Order.findMany({ where: { status: { in: ["OPEN", "PAYMENT_PENDING"] } }, include: { lines: { orderBy: { position: "asc" } }, branch: true, register: true }, orderBy: { updatedAt: "desc" } }),
  ]);
  return <main className="mx-auto max-w-7xl space-y-6 p-6"><header><h1 className="text-2xl font-bold">Orders V2 — validación</h1><p className="text-sm text-on-surface-variant">Carritos pre-venta: no crean Sale, Payment, movimientos de caja ni consumo de inventario.</p></header>
    <form action={createOrderAction} className="flex flex-wrap gap-2 rounded-xl border p-4"><input type="hidden" name="operationId" value={generateOperationId()}/><select className={field} name="cashSessionId">{sessions.map((s) => <option key={s.id} value={s.id}>{s.branch.name} · {s.register.name}</option>)}</select><select className={field} name="branchId">{sessions.map((s) => <option key={s.id} value={s.branchId}>{s.branch.name}</option>)}</select><select className={field} name="registerId">{sessions.map((s) => <option key={s.id} value={s.registerId}>{s.register.name}</option>)}</select><select className={field} name="terminalId">{terminals.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select><button className="rounded bg-primary px-3 py-2 text-on-primary">Crear Order</button></form>
    {orders.map((order) => <section key={order.id} className="space-y-3 rounded-xl border p-4"><header className="flex flex-wrap justify-between"><div><h2 className="font-semibold">{order.orderNumber}</h2><p className="text-sm">{order.branch.name} · {order.register.name} · {order.status} · v{order.version}</p></div><strong>${order.total.toFixed(2)} MXN</strong></header>
      {order.status === "OPEN" && <form action={addLineAction} className="flex flex-wrap gap-2"><input type="hidden" name="operationId" value={generateOperationId()}/><input type="hidden" name="orderId" value={order.id}/><input type="hidden" name="version" value={order.version}/><select className={field} name="target">{products.flatMap((p) => [<option key={`PRODUCT:${p.id}`} value={`PRODUCT:${p.id}`}>{p.name} (producto)</option>, ...p.variants.map((v) => <option key={`VARIANT:${v.id}`} value={`VARIANT:${v.id}`}>{p.name} · {v.name}</option>)])}</select><input className={field} name="quantity" type="number" min="0.000001" step="0.000001" defaultValue="1"/><button className="underline">Agregar</button></form>}
      <div className="space-y-1">{order.lines.map((line) => <div key={line.id} className="flex flex-wrap items-center justify-between gap-2 rounded bg-surface-container p-2 text-sm"><span>{line.displayName} · ${line.unitPrice.toFixed(2)} · {line.priceVersionId}</span>{order.status === "OPEN" && <><form action={updateLineAction} className="flex gap-1"><input type="hidden" name="operationId" value={generateOperationId()}/><input type="hidden" name="orderId" value={order.id}/><input type="hidden" name="lineId" value={line.id}/><input type="hidden" name="version" value={order.version}/><input className={field} name="quantity" type="number" step="0.000001" defaultValue={line.quantity.toString()}/><button className="underline">Cantidad</button></form><form action={removeLineAction}><input type="hidden" name="operationId" value={generateOperationId()}/><input type="hidden" name="orderId" value={order.id}/><input type="hidden" name="lineId" value={line.id}/><input type="hidden" name="version" value={order.version}/><button className="text-error underline">Quitar</button></form></>}</div>)}</div>
      <div className="flex flex-wrap gap-2">{[...(order.status === "OPEN" ? [["REPRICE", "Reprice"], ["BEGIN", "BeginPayment"]] : [["RESUME", "Volver a OPEN"]]), ["VOID", "Void"]].map(([intent, label]) => <form key={intent} action={transitionOrderAction}><input type="hidden" name="operationId" value={generateOperationId()}/><input type="hidden" name="orderId" value={order.id}/><input type="hidden" name="version" value={order.version}/><input type="hidden" name="intent" value={intent}/>{intent === "VOID" && <input className={field} name="reason" defaultValue="Cancelación operativa"/>}<button className="rounded border px-2 py-1">{label}</button></form>)}</div>
    </section>)}
  </main>;
}
