import assert from "node:assert/strict";
import test from "node:test";
import { prisma } from "@/lib/prisma";
import { DomainError } from "@/lib/domain/errors";
import { generateOperationId } from "@/lib/pos2/operationId";
import { addOrderLine, beginPayment, createOrder, expireOrder, repriceOrder, resumeOrder, updateOrderLineQuantity, voidOrder } from "@/lib/pos2/orders/manageOrders";
import { getOpenOrders } from "@/lib/pos2/orders/queries";
import { createPriceVersion, endPriceVersion } from "@/lib/pos2/pricing/managePrices";
import { closeCashSession } from "@/lib/pos2/cash/closeCashSession";

const enabled = Boolean(process.env.PHASE3E_TEST_DATABASE_URL);
test("POS 2.0 phase 3E PostgreSQL contract", { skip: !enabled, timeout: 120_000 }, async (t) => {
  const p = "p3e"; const adminId = `${p}-admin`; const branchA = `${p}-a`; const branchB = `${p}-b`; const registerA = `${p}-reg-a`; const registerB = `${p}-reg-b`; const terminalA = `${p}-term-a`; const terminalB = `${p}-term-b`; const sessionA = `${p}-session-a`; const sessionB = `${p}-session-b`; const productId = `${p}-product`; const variantId = `${p}-variant`;
  const admin = { id: adminId, role: "ADMIN" as const, branchIds: null };
  await prisma.user.create({ data: { id: adminId, name: "Order Admin", username: adminId, password: "test", role: "ADMIN" } });
  await prisma.branch.createMany({ data: [{ id: branchA, name: "Orders A", code: "O3EA" }, { id: branchB, name: "Orders B", code: "O3EB" }] });
  await prisma.register.createMany({ data: [{ id: registerA, branchId: branchA, code: "RA", name: "Register A", createdById: adminId }, { id: registerB, branchId: branchB, code: "RB", name: "Register B", createdById: adminId }] });
  await prisma.terminal.createMany({ data: [{ id: terminalA, branchId: branchA, name: "Terminal A", status: "ACTIVE", credentialHash: "test-hash", createdById: adminId }, { id: terminalB, branchId: branchB, name: "Terminal B", status: "ACTIVE", credentialHash: "test-hash", createdById: adminId }] });
  await prisma.cashSession.createMany({ data: [{ id: sessionA, branchId: branchA, registerId: registerA, openingTerminalId: terminalA, openedById: adminId, status: "OPEN" }, { id: sessionB, branchId: branchB, registerId: registerB, openingTerminalId: terminalB, openedById: adminId, status: "OPEN" }] });
  await prisma.posCategory.create({ data: { id: `${p}-category`, name: "Orders" } }); await prisma.posProduct.create({ data: { id: productId, categoryId: `${p}-category`, name: "Cantarito", active: true, sellable: true, baseUnit: "UNIT" } }); await prisma.posProductVariant.create({ data: { id: variantId, productId, name: "Grande", price: 99, active: true, baseUnit: "UNIT" } });
  const price = await createPriceVersion({ operationId: generateOperationId(), actor: admin, variantId, scope: "GLOBAL", amount: "99", validFrom: new Date("2026-01-01Z") });
  const newOrder = () => createOrder({ operationId: generateOperationId(), actor: admin, branchId: branchA, registerId: registerA, terminalId: terminalA, cashSessionId: sessionA });
  let orderId = "";

  await t.test("CreateOrder is idempotent and validates the operational context", async () => {
    const operationId = generateOperationId(); const created = await createOrder({ operationId, actor: admin, branchId: branchA, registerId: registerA, terminalId: terminalA, cashSessionId: sessionA }); orderId = String(created.result.id);
    assert.equal((await createOrder({ operationId, actor: admin, branchId: branchA, registerId: registerA, terminalId: terminalA, cashSessionId: sessionA })).replayed, true);
    assert.match(String(created.result.orderNumber), /^O3EA-\d{8}-\d{6}$/); assert.equal(await prisma.posSale.count(), 0); assert.equal(await prisma.cashMovement.count(), 0);
  });
  await t.test("AddOrderLine snapshots PriceVersion and combines exact duplicate target", async () => {
    const first = await addOrderLine({ operationId: generateOperationId(), actor: admin, orderId, variantId, quantity: "1", expectedOrderVersion: 1 });
    const second = await addOrderLine({ operationId: generateOperationId(), actor: admin, orderId, variantId, quantity: "2", expectedOrderVersion: Number(first.result.version) });
    const order = await prisma.pos2Order.findUniqueOrThrow({ where: { id: orderId }, include: { lines: true } }); assert.equal(order.lines.length, 1); assert.equal(order.lines[0].quantity.toString(), "3"); assert.equal(order.lines[0].priceVersionId, price.result.id); assert.equal(order.total.toFixed(2), "297.00"); assert.equal(second.result.total, "297.00");
  });
  await t.test("same expectedVersion concurrent edits produce one winner", async () => {
    const order = await prisma.pos2Order.findUniqueOrThrow({ where: { id: orderId }, include: { lines: true } }); const lineId = order.lines[0].id;
    const edit = (quantity: string) => updateOrderLineQuantity({ operationId: generateOperationId(), actor: admin, orderId, lineId, quantity, expectedOrderVersion: order.version }); const results = await Promise.allSettled([edit("4"), edit("5")]); assert.equal(results.filter((r) => r.status === "fulfilled").length, 1); const rejected = results.find((r): r is PromiseRejectedResult => r.status === "rejected"); assert.ok(rejected?.reason instanceof DomainError); assert.equal(rejected.reason.code, "ORDER_VERSION_CONFLICT");
  });
  await t.test("concurrent duplicate adds remain consistent under the Order lock", async () => {
    const created = await newOrder(); const id = String(created.result.id); const add = () => addOrderLine({ operationId: generateOperationId(), actor: admin, orderId: id, variantId, quantity: "1", expectedOrderVersion: 1 }); const results = await Promise.allSettled([add(), add()]); assert.equal(results.filter((r) => r.status === "fulfilled").length, 1); assert.equal((await prisma.pos2OrderLine.findMany({ where: { orderId: id } })).length, 1);
  });
  await t.test("BeginPayment freezes edits, Resume reopens, and no financial rows appear", async () => {
    const before = await prisma.pos2Order.findUniqueOrThrow({ where: { id: orderId }, include: { lines: true } }); const frozen = await beginPayment({ operationId: generateOperationId(), actor: admin, orderId, expectedOrderVersion: before.version }); await assert.rejects(updateOrderLineQuantity({ operationId: generateOperationId(), actor: admin, orderId, lineId: before.lines[0].id, quantity: "2", expectedOrderVersion: Number(frozen.result.version) }), (error: unknown) => error instanceof DomainError && error.code === "ORDER_PAYMENT_PENDING"); const resumed = await resumeOrder({ operationId: generateOperationId(), actor: admin, orderId, expectedOrderVersion: Number(frozen.result.version) }); assert.equal(resumed.result.status, "OPEN"); assert.equal(await prisma.posSale.count(), 0); assert.equal(await prisma.cashMovement.count(), 0);
  });
  await t.test("BeginPayment racing an edit cannot leave a partially frozen Order", async () => {
    const created = await newOrder(); const id = String(created.result.id); const added = await addOrderLine({ operationId: generateOperationId(), actor: admin, orderId: id, variantId, quantity: "1", expectedOrderVersion: 1 }); const order = await prisma.pos2Order.findUniqueOrThrow({ where: { id }, include: { lines: true } });
    const results = await Promise.allSettled([beginPayment({ operationId: generateOperationId(), actor: admin, orderId: id, expectedOrderVersion: Number(added.result.version) }), updateOrderLineQuantity({ operationId: generateOperationId(), actor: admin, orderId: id, lineId: order.lines[0].id, quantity: "2", expectedOrderVersion: Number(added.result.version) })]); assert.equal(results.filter((r) => r.status === "fulfilled").length, 1); const final = await prisma.pos2Order.findUniqueOrThrow({ where: { id }, include: { lines: true } }); assert.ok(final.status === "PAYMENT_PENDING" && final.lines[0].quantity.equals(1) || final.status === "OPEN" && final.lines[0].quantity.equals(2));
  });
  await t.test("Void vs BeginPayment concurrent transition has exactly one winner", async () => {
    const created = await newOrder(); const id = String(created.result.id); const added = await addOrderLine({ operationId: generateOperationId(), actor: admin, orderId: id, variantId, quantity: "1", expectedOrderVersion: 1 }); const version = Number(added.result.version); const results = await Promise.allSettled([beginPayment({ operationId: generateOperationId(), actor: admin, orderId: id, expectedOrderVersion: version }), voidOrder({ operationId: generateOperationId(), actor: admin, orderId: id, expectedOrderVersion: version, reason: "Concurrent void" })]); assert.equal(results.filter((r) => r.status === "fulfilled").length, 1); assert.ok(["PAYMENT_PENDING", "VOIDED"].includes((await prisma.pos2Order.findUniqueOrThrow({ where: { id } })).status));
  });
  await t.test("Void and Expire preserve historical rows", async () => {
    const created = await createOrder({ operationId: generateOperationId(), actor: admin, branchId: branchA, registerId: registerA, terminalId: terminalA, cashSessionId: sessionA, expiresAt: new Date(Date.now() - 1000) }); const id = String(created.result.id); const added = await addOrderLine({ operationId: generateOperationId(), actor: admin, orderId: id, variantId, quantity: "1", expectedOrderVersion: 1 }); const expired = await expireOrder({ operationId: generateOperationId(), actor: admin, orderId: id, expectedOrderVersion: Number(added.result.version) }); assert.equal(expired.result.status, "EXPIRED"); assert.equal(await prisma.pos2OrderLine.count({ where: { orderId: id } }), 1);
    const voidCreated = await newOrder(); const voidId = String(voidCreated.result.id); const voidAdded = await addOrderLine({ operationId: generateOperationId(), actor: admin, orderId: voidId, variantId, quantity: "1", expectedOrderVersion: 1 }); const voided = await voidOrder({ operationId: generateOperationId(), actor: admin, orderId: voidId, expectedOrderVersion: Number(voidAdded.result.version), reason: "Cliente canceló" }); assert.equal(voided.result.status, "VOIDED"); assert.equal(await prisma.pos2OrderLine.count({ where: { orderId: voidId } }), 1);
  });
  await t.test("PAYMENT_PENDING blocks CashSession close cleanly", async () => {
    const created = await newOrder(); const id = String(created.result.id); const added = await addOrderLine({ operationId: generateOperationId(), actor: admin, orderId: id, variantId, quantity: "1", expectedOrderVersion: 1 }); await beginPayment({ operationId: generateOperationId(), actor: admin, orderId: id, expectedOrderVersion: Number(added.result.version) }); const pending = await prisma.pos2Order.findFirst({ where: { id, status: "PAYMENT_PENDING" } }); assert.ok(pending); await assert.rejects(closeCashSession({ operationId: generateOperationId(), actor: admin, cashSessionId: sessionA, terminalId: terminalA, declaredCash: "0" }), (error: unknown) => error instanceof DomainError && error.code === "ORDER_PAYMENT_PENDING"); assert.equal((await prisma.cashSession.findUniqueOrThrow({ where: { id: sessionA } })).status, "OPEN");
  });
  await t.test("branch-scoped actor cannot recover or mutate another branch", async () => {
    const managerId = `${p}-manager`; await prisma.user.create({ data: { id: managerId, name: "Manager", username: managerId, password: "test", role: "GERENTE" } }); for (const capabilityId of ["cap-pos-order-create", "cap-pos-order-edit", "cap-pos-order-recover"]) await prisma.capabilityGrant.create({ data: { capabilityId, userId: managerId, scope: "BRANCH", branchId: branchA } }); const manager = { id: managerId, role: "GERENTE" as const, branchIds: [branchA] }; assert.ok((await getOpenOrders({ actor: manager, branchId: branchA })).length > 0); await assert.rejects(getOpenOrders({ actor: manager, branchId: branchB }), (error: unknown) => error instanceof DomainError && error.code === "PERMISSION_DENIED"); const orderB = await createOrder({ operationId: generateOperationId(), actor: admin, branchId: branchB, registerId: registerB, terminalId: terminalB, cashSessionId: sessionB }); await assert.rejects(addOrderLine({ operationId: generateOperationId(), actor: manager, orderId: String(orderB.result.id), variantId, quantity: "1", expectedOrderVersion: 1 }), (error: unknown) => error instanceof DomainError && error.code === "PERMISSION_DENIED");
  });
  await t.test("Reprice detects a newly effective version and updates OPEN snapshot", async () => {
    const original = await prisma.priceVersion.findUniqueOrThrow({ where: { id: String(price.result.id) } }); const cutover = new Date(); await endPriceVersion({ operationId: generateOperationId(), actor: admin, priceVersionId: original.id, effectiveAt: cutover, reason: "Nueva lista" }); await createPriceVersion({ operationId: generateOperationId(), actor: admin, variantId, scope: "GLOBAL", amount: "105", validFrom: cutover }); const current = await prisma.pos2Order.findUniqueOrThrow({ where: { id: orderId } }); const repriced = await repriceOrder({ operationId: generateOperationId(), actor: admin, orderId, expectedOrderVersion: current.version }); assert.ok((repriced.result.findings as unknown as Array<{ status: string }>).some((finding) => finding.status === "PRICE_CHANGED")); assert.equal((await prisma.pos2OrderLine.findFirstOrThrow({ where: { orderId } })).unitPrice.toFixed(2), "105.00");
  });
  await t.test("Reprice racing a branch publication observes one coherent timeline", async () => {
    const created = await newOrder(); const id = String(created.result.id); const added = await addOrderLine({ operationId: generateOperationId(), actor: admin, orderId: id, variantId, quantity: "1", expectedOrderVersion: 1 }); const publicationAt = new Date();
    await Promise.allSettled([repriceOrder({ operationId: generateOperationId(), actor: admin, orderId: id, expectedOrderVersion: Number(added.result.version) }), createPriceVersion({ operationId: generateOperationId(), actor: admin, variantId, scope: "BRANCH", branchId: branchA, amount: "103", validFrom: publicationAt })]); const after = await prisma.pos2Order.findUniqueOrThrow({ where: { id } }); await repriceOrder({ operationId: generateOperationId(), actor: admin, orderId: id, expectedOrderVersion: after.version }); assert.equal((await prisma.pos2OrderLine.findFirstOrThrow({ where: { orderId: id } })).unitPrice.toFixed(2), "103.00");
  });
  await t.test("100-line load and batch reprice avoid critical N+1", async () => {
    const created = await newOrder(); const id = String(created.result.id); const variants = Array.from({ length: 100 }, (_, index) => ({ id: `${p}-perf-v-${index}`, productId, name: `Perf ${index}`, price: 10, active: true, baseUnit: "UNIT" as const })); await prisma.posProductVariant.createMany({ data: variants }); await prisma.priceVersion.createMany({ data: variants.map((v, index) => ({ id: `${p}-perf-price-${index}`, targetType: "VARIANT", targetKey: `VARIANT:${v.id}`, variantId: v.id, scope: "GLOBAL", branchKey: "GLOBAL", amount: "10", validFrom: new Date("2026-01-01Z"), createdById: adminId, operationId: generateOperationId() })) }); await prisma.pos2OrderLine.createMany({ data: variants.map((v, index) => ({ id: `${p}-perf-line-${index}`, orderId: id, variantId: v.id, targetKey: `VARIANT:${v.id}`, displayName: v.name, catalogVersion: 1, quantity: "1", unit: "UNIT", unitPrice: "10", lineSubtotal: "10", lineTotal: "10", priceVersionId: `${p}-perf-price-${index}`, pricingExplanation: "GLOBAL_BASE_PRICE", position: index })) }); await prisma.pos2Order.update({ where: { id }, data: { subtotal: "1000", total: "1000", version: { increment: 1 } } }); const order = await prisma.pos2Order.findUniqueOrThrow({ where: { id } }); const started = performance.now(); await repriceOrder({ operationId: generateOperationId(), actor: admin, orderId: id, expectedOrderVersion: order.version }); const elapsed = performance.now() - started; assert.ok(elapsed < 5000); t.diagnostic(`DEV Order load/reprice: ${elapsed.toFixed(1)}ms for 100 lines`);
  });
  assert.ok(await prisma.auditEvent.count({ where: { action: { in: ["ORDER_CREATED", "ORDER_LINE_ADDED", "ORDER_PAYMENT_STARTED", "ORDER_PAYMENT_ABORTED"] } } })); await prisma.$disconnect();
});
