import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { DomainError } from "@/lib/domain/errors";
import { generateOperationId } from "@/lib/pos2/operationId";
import { adjustInventory, countInventory, receiveInventory } from "@/lib/pos2/inventory/commands";
import { applyInventoryMovementsBatch } from "@/lib/pos2/inventory/applyMovements";
import { transferInventory } from "@/lib/pos2/inventory/transfer";
import { getBranchInventory, getLegacyBalance, reconcileInventoryProduct } from "@/lib/pos2/inventory/queries";
import { backfillLegacyOpeningBalanceDev, compareLegacyToV2 } from "@/lib/pos2/inventory/legacyBridge";

const enabled = Boolean(process.env.PHASE3F_TEST_DATABASE_URL);
test("POS 2.0 phase 3F PostgreSQL contract", { skip: !enabled, timeout: 120_000 }, async (t) => {
  const p="p3f", adminId=`${p}-admin`, branchA=`${p}-a`, branchB=`${p}-b`; const admin={id:adminId,role:"ADMIN" as const,branchIds:null};
  await prisma.user.create({data:{id:adminId,name:"Inventory Admin",username:adminId,password:"test",role:"ADMIN"}}); await prisma.branch.createMany({data:[{id:branchA,name:"Inventory A",code:"I3FA"},{id:branchB,name:"Inventory B",code:"I3FB"}]});
  const products=Array.from({length:7},(_,i)=>({id:`${p}-item-${i}`,code:`I3F-${i}`,name:`Physical ${i}`,category:"TEST",unit:"pieza",itemType:"CONSUMABLE" as const,trackStock:true,inventoryBaseUnit:"UNIT" as const})); await prisma.inventoryProduct.createMany({data:products});
  const movement=(id:string,delta:string)=>({inventoryProductId:id,quantityDelta:delta,unit:"UNIT" as const,movementType:new Prisma.Decimal(delta).isPositive()?"ADJUSTMENT_IN" as const:"ADJUSTMENT_OUT" as const,sourceType:"MANUAL_ADJUSTMENT" as const,sourceId:generateOperationId(),reasonCode:"TEST"});

  await t.test("InventoryProduct is the only physical FK and first-balance receipts are concurrency-safe",async()=>{ const id=products[0].id; const results=await Promise.all([receiveInventory({branchId:branchA,inventoryProductId:id,quantity:"1",unit:"UNIT",reason:"Receipt A",sourceId:"receipt-a",actor:admin,operationId:generateOperationId()}),receiveInventory({branchId:branchA,inventoryProductId:id,quantity:"1",unit:"UNIT",reason:"Receipt B",sourceId:"receipt-b",actor:admin,operationId:generateOperationId()})]); assert.equal(results.length,2); assert.equal(await prisma.inventoryBalance.count({where:{branchId:branchA,inventoryProductId:id}}),1); assert.equal((await prisma.inventoryBalance.findFirstOrThrow({where:{branchId:branchA,inventoryProductId:id}})).quantity.toString(),"2"); assert.equal(await prisma.inventoryMovement.count({where:{inventoryProductId:id}}),2); });
  await t.test("stock=1 with two concurrent consumptions admits one",async()=>{const id=products[1].id;await receiveInventory({branchId:branchA,inventoryProductId:id,quantity:"1",unit:"UNIT",reason:"Opening",sourceId:"one",actor:admin,operationId:generateOperationId()});const consume=()=>adjustInventory({branchId:branchA,inventoryProductId:id,delta:"-1",unit:"UNIT",reason:"Consume test",actor:admin,operationId:generateOperationId()});const r=await Promise.allSettled([consume(),consume()]);assert.equal(r.filter(x=>x.status==="fulfilled").length,1);const rejected=r.find((x):x is PromiseRejectedResult=>x.status==="rejected");assert.ok(rejected?.reason instanceof DomainError);assert.equal(rejected.reason.code,"INSUFFICIENT_STOCK");assert.equal((await reconcileInventoryProduct(admin,branchA,id)).status,"MATCH");});
  await t.test("inverse multi-item batches finish without deadlock",async()=>{const [a,b]=[products[2].id,products[3].id];for(const id of[a,b])await receiveInventory({branchId:branchA,inventoryProductId:id,quantity:"10",unit:"UNIT",reason:"Opening",sourceId:id,actor:admin,operationId:generateOperationId()});const batch=(items:Array<[string,string]>)=>applyInventoryMovementsBatch({branchId:branchA,actor:admin,operationId:generateOperationId(),movements:items.map(([id,d])=>movement(id,d))});const r=await Promise.allSettled([batch([[a,"-1"],[b,"-1"]]),batch([[b,"-1"],[a,"-1"]])]);assert.equal(r.filter(x=>x.status==="fulfilled").length,2);assert.equal((await reconcileInventoryProduct(admin,branchA,a)).status,"MATCH");assert.equal((await reconcileInventoryProduct(admin,branchA,b)).status,"MATCH");});
  await t.test("five-item batch rolls back entirely on one insufficient item",async()=>{const ids=products.slice(0,5).map(x=>x.id);const before=await prisma.inventoryMovement.count();await assert.rejects(applyInventoryMovementsBatch({branchId:branchA,actor:admin,operationId:generateOperationId(),movements:ids.map((id,i)=>movement(id,i===4?"-999":"1"))}),(e:unknown)=>e instanceof DomainError&&e.code==="INSUFFICIENT_STOCK");assert.equal(await prisma.inventoryMovement.count(),before);});
  await t.test("idempotent adjustment creates one movement",async()=>{const id=products[4].id,op=generateOperationId();await adjustInventory({branchId:branchA,inventoryProductId:id,delta:"2",unit:"UNIT",reason:"Retry adjustment",actor:admin,operationId:op});const replay=await adjustInventory({branchId:branchA,inventoryProductId:id,delta:"2",unit:"UNIT",reason:"Retry adjustment",actor:admin,operationId:op});assert.equal(replay.replayed,true);assert.equal(await prisma.inventoryMovement.count({where:{operationId:op}}),1);});
  await t.test("transfer is atomic and remains coherent against concurrent consumption",async()=>{const id=products[5].id;await receiveInventory({branchId:branchA,inventoryProductId:id,quantity:"5",unit:"UNIT",reason:"Transfer stock",sourceId:"transfer-stock",actor:admin,operationId:generateOperationId()});const r=await Promise.allSettled([transferInventory({fromBranchId:branchA,toBranchId:branchB,inventoryProductId:id,quantity:"3",unit:"UNIT",reason:"Branch transfer",actor:admin,operationId:generateOperationId()}),adjustInventory({branchId:branchA,inventoryProductId:id,delta:"-3",unit:"UNIT",reason:"Concurrent consumption",actor:admin,operationId:generateOperationId()})]);assert.equal(r.filter(x=>x.status==="fulfilled").length,1);assert.equal((await reconcileInventoryProduct(admin,branchA,id)).status,"MATCH");assert.equal((await reconcileInventoryProduct(admin,branchB,id)).status,"MATCH");});
  await t.test("physical count stores declaration and correction movement",async()=>{const id=products[4].id;const result=await countInventory({branchId:branchA,inventoryProductId:id,declaredQuantity:"1",unit:"UNIT",notes:"Physical declaration",actor:admin,operationId:generateOperationId()});assert.equal(result.result.declared,"1.000000");assert.equal(await prisma.inventoryCountDeclaration.count({where:{inventoryProductId:id}}),1);assert.equal((await reconcileInventoryProduct(admin,branchA,id)).status,"MATCH");});
  await t.test("ledger is DB append-only",async()=>{const row=await prisma.inventoryMovement.findFirstOrThrow();await assert.rejects(prisma.inventoryMovement.update({where:{id:row.id},data:{reasonCode:"MUTATED"}}));await assert.rejects(prisma.inventoryMovement.delete({where:{id:row.id}}));});
  await t.test("branch capabilities isolate reads and writes",async()=>{const userId=`${p}-manager`;await prisma.user.create({data:{id:userId,name:"Inventory Manager",username:userId,password:"test",role:"GERENTE"}});for(const capabilityId of["cap-inventory-view","cap-inventory-receive"])await prisma.capabilityGrant.create({data:{capabilityId,userId,scope:"BRANCH",branchId:branchA}});const manager={id:userId,role:"GERENTE" as const,branchIds:[branchA]};assert.ok((await getBranchInventory(manager,branchA)).length>0);await assert.rejects(getBranchInventory(manager,branchB),(e:unknown)=>e instanceof DomainError&&e.code==="PERMISSION_DENIED");await assert.rejects(receiveInventory({branchId:branchB,inventoryProductId:products[0].id,quantity:"1",unit:"UNIT",reason:"Cross branch",sourceId:"cross",actor:manager,operationId:generateOperationId()}),(e:unknown)=>e instanceof DomainError&&e.code==="PERMISSION_DENIED");});
  await t.test("unconfigured or unit-mismatched physical items are rejected",async()=>{const id=`${p}-untracked`;await prisma.inventoryProduct.create({data:{id,code:"I3F-U",name:"Unconfigured",category:"TEST",unit:"pieza",itemType:"CONSUMABLE",trackStock:true}});await assert.rejects(receiveInventory({branchId:branchA,inventoryProductId:id,quantity:"1",unit:"UNIT",reason:"No base unit",sourceId:"u",actor:admin,operationId:generateOperationId()}),(e:unknown)=>e instanceof DomainError&&e.code==="INVENTORY_NOT_TRACKED");await assert.rejects(receiveInventory({branchId:branchA,inventoryProductId:products[0].id,quantity:"1",unit:"ML",reason:"Wrong unit",sourceId:"wrong",actor:admin,operationId:generateOperationId()}),(e:unknown)=>e instanceof DomainError&&e.code==="INVENTORY_UNIT_MISMATCH");});
  await t.test("DEV legacy opening backfill and shadow comparison use count plus later entries",async()=>{const id=products[6].id;await prisma.inventoryCount.create({data:{id:`${p}-legacy-count`,code:`${p}-legacy`,branchId:branchB,countDate:new Date("2026-01-01Z"),status:"CERRADO",items:{create:{productId:id,quantityCounted:"7"}}}});await prisma.inventoryEntry.create({data:{branchId:branchB,productId:id,type:"COMPRA",quantity:"2",entryDate:new Date("2026-02-01Z")}});assert.equal((await getLegacyBalance(branchB,id)).toString(),"9");await backfillLegacyOpeningBalanceDev({branchId:branchB,inventoryProductId:id,unit:"UNIT",actor:admin,operationId:generateOperationId(),capturedAt:new Date(),migrationVersion:"phase3f-dev"});const balance=await prisma.inventoryBalance.findUniqueOrThrow({where:{branchId_inventoryProductId:{branchId:branchB,inventoryProductId:id}}});assert.equal((await compareLegacyToV2(branchB,id,balance.quantity.toString())).status,"MATCH");});
  await t.test("5,000 balances and 50,000 movements remain queryable without N+1",async()=>{const perfProducts=Array.from({length:5000},(_,i)=>({id:`${p}-perf-${i}`,code:`I3FP-${i}`,name:`Perf ${i}`,category:"PERF",unit:"pieza",itemType:"CONSUMABLE" as const,trackStock:true,inventoryBaseUnit:"UNIT" as const}));await prisma.inventoryProduct.createMany({data:perfProducts});await prisma.inventoryBalance.createMany({data:perfProducts.map(x=>({id:randomUUID(),branchId:branchA,inventoryProductId:x.id,quantity:"10",unit:"UNIT" as const}))});for(let chunk=0;chunk<20;chunk++){const rows=[];for(let i=chunk*250;i<(chunk+1)*250;i++)for(let step=0;step<10;step++)rows.push({id:randomUUID(),branchId:branchA,inventoryProductId:perfProducts[i].id,movementType:"OPENING_BALANCE" as const,quantityDelta:"1",unit:"UNIT" as const,balanceBefore:String(step),balanceAfter:String(step+1),sourceType:"LEGACY_OPENING" as const,sourceId:"perf",actorId:adminId,operationId:generateOperationId(),reasonCode:"PERF"});await prisma.inventoryMovement.createMany({data:rows});}const started=performance.now();const balances=await prisma.inventoryBalance.findMany({where:{branchId:branchA},include:{inventoryProduct:true}});const ledger=await prisma.inventoryMovement.findMany({where:{branchId:branchA},orderBy:{createdAt:"desc"},take:100});const availability=await prisma.inventoryBalance.findMany({where:{branchId:branchA,inventoryProductId:{in:perfProducts.slice(0,100).map(x=>x.id)}}});const elapsed=performance.now()-started;assert.ok(balances.length>=5000&&ledger.length===100&&availability.length===100);assert.ok(elapsed<5000);t.diagnostic(`DEV inventory reads: ${elapsed.toFixed(1)}ms for 5,000 balances / 50,000 movements / 100-item availability`);});
  await prisma.$disconnect();
});
