import assert from "node:assert/strict";
import test from "node:test";
import { prisma } from "@/lib/prisma";
import { DomainError } from "@/lib/domain/errors";
import { generateOperationId } from "@/lib/pos2/operationId";
import { completeSale } from "@/lib/pos2/sales/completeSale";
import { createCashOut } from "@/lib/pos2/cash/createCashMovement";
import { closeCashSession } from "@/lib/pos2/cash/closeCashSession";

const enabled = Boolean(process.env.PHASE3G_TEST_DATABASE_URL);
test("POS 2.0 phase 3G PostgreSQL atomic sale contract", { skip: !enabled, timeout: 120_000 }, async (t) => {
  const p="p3g", admin={id:`${p}-admin`,role:"ADMIN" as const,branchIds:null}, branchId=`${p}-branch`, registerId=`${p}-register`, terminalId=`${p}-terminal`, sessionId=`${p}-session`, inventoryId=`${p}-inventory`, categoryId=`${p}-category`, productId=`${p}-product`, variantId=`${p}-variant`, priceId=`${p}-price`;
  await prisma.user.create({data:{id:admin.id,name:"Sales Admin",username:admin.id,password:"test",role:"ADMIN"}}); await prisma.branch.create({data:{id:branchId,name:"Sales Branch",code:"S3G"}}); await prisma.register.create({data:{id:registerId,branchId,code:"R1",name:"Register",createdById:admin.id}}); await prisma.terminal.create({data:{id:terminalId,branchId,name:"Terminal",status:"ACTIVE",credentialHash:"hash",createdById:admin.id}}); await prisma.cashSession.create({data:{id:sessionId,branchId,registerId,openingTerminalId:terminalId,openedById:admin.id,status:"OPEN"}});
  await prisma.inventoryProduct.create({data:{id:inventoryId,code:"P3G-I",name:"Ingredient",category:"TEST",unit:"ml",itemType:"CONSUMABLE",trackStock:true,inventoryBaseUnit:"ML"}}); await prisma.inventoryBalance.create({data:{branchId,inventoryProductId:inventoryId,quantity:"1000",unit:"ML"}});
  await prisma.posCategory.create({data:{id:categoryId,name:"Sales",slug:"p3g-sales",active:true,position:0}}); await prisma.posProduct.create({data:{id:productId,categoryId,name:"Drink",active:true,sellable:true,inventoryTracked:true,baseUnit:"UNIT",createdById:admin.id}}); await prisma.posProductVariant.create({data:{id:variantId,productId,name:"Regular",baseUnit:"UNIT",price:100,active:true,ingredients:{create:{inventoryProductId:inventoryId,quantity:"10",unit:"ML",unitStatus:"RESOLVED"}}}}); await prisma.priceVersion.create({data:{id:priceId,targetType:"VARIANT",targetKey:`VARIANT:${variantId}`,variantId,scope:"GLOBAL",branchKey:"GLOBAL",amount:"100",createdById:admin.id,operationId:generateOperationId(),validFrom:new Date("2026-01-01Z")}});
  let orderCounter=0; const makeOrder=async()=>{orderCounter++;return prisma.pos2Order.create({data:{id:`${p}-order-${orderCounter}`,orderNumber:`S3G-O${orderCounter}`,branchId,registerId,terminalId,cashSessionId:sessionId,createdById:admin.id,lastModifiedById:admin.id,status:"PAYMENT_PENDING",subtotal:"100",discountTotal:"0",total:"100",pricingTimestamp:new Date(),version:2,lines:{create:{productId:null,variantId,targetKey:`VARIANT:${variantId}`,displayName:"Drink — Regular",catalogVersion:1,quantity:"1",unit:"UNIT",unitPrice:"100",lineSubtotal:"100",discountTotal:"0",lineTotal:"100",priceVersionId:priceId,pricingExplanation:"GLOBAL_BASE_PRICE",position:0}}},include:{lines:true}})};
  const input=(order:{id:string;version:number},operationId=generateOperationId())=>({orderId:order.id,expectedOrderVersion:order.version,cashSessionId:sessionId,terminalId,actor:admin,operationId,payments:[{method:"CASH" as const,amount:"40",cashTendered:"50"},{method:"CARD" as const,amount:"60",reference:"AUTH"}]});

  await t.test("mixed completion is coherent, idempotent and rejects key reuse",async()=>{const order=await makeOrder(),op=generateOperationId();const first=await completeSale(input(order,op));const replay=await completeSale(input(order,op));assert.equal(replay.replayed,true);assert.equal(first.result.id,replay.result.id);await assert.rejects(completeSale({...input(order,op),payments:[{method:"CARD",amount:"100"}]}),(e:unknown)=>e instanceof DomainError&&e.code==="IDEMPOTENCY_KEY_REUSED");assert.equal(await prisma.pos2Sale.count({where:{orderId:order.id}}),1);assert.equal(await prisma.pos2Payment.count({where:{saleId:String(first.result.id)}}),2);assert.equal((await prisma.cashMovement.findFirstOrThrow({where:{sourceId:String(first.result.id)}})).amount.toString(),"40");assert.equal((await prisma.inventoryBalance.findUniqueOrThrow({where:{branchId_inventoryProductId:{branchId,inventoryProductId:inventoryId}}})).quantity.toString(),"990");assert.equal((await prisma.pos2Order.findUniqueOrThrow({where:{id:order.id}})).status,"FINALIZED");});
  await t.test("two concurrent completions yield exactly one Sale",async()=>{const order=await makeOrder();const r=await Promise.allSettled([completeSale(input(order)),completeSale(input(order))]);assert.equal(r.filter(x=>x.status==="fulfilled").length,1);assert.equal(await prisma.pos2Sale.count({where:{orderId:order.id}}),1);});
  await t.test("payment mismatch has no effects",async()=>{const order=await makeOrder();await assert.rejects(completeSale({...input(order),payments:[{method:"CARD",amount:"99"}]}),(e:unknown)=>e instanceof DomainError&&e.code==="PAYMENT_MISMATCH");assert.equal(await prisma.pos2Sale.count({where:{orderId:order.id}}),0);assert.equal((await prisma.pos2Order.findUniqueOrThrow({where:{id:order.id}})).status,"PAYMENT_PENDING");});
  await t.test("failure after first inventory movement rolls back every fact",async()=>{const second=await prisma.inventoryProduct.create({data:{id:`${p}-inventory-2`,code:"P3G-I2",name:"Ingredient 2",category:"TEST",unit:"ml",itemType:"CONSUMABLE",trackStock:true,inventoryBaseUnit:"ML"}});await prisma.inventoryBalance.create({data:{branchId,inventoryProductId:second.id,quantity:"1000",unit:"ML"}});await prisma.posVariantIngredient.create({data:{variantId,inventoryProductId:second.id,quantity:"5",unit:"ML",unitStatus:"RESOLVED"}});const order=await makeOrder(),before=await prisma.inventoryMovement.count();await assert.rejects(completeSale({...input(order),faultInjectionForTest:"AFTER_FIRST_INVENTORY"}));assert.equal(await prisma.pos2Sale.count({where:{orderId:order.id}}),0);assert.equal(await prisma.inventoryMovement.count(),before);assert.equal(await prisma.pos2Payment.count({where:{sale:{orderId:order.id}}}),0);assert.equal((await prisma.pos2Order.findUniqueOrThrow({where:{id:order.id}})).status,"PAYMENT_PENDING");});
  await t.test("faults after Sale, Payments and before finalize roll back all tables",async()=>{for(const faultInjectionForTest of["AFTER_SALE","AFTER_PAYMENTS","BEFORE_FINALIZE"] as const){const order=await makeOrder(),beforeInventory=await prisma.inventoryMovement.count(),beforeCash=await prisma.cashMovement.count();await assert.rejects(completeSale({...input(order),faultInjectionForTest}));assert.equal(await prisma.pos2Sale.count({where:{orderId:order.id}}),0);assert.equal(await prisma.inventoryMovement.count(),beforeInventory);assert.equal(await prisma.cashMovement.count(),beforeCash);assert.equal((await prisma.pos2Order.findUniqueOrThrow({where:{id:order.id}})).status,"PAYMENT_PENDING");}});
  await t.test("two distinct Orders competing for one recipe stock admit one",async()=>{await prisma.inventoryBalance.updateMany({where:{branchId},data:{quantity:"5"}});await prisma.inventoryBalance.update({where:{branchId_inventoryProductId:{branchId,inventoryProductId:inventoryId}},data:{quantity:"10"}});const a=await makeOrder(),b=await makeOrder();const r=await Promise.allSettled([completeSale(input(a)),completeSale(input(b))]);assert.equal(r.filter(x=>x.status==="fulfilled").length,1);assert.equal(r.filter(x=>x.status==="rejected").length,1);assert.equal(await prisma.pos2Sale.count({where:{orderId:{in:[a.id,b.id]}}}),1);await prisma.inventoryBalance.updateMany({where:{branchId},data:{quantity:"1000"}});});
  await t.test("unresolved recipe units and changed price block completion",async()=>{const ingredient=await prisma.posVariantIngredient.findFirstOrThrow({where:{variantId}});await prisma.posVariantIngredient.update({where:{id:ingredient.id},data:{unit:null,unitStatus:"UNRESOLVED"}});const unresolved=await makeOrder();await assert.rejects(completeSale(input(unresolved)),(e:unknown)=>e instanceof DomainError&&e.code==="RECIPE_UNIT_UNRESOLVED");await prisma.posVariantIngredient.update({where:{id:ingredient.id},data:{unit:"ML",unitStatus:"RESOLVED"}});const changed=await makeOrder();await prisma.$executeRaw`ALTER TABLE "PriceVersion" DISABLE TRIGGER "PriceVersion_immutable"`;await prisma.priceVersion.update({where:{id:priceId},data:{amount:"101"}});await prisma.$executeRaw`ALTER TABLE "PriceVersion" ENABLE TRIGGER "PriceVersion_immutable"`;await assert.rejects(completeSale(input(changed)),(e:unknown)=>e instanceof DomainError&&e.code==="PRICE_CHANGED");await prisma.$executeRaw`ALTER TABLE "PriceVersion" DISABLE TRIGGER "PriceVersion_immutable"`;await prisma.priceVersion.update({where:{id:priceId},data:{amount:"100"}});await prisma.$executeRaw`ALTER TABLE "PriceVersion" ENABLE TRIGGER "PriceVersion_immutable"`;});
  await t.test("100-line shared recipe completes without N+1 inventory writes",async()=>{await prisma.inventoryBalance.updateMany({where:{branchId},data:{quantity:"5000"}});orderCounter++;const order=await prisma.pos2Order.create({data:{id:`${p}-order-${orderCounter}`,orderNumber:`S3G-O${orderCounter}`,branchId,registerId,terminalId,cashSessionId:sessionId,createdById:admin.id,lastModifiedById:admin.id,status:"PAYMENT_PENDING",subtotal:"10000",discountTotal:"0",total:"10000",pricingTimestamp:new Date(),version:2,lines:{create:Array.from({length:100},(_,position)=>({variantId,targetKey:`VARIANT:${variantId}`,displayName:"Drink — Regular",catalogVersion:1,quantity:"1",unit:"UNIT" as const,unitPrice:"100",lineSubtotal:"100",discountTotal:"0",lineTotal:"100",priceVersionId:priceId,pricingExplanation:"GLOBAL_BASE_PRICE" as const,position}))}}});const started=performance.now();await completeSale({...input(order),payments:[{method:"TRANSFER",amount:"10000",reference:"PERF"}]});const elapsed=performance.now()-started;assert.equal(await prisma.inventoryMovement.count({where:{sourceId:(await prisma.pos2Sale.findUniqueOrThrow({where:{orderId:order.id}})).id}}),2);t.diagnostic(`DEV CompleteSale 100 lines / shared two-ingredient recipe: ${elapsed.toFixed(1)}ms`);});
  await t.test("CompleteSale serializes safely with CashOut and blocks Close while payment is pending",async()=>{const order=await makeOrder();const results=await Promise.allSettled([completeSale(input(order)),createCashOut({operationId:generateOperationId(),cashSessionId:sessionId,terminalId,actor:admin,amount:"1",reason:"Concurrent test"}),closeCashSession({operationId:generateOperationId(),cashSessionId:sessionId,terminalId,actor:admin,declaredCash:"0"})]);assert.equal(results[0].status,"fulfilled");assert.equal(results[1].status,"fulfilled");assert.equal(results[2].status,"rejected");assert.equal((await prisma.cashSession.findUniqueOrThrow({where:{id:sessionId}})).status,"OPEN");});
  await t.test("insufficient stock and closed cash session reject atomically",async()=>{await prisma.inventoryBalance.update({where:{branchId_inventoryProductId:{branchId,inventoryProductId:inventoryId}},data:{quantity:"0"}});const order=await makeOrder();await assert.rejects(completeSale(input(order)),(e:unknown)=>e instanceof DomainError&&e.code==="INSUFFICIENT_STOCK");assert.equal(await prisma.pos2Sale.count({where:{orderId:order.id}}),0);await prisma.cashSession.update({where:{id:sessionId},data:{status:"CLOSED",closedAt:new Date()}});const other=await makeOrder();await assert.rejects(completeSale(input(other)),(e:unknown)=>e instanceof DomainError&&e.code==="CASH_SESSION_NOT_OPEN");assert.equal(await prisma.pos2Sale.count({where:{orderId:other.id}}),0);});
  await t.test("financial facts are database immutable",async()=>{const sale=await prisma.pos2Sale.findFirstOrThrow();const payment=await prisma.pos2Payment.findFirstOrThrow({where:{saleId:sale.id}});const line=await prisma.pos2SaleLine.findFirstOrThrow({where:{saleId:sale.id}});await assert.rejects(prisma.pos2Sale.update({where:{id:sale.id},data:{total:"1"}}));await assert.rejects(prisma.pos2Payment.delete({where:{id:payment.id}}));await assert.rejects(prisma.pos2SaleLine.update({where:{id:line.id},data:{productNameSnapshot:"changed"}}));});
  await prisma.$disconnect();
});
