import Link from "next/link";
import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { generateOperationId } from "@/lib/pos2/operationId";
import { archiveProductAction, createCategoryAction, createProductAction, createVariantAction, setOverrideAction, updateCategoryAction, updateProductAction, updateVariantAction } from "./actions";

const input = "rounded border border-outline-variant bg-background px-2 py-1";

export default async function CatalogAdministrationPage() {
  await requireAdmin();
  const [categories, branches] = await Promise.all([
    prisma.posCategory.findMany({ include: { products: { include: { variants: { orderBy: { position: "asc" } }, branchOverrides: true }, orderBy: { position: "asc" } } }, orderBy: { position: "asc" } }),
    prisma.branch.findMany({ where: { active: true }, select: { id: true, name: true }, orderBy: { name: "asc" } }),
  ]);
  return <main className="mx-auto max-w-7xl space-y-8 p-6">
    <header><h1 className="text-2xl font-bold">Catálogo empresarial POS 2.0</h1><p className="text-sm text-on-surface-variant">Fuente global con disponibilidad por sucursal. El precio mostrado sigue siendo legacy.</p><Link className="text-sm font-semibold text-primary underline" href="/administration/pos2/catalog/preview">Abrir preview por sucursal</Link></header>
    <section className="grid gap-4 lg:grid-cols-3">
      <form action={createCategoryAction} className="space-y-2 rounded-xl border p-4"><h2 className="font-semibold">Nueva categoría</h2><input type="hidden" name="operationId" value={generateOperationId()}/><input className={input} name="name" required placeholder="Bebidas"/><input className={input} name="slug" placeholder="bebidas"/><input className={input} name="description" placeholder="Descripción"/><input className={input} name="icon" placeholder="Emoji o URL de imagen"/><input className={input} name="imageAlt" placeholder="Texto alternativo"/><button className="rounded bg-primary px-3 py-2 text-on-primary">Crear categoría</button></form>
      <form action={createProductAction} className="space-y-2 rounded-xl border p-4"><h2 className="font-semibold">Nuevo producto</h2><input type="hidden" name="operationId" value={generateOperationId()}/><select className={input} name="categoryId" required>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><input className={input} name="name" required placeholder="Cantarito"/><input className={input} name="sku" placeholder="SKU empresarial"/><input className={input} name="internalCode" placeholder="Código interno"/><input className={input} name="barcode" placeholder="Código de barras opcional"/><input className={input} name="description" placeholder="Descripción"/><input className={input} name="icon" placeholder="Emoji o URL Blob"/><input className={input} name="imageAlt" placeholder="Texto alternativo"/><select className={input} name="baseUnit"><option value="UNIT">Unidad</option><option value="ML">Mililitros</option></select><label className="block"><input type="checkbox" name="sellable" defaultChecked/> Vendible</label><label className="block"><input type="checkbox" name="inventoryTracked"/> Controla inventario</label><button className="rounded bg-primary px-3 py-2 text-on-primary">Crear producto</button></form>
      <form action={createVariantAction} className="space-y-2 rounded-xl border p-4"><h2 className="font-semibold">Nueva variante</h2><input type="hidden" name="operationId" value={generateOperationId()}/><select className={input} name="productId" required>{categories.flatMap((category) => category.products).map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select><input className={input} name="name" required placeholder="Grande"/><input className={input} name="sku" placeholder="SKU de presentación"/><input className={input} name="internalCode" placeholder="Código interno"/><input className={input} name="barcode" placeholder="Código de barras"/><select className={input} name="baseUnit"><option value="UNIT">Unidad</option><option value="ML">Mililitros</option></select><input className={input} name="legacyPrice" type="number" min="0" step="0.01" required placeholder="Precio legacy"/><button className="rounded bg-primary px-3 py-2 text-on-primary">Crear variante</button></form>
    </section>
    {categories.map((category) => <section key={category.id} className="space-y-3 rounded-xl border p-4">
      <form action={updateCategoryAction} className="flex flex-wrap items-center gap-2"><input type="hidden" name="categoryId" value={category.id}/><input type="hidden" name="version" value={category.version}/><input className={input} name="name" defaultValue={category.name}/><input className={input} name="slug" defaultValue={category.slug ?? category.name}/><input className={input} name="description" defaultValue={category.description ?? ""}/><input className={input} name="icon" defaultValue={category.icon ?? ""}/><input className={input} name="imageAlt" defaultValue={category.imageAlt ?? ""}/><input className={input} name="position" type="number" defaultValue={category.position}/><label><input name="active" type="checkbox" defaultChecked={category.active}/> Activa</label><button className="text-sm underline">Guardar categoría</button></form>
      {category.products.map((product) => <article key={product.id} className="space-y-3 rounded-lg bg-surface-container p-3">
        <form action={updateProductAction} className="flex flex-wrap gap-2"><input type="hidden" name="productId" value={product.id}/><input type="hidden" name="version" value={product.version}/><select className={input} name="categoryId" defaultValue={product.categoryId}>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input className={input} name="name" defaultValue={product.name}/><input className={input} name="description" defaultValue={product.description ?? ""} placeholder="Descripción"/><input className={input} name="sku" defaultValue={product.sku ?? ""} placeholder="SKU"/><input className={input} name="internalCode" defaultValue={product.internalCode ?? ""} placeholder="Código"/><input className={input} name="barcode" defaultValue={product.barcode ?? ""} placeholder="Barcode"/><input className={input} name="icon" defaultValue={product.icon ?? ""} placeholder="Imagen/emoji"/><input className={input} name="imageAlt" defaultValue={product.imageAlt ?? ""} placeholder="Alt"/><select className={input} name="baseUnit" defaultValue={product.baseUnit}><option value="UNIT">UNIT</option><option value="ML">ML</option></select><input className={input} name="position" type="number" defaultValue={product.position}/><label><input name="active" type="checkbox" defaultChecked={product.active}/> Activo</label><label><input name="sellable" type="checkbox" defaultChecked={product.sellable}/> Vendible</label><label><input name="inventoryTracked" type="checkbox" defaultChecked={product.inventoryTracked}/> Inventario</label><button className="text-sm underline">Guardar producto</button></form>
        <div className="flex flex-wrap gap-2">{product.variants.map((variant) => <form key={variant.id} action={updateVariantAction} className="flex flex-wrap gap-1 rounded border p-2"><input type="hidden" name="variantId" value={variant.id}/><input type="hidden" name="version" value={variant.version}/><input className={input} name="name" defaultValue={variant.name}/><input className={input} name="sku" defaultValue={variant.sku ?? ""} placeholder="SKU"/><input className={input} name="internalCode" defaultValue={variant.internalCode ?? ""} placeholder="Código"/><input className={input} name="barcode" defaultValue={variant.barcode ?? ""} placeholder="Barcode"/><select className={input} name="baseUnit" defaultValue={variant.baseUnit}><option>UNIT</option><option>ML</option></select><input className={input} name="legacyPrice" type="number" step="0.01" min="0" defaultValue={variant.price}/><input className={input} name="position" type="number" defaultValue={variant.position}/><label><input name="active" type="checkbox" defaultChecked={variant.active}/> Activa</label><button className="text-xs underline">Guardar variante</button></form>)}</div>
        <details><summary className="cursor-pointer text-sm font-semibold">Overrides por sucursal</summary><div className="mt-2 grid gap-2 md:grid-cols-2">{branches.map((branch) => { const override = product.branchOverrides.find((item) => item.branchId === branch.id); return <form key={branch.id} action={setOverrideAction} className="flex flex-wrap gap-2 rounded border p-2 text-sm"><input type="hidden" name="branchId" value={branch.id}/><input type="hidden" name="productId" value={product.id}/><input type="hidden" name="version" value={override?.version ?? 0}/><strong>{branch.name}</strong><label><input name="enabled" type="checkbox" defaultChecked={override?.enabled ?? true}/> Habilitado</label><label><input name="visibleInPos" type="checkbox" defaultChecked={override?.visibleInPos ?? true}/> Visible</label><select className={input} name="availability" defaultValue={override?.availability ?? "AVAILABLE"}><option value="AVAILABLE">Disponible</option><option value="TEMPORARILY_UNAVAILABLE">No disponible temporalmente</option></select><input className={input} name="sortOrder" type="number" defaultValue={override?.sortOrder ?? ""} placeholder="Orden local"/><button className="underline">Guardar</button></form>; })}</div></details>
        {!product.archivedAt && <form action={archiveProductAction}><input type="hidden" name="productId" value={product.id}/><input type="hidden" name="version" value={product.version}/><button className="text-sm text-error underline">Archivar sin borrar</button></form>}
      </article>)}
    </section>)}
  </main>;
}
