import Link from "next/link";
import { requireModuleAccess } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { QrRecordActions } from "@/components/liquors/PublicQrWizard";
import { PageHeader } from "@/components/ui/CompactUI";
import type { PublicQrRecord } from "@/lib/publicQr";

export default async function LiquorProductionQrPage() {
  await requireModuleAccess("/liquors/production");
  const profiles = await prisma.publicQrProfile.findMany({ orderBy: { updatedAt: "desc" } });
  const records = profiles.map((profile): PublicQrRecord => ({ id: profile.id, publicId: profile.publicId, batchId: profile.batchId, lotId: profile.lotId, productName: profile.productName, lotCode: profile.lotCode, payload: profile.payload as PublicQrRecord["payload"], visibility: profile.visibility as PublicQrRecord["visibility"], status: profile.status, createdAt: profile.createdAt.toISOString(), publishedAt: profile.publishedAt?.toISOString() ?? null, updatedAt: profile.updatedAt.toISOString() }));
  return <main className="page-frame text-on-surface"><div className="mx-auto max-w-7xl"><PageHeader title="QR / Etiquetado" description="Crea fichas públicas para lotes de tequila o elaboraciones de licor." actions={<div className="flex flex-wrap gap-2"><Link href="/liquors/production/qr/new" className="compact-action">+ QR de tequila</Link><Link href="/liquors/production/qr/new/licor" className="compact-action bg-primary font-semibold text-on-primary">+ QR de licor</Link></div>} /><div className="mt-4 flex gap-1 overflow-x-auto rounded-xl border border-outline-variant bg-surface-container p-1"><Link href="/liquors/production" className="shrink-0 rounded-lg px-4 py-2 text-sm font-semibold text-on-surface-variant hover:bg-surface-container-high">Proceso de elaboración</Link><Link href="/liquors/production/qr" className="shrink-0 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-on-primary">QR / Etiquetado</Link></div><section className="mt-5"><h2 className="text-lg font-semibold">Etiquetas existentes</h2>{records.length === 0 ? <p className="mt-3 rounded-xl border border-dashed border-outline-variant p-6 text-sm text-on-surface-variant">Todavía no hay fichas. Crea la primera con el asistente.</p> : <div className="mt-3 grid gap-3 md:grid-cols-2">{records.map((record) => <article key={record.id} className="rounded-xl border border-outline-variant bg-surface-container p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{record.productName}</h3><p className="mt-1 text-xs text-on-surface-variant">{record.lotCode || "Sin lote relacionado"} · {record.lotId ? "Tequila" : "Licor"} · {record.status.toLowerCase()}</p></div><span className="rounded-full bg-surface-container-high px-2 py-1 text-[11px] font-semibold">{record.status}</span></div><div className="mt-3"><QrRecordActions record={record} /></div></article>)}</div>}</section><section className="mt-8 rounded-xl border border-outline-variant bg-surface-container p-4"><h2 className="font-semibold">Editores separados</h2><p className="mt-1 text-sm text-on-surface-variant">Tequila y licor tienen editores independientes. Las fichas existentes se pueden modificar sin cambiar su URL ni su QR.</p></section></div></main>;
}
