import Link from "next/link";
import { requireAdmin } from "@/lib/auth";
import { listEmployees } from "@/lib/workforce/employment/service";
import { prisma } from "@/lib/prisma";
const states: Record<string,string> = {ACTIVE:"Activo",INACTIVE:"Inactivo",TERMINATED:"Baja",NONE:"Sin relación laboral"};
export default async function EmployeesPage({searchParams}:{searchParams:Promise<{q?:string;branch?:string;status?:string}>}) {
  await requireAdmin();
  const filters=await searchParams;
  const [all,branches]=await Promise.all([listEmployees(),prisma.branch.findMany({where:{active:true},orderBy:{name:"asc"}})]);
  const rows=all.map(employee=>{const current=employee.employments.find(e=>e.status!=="TERMINATED")??employee.employments[0];const assignments=current?.status!=="TERMINATED"?current?.branchAssignments??[]:[];return {employee,current,assignments,home:assignments.find(a=>a.type==="HOME")?.branch.name??"Sin sucursal",allowed:assignments.filter(a=>a.type==="ALLOWED").map(a=>a.branch.name).join(", ")||"—",status:current?.status??"NONE",rate:current?.status!=="TERMINATED"?current?.payRates[0]:null};}).filter(row=>(!filters.q||`${row.employee.displayName??""} ${row.employee.employeeNumber??""} ${row.employee.user?.username??""}`.toLocaleLowerCase().includes(filters.q.toLocaleLowerCase()))&&(!filters.status||row.status===filters.status)&&(!filters.branch||row.assignments.some(a=>a.branchId===filters.branch)));
  const rate=(row:typeof rows[number])=>row.rate?`${row.rate.currency??"Sin moneda"} ${Number(row.rate.amount).toFixed(2)} / ${{HOURLY:"hora",DAILY:"día",WEEKLY:"semana",SALARY:"salario"}[row.rate.rateType]}`:"Sin tarifa registrada";
  return <section className="space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold">Empleados</h1><p className="text-sm text-on-surface-variant">Trabajadores, sucursales y condiciones laborales.</p></div><Link href="/administration/workforce/employees/new" className="rounded-lg bg-primary px-4 py-3 font-bold text-on-primary">+ Nuevo empleado</Link></header>
    <form className="grid gap-3 rounded-xl border border-outline-variant p-4 sm:grid-cols-[2fr_1fr_1fr_auto]"><label className="text-sm">Buscar empleado<input name="q" defaultValue={filters.q} placeholder="Nombre o usuario" className="mt-1 w-full rounded-lg border bg-surface px-3 py-2"/></label><label className="text-sm">Sucursal<select name="branch" defaultValue={filters.branch??""} className="mt-1 w-full rounded-lg border bg-surface px-3 py-2"><option value="">Todas las sucursales</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="text-sm">Estado<select name="status" defaultValue={filters.status??""} className="mt-1 w-full rounded-lg border bg-surface px-3 py-2"><option value="">Todos los estados</option>{Object.entries(states).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><button className="self-end rounded-lg border px-4 py-2 font-semibold">Filtrar</button></form>
    <p className="text-sm text-on-surface-variant">{rows.length} empleados</p>
    <div className="hidden overflow-x-auto rounded-xl border border-outline-variant md:block"><table className="w-full text-left text-sm"><thead className="bg-surface-container"><tr>{["Empleado","Estado","Sucursal principal","Sucursales permitidas","Tarifa","Acciones"].map(label=><th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.employee.id} className="border-t border-outline-variant"><td className="p-3"><Link className="font-bold hover:underline" href={`/administration/workforce/employees/${row.employee.id}`}>{row.employee.displayName??"Sin nombre"}</Link><p className="text-xs text-on-surface-variant">{row.employee.user?`@${row.employee.user.username}`:"Sin usuario vinculado"}</p></td><td className="p-3">{states[row.status]}</td><td className="p-3">{row.home}</td><td className="p-3">{row.allowed}</td><td className="p-3">{rate(row)}</td><td className="p-3"><Link className="font-semibold text-primary" href={`/administration/workforce/employees/${row.employee.id}`}>Ver / Editar</Link></td></tr>)}</tbody></table></div>
    <div className="space-y-3 md:hidden">{rows.map(row=><article key={row.employee.id} className="rounded-xl border border-outline-variant p-4"><div className="flex justify-between gap-3"><h2 className="font-bold">{row.employee.displayName??"Sin nombre"}</h2><span className="text-sm">{states[row.status]}</span></div><p className="mt-2 text-sm">{row.home}</p>{row.allowed!=="—"&&<p className="text-sm text-on-surface-variant">También: {row.allowed}</p>}<p className="my-2 text-sm">{rate(row)}</p><Link className="inline-block py-2 font-semibold text-primary" href={`/administration/workforce/employees/${row.employee.id}`}>Ver / Editar</Link></article>)}</div>
    {!rows.length&&<p className="rounded-xl border p-6 text-center">No hay empleados que coincidan. Puedes ajustar los filtros o crear un empleado.</p>}
  </section>;
}
