"use client";

import { CartesianGrid, Line, LineChart, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { formatBusinessTime } from "@/lib/dateTime";
import type { ReactElement } from "react";

type CookingEvent = { id: string; type: string; createdAt: Date | string; temperatureTop: number | null; temperatureMiddle: number | null; temperatureBottom: number | null };
type SteamInterval = { id: string; state: string; startedAt: Date | string; endedAt: Date | string | null; pressureReadings: Array<{ occurredAt: Date | string; canonicalPsi: unknown }> };

export default function CookingCharts({ events, steamIntervals = [] }: { events: CookingEvent[]; steamIntervals?: SteamInterval[] }) {
  const data = events.filter((event) => event.type === "TEMPERATURA").map((event) => ({ timestamp: new Date(event.createdAt).getTime(), superior: event.temperatureTop, media: event.temperatureMiddle, inferior: event.temperatureBottom }));
  const pressure = steamIntervals.flatMap((interval) => interval.pressureReadings.map((reading) => ({ timestamp: new Date(reading.occurredAt).getTime(), psi: Number(reading.canonicalPsi), interval: interval.id }))).sort((a, b) => a.timestamp - b.timestamp);
  return <section className="mt-4 space-y-4 rounded-xl border border-outline-variant bg-surface-container p-4 sm:p-5"><div><h2 className="text-sm font-semibold">Gráficas de cocción</h2><p className="text-xs text-on-surface-variant">Los puntos usan su hora real; no se interpolan eventos con la temperatura más cercana.</p></div>{data.length > 0 && <Chart title="Temperatura por hora"><LineChart data={data} margin={{ top: 10, right: 30, left: 10, bottom: 10 }}><CartesianGrid strokeDasharray="3 3" stroke="var(--color-outline-variant)" /><XAxis type="number" dataKey="timestamp" domain={["dataMin", "dataMax"]} tickFormatter={(value) => formatBusinessTime(value)} stroke="var(--color-outline)" /><YAxis unit="°C" stroke="var(--color-outline)" /><Tooltip labelFormatter={(value) => formatBusinessTime(Number(value))} /><Legend /><Line type="monotone" dataKey="inferior" name="Inferior" stroke="var(--color-on-surface-variant)" dot /><Line type="monotone" dataKey="media" name="Media" stroke="var(--color-outline)" dot /><Line type="monotone" dataKey="superior" name="Superior" stroke="var(--color-on-surface)" dot /></LineChart></Chart>}{pressure.length > 0 && <Chart title="Presión de vapor (PSI)"><LineChart data={pressure} margin={{ top: 10, right: 30, left: 10, bottom: 10 }}><CartesianGrid strokeDasharray="3 3" stroke="var(--color-outline-variant)" /><XAxis type="number" dataKey="timestamp" domain={["dataMin", "dataMax"]} tickFormatter={(value) => formatBusinessTime(value)} stroke="var(--color-outline)" /><YAxis unit=" PSI" stroke="var(--color-outline)" /><Tooltip labelFormatter={(value) => formatBusinessTime(Number(value))} /><Line type="stepAfter" dataKey="psi" name="PSI canónico" stroke="var(--color-primary)" strokeWidth={2.5} dot /></LineChart></Chart>}{steamIntervals.length > 0 && <div className="rounded-xl bg-surface-container-high p-4"><h3 className="text-sm font-semibold">Franjas de vapor</h3><div className="mt-3 space-y-2">{steamIntervals.map((interval) => <div key={interval.id} className="flex items-center justify-between gap-3 text-sm"><span className="font-semibold">{interval.state === "INYECTANDO" ? "Inyectando" : "Sin inyección"}</span><span className="text-on-surface-variant">{formatBusinessTime(interval.startedAt)} — {interval.endedAt ? formatBusinessTime(interval.endedAt) : "activa"}</span></div>)}</div></div>}{data.length === 0 && pressure.length === 0 && <p className="text-on-surface-variant">Aún no hay temperaturas o presiones registradas para graficar.</p>}</section>;
}

function Chart({ title, children }: { title: string; children: ReactElement }) { return <div className="rounded-xl bg-surface-container-high p-3"><p className="mb-2 text-xs font-semibold">{title}</p><div className="h-64 sm:h-72"><ResponsiveContainer width="100%" height="100%">{children}</ResponsiveContainer></div></div>; }
