"use client";
import { useEffect, useState } from "react";
import { getShiftRequestsForAdmin, reviewShiftRequestAction } from "@/app/actions/shiftRequests";

const LABELS = { CANNOT_WORK: "No puede trabajar", CHANGE_TIME: "Cambio de horario", SWAP: "Intercambio", DAY_OFF: "Día libre" };
type Row = Awaited<ReturnType<typeof getShiftRequestsForAdmin>>[number];
export default function ShiftRequestsManager() {
  const [rows, setRows] = useState<Row[]>([]); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void getShiftRequestsForAdmin().then(setRows); }, []);
  async function review(id: string, approve: boolean) { setBusy(id); setError(null); const result = await reviewShiftRequestAction(id, approve); setBusy(null); if (result.error) return setError(result.error); setRows((items) => items.filter((item) => item.id !== id)); }
  return <div className="space-y-4">{error && <p className="rounded-xl bg-error/10 p-3 text-sm text-error">{error}</p>}{rows.length === 0 && <div className="rounded-2xl border border-dashed border-outline-variant p-8 text-center text-sm text-on-surface-variant">No hay solicitudes pendientes.</div>}{rows.map((row) => <article key={row.id} className="rounded-2xl border border-outline-variant bg-surface-container p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-bold">{row.requestedBy.name} · {LABELS[row.type]}</p><p className="text-sm text-on-surface-variant">{new Date(row.shift.date).toLocaleDateString("es-MX", { dateStyle: "medium", timeZone: "UTC" })} · {row.shift.startTime}–{row.shift.endTime} · {row.shift.branch?.name}</p></div><span className="rounded-full bg-secondary/10 px-3 py-1 text-xs font-bold text-secondary">Pendiente</span></div><p className="mt-3 rounded-xl bg-surface-container-high p-3 text-sm">{row.reason}</p>{row.type === "CHANGE_TIME" && <p className="mt-2 text-sm font-semibold">Solicita: {row.proposedStartTime}–{row.proposedEndTime}</p>}{row.type === "SWAP" && <p className="mt-2 text-sm font-semibold">Intercambio con: {row.swapTargetUser?.name}</p>}<div className="mt-4 flex gap-2"><button onClick={() => review(row.id, true)} disabled={busy === row.id} className="rounded-xl bg-primary px-4 py-2 text-sm font-bold text-on-primary disabled:opacity-50">Aprobar</button><button onClick={() => review(row.id, false)} disabled={busy === row.id} className="rounded-xl border border-error/30 px-4 py-2 text-sm font-semibold text-error disabled:opacity-50">Rechazar</button></div></article>)}</div>;
}
