"use client";

import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import { archivePublicQrAction, publishPublicQrAction, savePublicQrAction } from "@/app/actions/publicQr";
import { DEFAULT_VISIBILITY, emptyPayload, formatIsoDate, isVisible, type PublicQrPayload, type PublicQrRecord, type PublicQrVisibility } from "@/lib/publicQr";

type BatchOption = { id: string; code: string; productName: string; productionDate: string; finalAlcohol: number | null; defaultAlcohol: number | null; process?: Partial<PublicQrPayload["process"]> };
type Props = { batches: BatchOption[]; liquorBatches?: BatchOption[]; initial?: PublicQrRecord | null };

const steps = ["Producto", "Lote", "Origen", "Proceso", "Información", "Trazabilidad", "Publicación", "Vista previa"];
const productFields = [
  ["commercialName", "Nombre comercial", "text"], ["type", "Tipo de producto", "select"], ["className", "Clase", "select"], ["presentation", "Presentación", "select"], ["alcoholPercent", "% Alc. Vol.", "number"],
] as const;
const originFields = [["place", "Lugar de elaboración"], ["producer", "Productor"], ["agaveOrigin", "Origen del agave"], ["region", "Región"], ["agaveVariety", "Variedad de agave"], ["harvestYear", "Año/cosecha del agave"]] as const;
const processFields = [["cookingMethod", "Método de cocción"], ["cookingDate", "Fecha de cocción", "date"], ["milling", "Molienda"], ["fermentation", "Fermentación"], ["fermentationDuration", "Duración de fermentación"], ["distillations", "Número de destilaciones"], ["distillationDate", "Fecha de destilación", "date"], ["obtainedAlcohol", "Graduación obtenida"], ["adjustmentWater", "Agua utilizada para ajuste"], ["barrelType", "Tipo de barrica"], ["barrelMaterial", "Material de barrica"], ["barrelOrigin", "Procedencia de barrica"], ["maturationTime", "Tiempo de maduración"], ["barrelEntryDate", "Fecha de entrada a barrica", "date"], ["barrelExitDate", "Fecha de salida de barrica", "date"]] as const;
const consumerFields = [["introduction", "Introducción breve"], ["description", "Descripción del producto"], ["aroma", "Aroma"], ["flavor", "Sabor"], ["body", "Cuerpo"], ["finish", "Final"], ["tastingNotes", "Notas de cata"], ["recommendation", "Recomendación de consumo"], ["temperature", "Temperatura recomendada"], ["pairing", "Maridaje"]] as const;
const traceFields = [["nom", "NOM"], ["authorizedProducer", "Productor autorizado"], ["certificateNumber", "Número de certificado"], ["certificationReference", "Registro o referencia de certificación"], ["internalCode", "Código interno"], ["contact", "Contacto"], ["website", "Página web"]] as const;

function mergePayload(value?: PublicQrPayload | null): PublicQrPayload {
  const base = emptyPayload();
  if (!value) return base;
  return { ...base, ...value, product: { ...base.product, ...value.product }, identification: { ...base.identification, ...value.identification }, origin: { ...base.origin, ...value.origin, place: value.origin?.place || base.origin.place, producer: value.origin?.producer || base.origin.producer }, process: { ...base.process, ...value.process }, consumer: { ...base.consumer, ...value.consumer }, traceability: { ...base.traceability, ...value.traceability } };
}

export default function PublicQrWizard({ batches, liquorBatches = [], initial }: Props) {
  const [step, setStep] = useState(0);
  const [payload, setPayload] = useState<PublicQrPayload>(() => mergePayload(initial?.payload));
  const [visibility, setVisibility] = useState<PublicQrVisibility>(() => ({ ...DEFAULT_VISIBILITY, ...(initial?.visibility ?? {}) }));
  const initialSourceKind = initial?.batchId ? "batch" : "lot";
  const [sourceKind, setSourceKind] = useState<"lot" | "batch">(initialSourceKind);
  const [lotId, setLotId] = useState(initial?.lotId ?? "");
  const [batchId, setBatchId] = useState(initial?.batchId ?? "");
  const [recordId, setRecordId] = useState(initial?.id ?? "");
  const [publicId, setPublicId] = useState(initial?.publicId ?? "");
  const [message, setMessage] = useState("");
  const [pending, startTransition] = useTransition();
  const sourceOptions = sourceKind === "lot" ? batches : liquorBatches;
  const selectedBatch = sourceOptions.find((batch) => batch.id === (sourceKind === "lot" ? lotId : batchId));
  const update = (section: keyof PublicQrPayload, key: string, value: string) => setPayload((current) => ({ ...current, [section]: { ...current[section], [key]: value } }));

  function selectBatch(value: string) {
    if (sourceKind === "lot") setLotId(value); else setBatchId(value);
    const batch = sourceOptions.find((item) => item.id === value);
    if (!batch) return;
    setPayload((current) => ({ ...current, product: { ...current.product, commercialName: current.product.commercialName || batch.productName, alcoholPercent: current.product.alcoholPercent || String(batch.finalAlcohol ?? batch.defaultAlcohol ?? "") }, identification: { ...current.identification, lotCode: batch.code, elaborationDate: current.identification.elaborationDate || formatIsoDate(batch.productionDate) }, process: { ...current.process, ...batch.process } }));
  }

  function save(publish = false) {
    setMessage("");
    startTransition(async () => {
      try {
        const input = JSON.stringify({ id: recordId || undefined, lotId: sourceKind === "lot" ? lotId || null : null, batchId: sourceKind === "batch" ? batchId || null : null, payload, visibility });
        const result = publish ? await publishPublicQrAction(input) : await savePublicQrAction(input);
        setRecordId(result.id); setPublicId(result.publicId); setMessage(publish ? "Publicado. La URL del QR quedó permanente." : "Borrador guardado.");
      } catch (error) { setMessage(error instanceof Error ? error.message : "No fue posible guardar la ficha."); }
    });
  }

  return <div className="space-y-5">
    <div className="flex gap-1 overflow-x-auto pb-1" aria-label="Pasos del asistente">{steps.map((label, index) => <button key={label} type="button" onClick={() => setStep(index)} className={`shrink-0 rounded-full px-3 py-1.5 text-xs font-semibold ${step === index ? "bg-primary text-on-primary" : "bg-surface-container text-on-surface-variant"}`}>{index + 1}. {label}</button>)}</div>
    {step === 0 && <WizardCard title="Paso 1 · Producto" description="Define la presentación pública sin tocar la receta interna. Las opciones se pueden ampliar con una opción personalizada."><div className="grid gap-3 sm:grid-cols-2">{productFields.map(([key, label, type]) => <Field key={key} label={label} value={payload.product[key]} type={type} options={key === "type" ? ["Tequila", "Tequila 100% agave", "Otra"] : key === "className" ? ["Blanco", "Joven", "Reposado", "Añejo", "Extra añejo", "Otra"] : key === "presentation" ? ["750 ml", "1 L", "Otra"] : undefined} onChange={(value) => update("product", key, value)} />)}{(["type", "className", "presentation"] as const).filter((key) => payload.product[key] === "Otra").map((key) => <Field key={`${key}-custom`} label={`Nueva opción para ${key === "type" ? "tipo" : key === "className" ? "clase" : "presentación"}`} value="" onChange={(value) => update("product", key, value)} />)}</div></WizardCard>}
    {step === 1 && <WizardCard title="Paso 2 · Identificación y lote" description="Usa el mismo editor para tequila o para una elaboración de licor."><div className="space-y-3"><label className="block text-sm font-medium text-on-surface">Origen de la etiqueta<select className="compact-field mt-1 w-full border border-outline-variant bg-surface text-on-surface" value={sourceKind} onChange={(event) => { const value = event.target.value as "lot" | "batch"; setSourceKind(value); setLotId(""); setBatchId(""); }} disabled={Boolean(recordId)}><option value="lot">Lote del proceso de tequila</option><option value="batch">Lote de elaboración de licor</option></select></label><label className="block text-sm font-medium text-on-surface">{sourceKind === "lot" ? "Lote de tequila" : "Lote de licor"}<select className="compact-field mt-1 w-full border border-outline-variant bg-surface text-on-surface" value={sourceKind === "lot" ? lotId : batchId} onChange={(event) => selectBatch(event.target.value)} disabled={Boolean(recordId)}><option value="">Selecciona un lote…</option>{sourceOptions.map((batch) => <option key={batch.id} value={batch.id}>{batch.code} · {batch.productName}</option>)}</select></label>{selectedBatch && <p className="rounded-lg bg-tertiary-fixed-dim/10 px-3 py-2 text-xs text-on-surface-variant">Se precargaron los datos disponibles del lote. La relación original queda bloqueada al publicar.</p>}<div className="grid gap-3 sm:grid-cols-2"><Field label="Lote" value={payload.identification.lotCode} type="text" onChange={(value) => update("identification", "lotCode", value)} disabled={Boolean(selectedBatch) || Boolean(recordId)} /><Field label="Fecha de elaboración" value={payload.identification.elaborationDate} type="date" onChange={(value) => update("identification", "elaborationDate", value)} disabled={Boolean(selectedBatch) || Boolean(recordId)} /><Field label="Fecha de envasado" value={payload.identification.bottlingDate} type="date" onChange={(value) => update("identification", "bottlingDate", value)} /><Field label="Número de botella (opcional)" value={payload.identification.bottleNumber} type="text" onChange={(value) => update("identification", "bottleNumber", value)} /><Field label="Total de botellas (opcional)" value={payload.identification.totalBottles} type="number" onChange={(value) => update("identification", "totalBottles", value)} /></div></div></WizardCard>}
    {step === 2 && <WizardCard title="Paso 3 · Origen" description="Son datos editables de la ficha pública."><div className="grid gap-3 sm:grid-cols-2">{originFields.map(([key, label]) => <Field key={key} label={label} value={payload.origin[key]} onChange={(value) => update("origin", key, value)} />)}</div></WizardCard>}
    {step === 3 && <WizardCard title="Paso 4 · Proceso" description="Publica sólo lo que el consumidor necesita; costos, rendimientos y recetas internas nunca se muestran."><div className="grid gap-3 sm:grid-cols-2">{processFields.map(([key, label, type]) => <Field key={key} label={label} value={payload.process[key]} type={type ?? "text"} onChange={(value) => update("process", key, value)} />)}</div></WizardCard>}
    {step === 4 && <WizardCard title="Paso 5 · Información para el consumidor"><div className="grid gap-3 sm:grid-cols-2">{consumerFields.map(([key, label]) => <Field key={key} label={label} value={payload.consumer[key]} multiline={key === "description" || key === "tastingNotes" || key === "recommendation"} onChange={(value) => update("consumer", key, value)} />)}</div></WizardCard>}
    {step === 5 && <WizardCard title="Paso 6 · Datos de trazabilidad / etiqueta" description="Deja vacío lo que no tengas confirmado; no inventamos certificaciones."><div className="grid gap-3 sm:grid-cols-2">{traceFields.map(([key, label]) => <Field key={key} label={label} value={payload.traceability[key]} type={key === "website" ? "url" : "text"} onChange={(value) => update("traceability", key, value)} />)}</div></WizardCard>}
    {step === 6 && <WizardCard title="Paso 7 · Elegir qué verá el cliente" description="Activa u oculta cada dato sin cambiar la información guardada."><div className="grid gap-2 sm:grid-cols-2">{Object.entries(DEFAULT_VISIBILITY).map(([key]) => <label key={key} className="flex items-center justify-between rounded-lg border border-outline-variant px-3 py-2 text-sm"><span>{labelFor(key)}</span><input type="checkbox" checked={visibility[key] !== false} onChange={(event) => setVisibility((current) => ({ ...current, [key]: event.target.checked }))} /></label>)}</div></WizardCard>}
    {step === 7 && <WizardCard title="Paso 8 · Vista previa" description="Así se verá en un teléfono al escanear el QR."><div className="mx-auto max-w-sm"><PublicQrPreview payload={payload} visibility={visibility} /></div></WizardCard>}
    <div className="flex flex-wrap items-center justify-between gap-2 border-t border-outline-variant pt-4"><button type="button" className="compact-action" disabled={step === 0 || pending} onClick={() => setStep((value) => Math.max(0, value - 1))}>Atrás</button><div className="flex flex-wrap gap-2"><button type="button" className="compact-action" disabled={pending} onClick={() => save(false)}>{pending ? "Guardando…" : "Guardar borrador"}</button>{step < steps.length - 1 ? <button type="button" className="compact-action bg-primary text-on-primary" onClick={() => setStep((value) => Math.min(steps.length - 1, value + 1))}>Siguiente</button> : <button type="button" className="compact-action bg-primary text-on-primary" disabled={pending} onClick={() => save(true)}>Publicar y crear QR</button>}</div></div>
    {message && <p className="rounded-lg bg-surface-container px-3 py-2 text-sm text-on-surface-variant">{message}{publicId && <>{" "}<Link className="font-semibold text-primary underline" href={`/q/${sourceKind === "batch" ? "licor" : "tequila"}/${publicId}`} target="_blank">Abrir ficha pública</Link></>}</p>}
    {recordId && <p className="text-xs text-on-surface-variant">ID estable: {publicId || recordId}</p>}
  </div>;
}

export function PublicQrPreview({ payload, visibility }: { payload: PublicQrPayload; visibility: PublicQrVisibility }) {
  const rows = useMemo(() => [
    ["Tipo", payload.product.type, "productType"], ["Clase", payload.product.className, "productClass"], ["Presentación", payload.product.presentation, "presentation"], ["Lote", payload.identification.lotCode, "lotCode"], ["Elaboración", payload.identification.elaborationDate, "elaborationDate"], ["Envasado", payload.identification.bottlingDate, "bottlingDate"], ["Alcohol", payload.product.alcoholPercent ? `${payload.product.alcoholPercent}%` : "", "alcoholPercent"], ["Ubicación", payload.origin.place, "place"], ["Origen", payload.origin.agaveOrigin, "agaveOrigin"],
  ].filter(([, value, key]) => value && isVisible(visibility, key)), [payload, visibility]);
  return <article className="overflow-hidden rounded-[1.6rem] border border-emerald-900/20 bg-[#f8f4e9] text-[#173b32] shadow-lg"><div className="bg-[#173b32] px-5 py-6 text-center text-white"><p className="text-[10px] font-bold uppercase tracking-[0.28em] text-emerald-200">Casa Destiladora del Norte</p><h2 className="mt-3 text-2xl font-semibold">{payload.product.commercialName || "Nombre del producto"}</h2><p className="mt-2 text-sm text-emerald-100">{payload.consumer.introduction}</p></div><div className="space-y-4 p-5"><div className="grid grid-cols-2 gap-2">{rows.map(([label, value]) => <div key={label} className="rounded-xl bg-white/70 p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-emerald-900/55">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>)}</div>{isVisible(visibility, "description") && payload.consumer.description && <TextBlock title="Descripción" text={payload.consumer.description} />}{isVisible(visibility, "tastingNotes") && payload.consumer.tastingNotes && <TextBlock title="Notas de cata" text={payload.consumer.tastingNotes} />}{isVisible(visibility, "recommendation") && payload.consumer.recommendation && <TextBlock title="Cómo disfrutarlo" text={payload.consumer.recommendation} />}</div></article>;
}

function TextBlock({ title, text }: { title: string; text: string }) { return <section><h3 className="text-xs font-bold uppercase tracking-wide text-emerald-900/60">{title}</h3><p className="mt-1 text-sm leading-6">{text}</p></section>; }
function labelFor(key: string) { return ({ productType: "Tipo de tequila", productClass: "Clase", presentation: "Presentación", lotCode: "Lote", elaborationDate: "Fecha de elaboración", bottlingDate: "Fecha de envasado", alcoholPercent: "% Alc. Vol.", place: "Lugar de elaboración", producer: "Productor", agaveOrigin: "Origen del agave", region: "Región", agaveVariety: "Variedad de agave", harvestYear: "Año/cosecha", process: "Proceso", barrel: "Barrica", introduction: "Introducción", description: "Descripción", aroma: "Aroma", flavor: "Sabor", body: "Cuerpo", finish: "Final", tastingNotes: "Notas de cata", recommendation: "Recomendación", temperature: "Temperatura", pairing: "Maridaje", nom: "NOM", authorizedProducer: "Productor autorizado", certificateNumber: "Número de certificado", certificationReference: "Referencia de certificación", internalCode: "Código interno", contact: "Contacto", website: "Página web" } as Record<string, string>)[key] ?? key; }
function Field({ label, value, onChange, type = "text", options, multiline, disabled }: { label: string; value: string; onChange: (value: string) => void; type?: string; options?: readonly string[]; multiline?: boolean; disabled?: boolean }) { const control = "compact-field mt-1 w-full border border-outline-variant bg-surface text-on-surface"; return <label className="block text-sm font-medium text-on-surface">{label}{options ? <select className={control} value={value} onChange={(event) => onChange(event.target.value)} disabled={disabled}><option value="">Selecciona…</option>{options.map((option) => <option key={option}>{option}</option>)}</select> : multiline ? <textarea className={`${control} min-h-24 p-2`} value={value} onChange={(event) => onChange(event.target.value)} disabled={disabled} /> : <input className={control} type={type} value={value} onChange={(event) => onChange(event.target.value)} disabled={disabled} />}</label>; }
function WizardCard({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-outline-variant bg-surface-container p-4 sm:p-5"><h2 className="text-lg font-semibold text-on-surface">{title}</h2>{description && <p className="mt-1 text-sm text-on-surface-variant">{description}</p>}<div className="mt-4">{children}</div></section>; }

export function QrRecordActions({ record, editHref }: { record: PublicQrRecord; editHref?: string }) {
  const [pending, startTransition] = useTransition();
  const publicPath = record.batchId ? `/q/licor/${record.publicId}` : `/q/tequila/${record.publicId}`;
  return <div className="flex flex-wrap gap-2 text-xs"><Link className="compact-action" href={publicPath} target="_blank">Ver</Link><Link className="compact-action" href={editHref ?? `/liquors/production/qr/${record.id}/edit`}>Editar</Link><Link className="compact-action" href={`/api/print/qr/public/${record.publicId}`} target="_blank">Descargar QR</Link><button className="compact-action text-error" disabled={pending || record.status === "ARCHIVADO"} onClick={() => { if (!window.confirm("¿Archivar esta ficha?")) return; startTransition(async () => { await archivePublicQrAction(record.id); window.location.reload(); }); }}>Archivar</button></div>;
}
