import assert from 'node:assert/strict';import test from 'node:test';
import {clockError,clockStateLabel,displayedSession,durationClock,clockSuccess,userClockEventLabel} from '../../app/workforce/clock/presentation';
const event=(type:string,time:string)=>({type,occurredAt:`2026-09-06T${time}:00Z`,branchId:'real-branch'});
test('timer resumes from canonical clock-in after reload and advances by seconds',()=>{const events=[event('CLOCK_IN','10:00')];const now=Date.parse('2026-09-06T11:27:43Z');assert.equal(durationClock(displayedSession(events,now)!.seconds),'01:27:43');assert.equal(displayedSession(events,now+1000)!.seconds,5264);assert.equal(displayedSession([...events],now)!.seconds,5263);});
test('active and completed breaks are excluded from worked time',()=>{const events=[event('CLOCK_IN','10:00'),event('BREAK_START','11:00')];assert.equal(displayedSession(events,Date.parse('2026-09-06T11:30:00Z'))!.seconds,3600);events.push(event('BREAK_END','11:30'));assert.equal(displayedSession(events,Date.parse('2026-09-06T12:00:00Z'))!.seconds,5400);});
test('clock-out freezes net time and latest session starts from its own entry',()=>{const events=[event('CLOCK_IN','10:00'),event('BREAK_START','11:00'),event('BREAK_END','11:30'),event('CLOCK_OUT','12:00')];assert.equal(displayedSession(events,Date.parse('2026-09-06T15:00:00Z'))!.seconds,5400);events.push(event('CLOCK_IN','14:00'));assert.equal(displayedSession(events,Date.parse('2026-09-06T15:00:00Z'))!.seconds,3600);});
test('friendly confirmations and no invented session',()=>{assert.equal(clockSuccess('CLOCK_IN'),'✓ Turno iniciado correctamente');assert.equal(clockSuccess('CLOCK_OUT'),'✓ Turno finalizado correctamente');assert.equal(displayedSession([],Date.now()),null);});
test('employee clock exposes only simple operational states',()=>{assert.equal(clockStateLabel('NO_SESSION'),'Sin turno activo');assert.equal(clockStateLabel('CLOCKED_IN'),'Turno en curso');assert.equal(clockStateLabel('ON_BREAK'),'Turno en curso');assert.equal(userClockEventLabel('CLOCK_IN'),'Entrada');assert.equal(userClockEventLabel('BREAK_START'),'Registro');});
test('clock errors are human and actionable',()=>{assert.equal(clockError('INVALID_TRANSITION: CLOCKED_IN → CLOCK_IN'),'Ya tienes un turno activo.');assert.equal(clockError('CLOCK_OUT requiere una entrada activa válida.'),'No puedes registrar salida porque no hay una entrada activa.');assert.equal(clockError('INVALID_TRANSITION: ON_BREAK → CLOCK_OUT'),'No se pudo registrar tu turno. Intenta nuevamente.');});
