import Link from "next/link";
import { requireModuleAccess } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { QrRecordActions } from "@/components/liquors/PublicQrWizard";
import { PageHeader } from "@/components/ui/CompactUI";
import type { PublicQrRecord } from "@/lib/publicQr";

export default async function LiquorLabelsPage() {
  await requireModuleAccess("/liquors/production");
  const profiles = await prisma.publicQrProfile.findMany({ where: { batchId: { not: null } }, orderBy: { updatedAt: "desc" } });
  const records = profiles.map((profile): PublicQrRecord => ({ id: profile.id, publicId: profile.publicId, batchId: profile.batchId, lotId: profile.lotId, productName: profile.productName, lotCode: profile.lotCode, payload: profile.payload as PublicQrRecord["payload"], visibility: profile.visibility as PublicQrRecord["visibility"], status: profile.status, createdAt: profile.createdAt.toISOString(), publishedAt: profile.publishedAt?.toISOString() ?? null, updatedAt: profile.updatedAt.toISOString() }));

  return <main className="page-frame text-on-surface"><div className="mx-auto max-w-7xl"><PageHeader title="Crear etiquetas de licores" description="Crea, edita y publica etiquetas de los lotes de elaboración de licores." actions={<Link href="/liquors/production/labels/new" className="compact-action bg-primary font-semibold text-on-primary">+ Crear etiqueta</Link>} /><div className="mt-4 flex gap-1 overflow-x-auto rounded-xl border border-outline-variant bg-surface-container p-1"><Link href="/liquors/production" className="shrink-0 rounded-lg px-4 py-2 text-sm font-semibold text-on-surface-variant hover:bg-surface-container-high">Proceso de elaboración</Link><Link href="/liquors/production/labels" className="shrink-0 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-on-primary">Crear etiquetas</Link></div><section className="mt-5"><h2 className="text-lg font-semibold">Etiquetas de licores existentes</h2>{records.length === 0 ? <div className="mt-3 rounded-xl border border-dashed border-outline-variant p-6"><p className="text-sm text-on-surface-variant">Todavía no hay etiquetas de licor.</p><Link href="/liquors/production/labels/new" className="mt-3 inline-flex compact-action bg-primary text-on-primary">Crear la primera etiqueta</Link></div> : <div className="mt-3 grid gap-3 md:grid-cols-2">{records.map((record) => <article key={record.id} className="rounded-xl border border-outline-variant bg-surface-container p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{record.productName}</h3><p className="mt-1 text-xs text-on-surface-variant">{record.lotCode || "Sin lote relacionado"} · {record.status.toLowerCase()}</p></div><span className="rounded-full bg-surface-container-high px-2 py-1 text-[11px] font-semibold">{record.status}</span></div><div className="mt-3"><QrRecordActions record={record} editHref={`/liquors/production/labels/${record.id}/edit`} /></div></article>)}</div>}</section></div></main>;
}
