import { SubmitButton } from "../SubmitButton";
import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getEmployee } from "@/lib/workforce/employment/service";
import { addWorkforceAllowedBranchAction, changeWorkforceEmploymentStatusAction, changeWorkforceHomeAction, changeWorkforcePayRateAction, updateWorkforceEmployeeAction, rehireWorkforceEmployeeAction, changeWorkforceJornadaAction, endWorkforceAllowedBranchAction } from "@/app/actions/workforceEmployment";
import { applyWorkforceScheduleTemplateAction } from "@/app/actions/workforceScheduling";
const field="mt-1 w-full rounded-lg border border-outline-variant bg-surface px-3 py-2 text-sm";
const panel="space-y-3 rounded-xl border border-outline-variant p-4 sm:p-5";
const button="rounded-lg bg-primary px-4 py-2 font-semibold text-on-primary";
const date=(d:Date|null)=>d?.toISOString().slice(0,10)??"Sin registrar";
const states={ACTIVE:"Activo",INACTIVE:"Inactivo",TERMINATED:"Baja"};
const jornadas={DAY:"Diurna",NIGHT:"Nocturna",MIXED:"Mixta"};
export default async function EmployeeDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;saved?:string;assignedBranch?:string}>}) {
  await requireAdmin();const {id}=await params;const query=await searchParams;
  const [employee,branches]=await Promise.all([getEmployee(id),prisma.branch.findMany({where:{active:true},include:{defaultScheduleTemplate:{include:{shifts:true}}},orderBy:{name:"asc"}})]);
  if(!employee)notFound();
  const open=employee.employments.find(e=>e.status!=="TERMINATED");const current=open??employee.employments[0];
  const now=new Date();const today=date(now);const live=current?.branchAssignments.filter(a=>a.effectiveFrom<=now&&(!a.effectiveTo||a.effectiveTo>now))??[];
  const home=live.find(a=>a.type==="HOME");const assigned=branches.find(b=>b.id===(query.assignedBranch??home?.branchId));const template=assigned?.defaultScheduleTemplate;
  const currentJornada=open?.jornadaPolicies.find(p=>date(p.effectiveFrom)<=today&&(!p.effectiveTo||date(p.effectiveTo)>=today));
  const nextMonday=new Date(now);nextMonday.setUTCHours(0,0,0,0);nextMonday.setUTCDate(nextMonday.getUTCDate()+7-((nextMonday.getUTCDay()+6)%7));const week=date(nextMonday);
  const ids= <><input type="hidden" name="employeeId" value={id}/><input type="hidden" name="employmentId" value={current?.id??""}/></>;
  const effective= <label className="block text-sm">Vigente desde<input required type="date" name="effectiveFrom" defaultValue={today} className={field}/></label>;
  const branchSelect= <label className="block text-sm">Sucursal<select required name="branchId" className={field}><option value="">Seleccionar sucursal</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>;
  return <section className="space-y-5"><Link href="/administration/workforce/employees" className="text-sm text-primary">← Empleados</Link><header><h1 className="break-words text-3xl font-bold">{employee.displayName}</h1><p className="mt-1 text-sm text-on-surface-variant">{current?states[current.status]:"Sin relación laboral"} · {employee.user?`@${employee.user.username}`:"Sin usuario vinculado"}</p></header>
    {query.error&&<p role="alert" className="rounded-lg border border-error p-3 text-error">{query.error}</p>}{query.saved&&<p role="status" className="rounded-lg border p-3">Cambios guardados.</p>}
    {open?.status==="ACTIVE"&&template?.active&&assigned&&<section className={`${panel} border-primary/40`}><h2 className="font-bold">Esta sucursal tiene un horario predeterminado.</h2><p className="text-sm">Horario predeterminado disponible: {template.name}. Se crearán turnos borrador.</p><div className="flex flex-wrap gap-2">{["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"].map((day,i)=><span className="rounded border px-2 py-1 text-xs" key={day}>{day}: {template.shifts.filter(s=>s.dayOfWeek===i&&s.startTime&&s.endTime).map(s=>`${s.startTime}–${s.endTime}`).join(", ")||"Descanso"}</span>)}</div><form action={applyWorkforceScheduleTemplateAction}><input type="hidden" name="employmentId" value={open.id}/><input type="hidden" name="templateId" value={template.id}/><input type="hidden" name="weekStart" value={week}/><input type="hidden" name="returnTo" value={`/administration/workforce/schedule?week=${week}&branch=${assigned.id}`}/><SubmitButton className={button}>Aplicar a próxima semana</SubmitButton><p className="mt-2 text-xs text-on-surface-variant">Semana del {week}. No se publica automáticamente.</p></form></section>}
    <form action={updateWorkforceEmployeeAction} className={panel}>{ids}<h2 className="font-bold">Datos del empleado</h2><label className="block">Nombre visible<input required name="displayName" defaultValue={employee.displayName??""} className={field}/></label><SubmitButton className={button}>Guardar nombre</SubmitButton></form>
    {open?<><div className="grid gap-4 lg:grid-cols-2"><section className={panel}><h2 className="text-lg font-bold">Sucursales vigentes</h2><p><strong>Sucursal principal (HOME):</strong> {home?.branch.name??"Sin sucursal"}</p><p className="text-sm"><strong>Permitidas:</strong> {live.filter(a=>a.type==="ALLOWED").map(a=>a.branch.name).join(", ")||"Sin sucursales adicionales"}</p><form action={changeWorkforceHomeAction} className="space-y-3 border-t pt-3">{ids}<h3 className="font-semibold">Asignar sucursal principal</h3>{branchSelect}{effective}<SubmitButton className={button}>Asignar sucursal</SubmitButton></form><form action={addWorkforceAllowedBranchAction} className="space-y-3 border-t pt-3">{ids}<h3 className="font-semibold">Agregar sucursal permitida (ALLOWED)</h3>{branchSelect}{effective}<SubmitButton className={button}>Agregar sucursal permitida</SubmitButton></form>{live.filter(a=>a.type==="ALLOWED").map(a=><form key={a.id} action={endWorkforceAllowedBranchAction} className="space-y-2 border-t pt-3">{ids}<input type="hidden" name="assignmentId" value={a.id}/><p className="text-sm">Terminar permiso: {a.branch.name}</p><label className="block text-sm">Fecha final<input required type="date" name="effectiveTo" defaultValue={today} className={field}/></label><SubmitButton className="rounded border px-3 py-2 text-sm">Terminar asignación</SubmitButton></form>)}</section>
      <div className="space-y-4"><section className={panel}><h2 className="text-lg font-bold">Tarifa</h2><p className="text-sm text-on-surface-variant">Cada cambio crea una nueva tarifa y conserva los importes anteriores.</p><form action={changeWorkforcePayRateAction} className="grid gap-3 sm:grid-cols-2">{ids}<label>Unidad<select name="rateType" className={field}><option value="HOURLY">Por hora</option><option value="DAILY">Por día</option><option value="WEEKLY">Por semana</option><option value="SALARY">Salario</option></select></label><label>Monto<input required type="number" min="0.01" step="0.01" name="amount" className={field}/></label><label>Moneda<input required name="currency" placeholder="Ej. MXN" maxLength={3} className={field}/></label>{effective}<SubmitButton className={`${button} sm:col-span-2`}>Guardar nueva tarifa</SubmitButton></form></section>
      <section className={panel}><h2 className="text-lg font-bold">Tipo de jornada</h2><p className="text-sm">{currentJornada?jornadas[currentJornada.jornadaType]:"Sin registrar"}</p><form action={changeWorkforceJornadaAction} className="space-y-3">{ids}<label className="block">Nueva jornada<select name="jornadaType" className={field}>{Object.entries(jornadas).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{effective}<SubmitButton className={button}>Guardar jornada</SubmitButton></form></section></div></div>
      <section className={panel}><h2 className="text-lg font-bold">Estado laboral</h2><p className="text-sm">Inicio: {date(open.startedAt)}. Los cambios no eliminan turnos, checadas, Timesheets ni nómina.</p><form action={changeWorkforceEmploymentStatusAction} className="flex flex-wrap items-end gap-3">{ids}<input type="hidden" name="effectiveAt" value={today}/><label>Estado<select name="status" defaultValue={open.status} className={field}><option value="ACTIVE">Activo</option><option value="INACTIVE">Inactivo</option></select></label><SubmitButton className={button}>Guardar estado</SubmitButton></form></section>
      <section className={`${panel} border-error/40`}><h2 className="text-lg font-bold">Dar de baja</h2><p className="text-sm">Termina esta relación laboral y conserva todo su historial.</p><form action={changeWorkforceEmploymentStatusAction} className="grid gap-3 sm:grid-cols-2">{ids}<input type="hidden" name="status" value="TERMINATED"/><label>Fecha de baja<input required type="date" name="effectiveAt" defaultValue={today} className={field}/></label><label>Motivo de baja<input required name="terminationReason" className={field}/></label><SubmitButton className="rounded-lg border border-error px-4 py-2 font-semibold text-error sm:col-span-2">Dar de baja</SubmitButton></form></section>
    </>:<section className={panel}><h2 className="text-lg font-bold">Recontratar</h2><p className="text-sm">Crea una nueva relación laboral. Las relaciones anteriores permanecen cerradas.</p><form action={rehireWorkforceEmployeeAction} className="space-y-3"><input type="hidden" name="employeeId" value={id}/><label className="block">Fecha de reingreso (si se conoce)<input type="date" name="startedAt" className={field}/></label><SubmitButton className={button}>Recontratar</SubmitButton></form></section>}
    <section className={panel}><h2 className="text-lg font-bold">Historial laboral</h2>{employee.employments.map(e=><details key={e.id} className="rounded-lg border p-3" open={e.id===current?.id}><summary className="cursor-pointer font-semibold">{states[e.status]} · {date(e.startedAt)} → {date(e.endedAt)}</summary>{e.terminationReason&&<p className="my-2 text-sm">Motivo: {e.terminationReason}</p>}<h3 className="mt-3 font-semibold">Sucursales</h3>{e.branchAssignments.map(a=><p key={a.id} className="text-sm">{a.type} · {a.branch.name} · {date(a.effectiveFrom)} → {date(a.effectiveTo)}</p>)}<h3 className="mt-3 font-semibold">Tarifas</h3>{e.payRates.map(r=><p key={r.id} className="text-sm">{r.currency??"Sin moneda"} {Number(r.amount).toFixed(2)} · {r.rateType} · {date(r.effectiveFrom)} → {date(r.effectiveTo)}</p>)}<h3 className="mt-3 font-semibold">Jornada</h3>{e.jornadaPolicies.map(j=><p key={j.id} className="text-sm">{jornadas[j.jornadaType]} · {date(j.effectiveFrom)} → {date(j.effectiveTo)}</p>)}</details>)}</section>
  </section>;
}
