import { Prisma } from "@prisma/client";
import { Money } from "@/lib/domain/money";

export type EngineLine={id:string;productId:string|null;variantId:string|null;categoryId:string;quantity:string;gross:string};
export type EngineRule={id:string;definitionId:string;code:string;name:string;kind:"PROMOTION"|"DISCOUNT"|"COURTESY";mechanic:"PERCENT_OFF"|"FIXED_AMOUNT_OFF"|"FIXED_BUNDLE_PRICE";scope:"GLOBAL"|"BRANCH";branchId:string|null;targetType:"PRODUCT"|"VARIANT"|"CATEGORY"|"ENTIRE_ORDER";targetId:string|null;percentage:string|null;amount:string|null;bundleQuantity:string|null;priority:number;stacking:"STACKABLE"|"EXCLUSIVE";excludedProductIds:string[];excludedCategoryIds:string[];requiresBeneficiary:boolean;requiresAuthorization:boolean;maxAmount:string|null;validFrom:Date;validTo:Date|null;weekdays:number[];startMinute:number|null;endMinute:number|null;timezone:string};
export type Allocation={lineId:string;amount:string};
export type EvaluatedAdjustment={ruleId:string;definitionId:string;code:string;name:string;kind:EngineRule["kind"];mechanic:EngineRule["mechanic"];percentage:string|null;allocations:Allocation[];amount:string;explanation:string};

function localParts(at:Date,timeZone:string){const parts=new Intl.DateTimeFormat("en-US",{timeZone,weekday:"short",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(at);const get=(type:string)=>parts.find(p=>p.type===type)?.value??"";const days:Record<string,number>={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6};return{weekday:days[get("weekday")],minute:Number(get("hour"))*60+Number(get("minute"))};}
export function isRuleActive(rule:EngineRule,branchId:string,at:Date){if(rule.validFrom>at||(rule.validTo&&at>=rule.validTo))return false;if(rule.scope==="BRANCH"&&rule.branchId!==branchId)return false;const local=localParts(at,rule.timezone);if(rule.weekdays.length&&!rule.weekdays.includes(local.weekday))return false;if(rule.startMinute!==null&&(local.minute<rule.startMinute||local.minute>=rule.endMinute!))return false;return true;}
function matches(rule:EngineRule,line:EngineLine){if(line.productId&&rule.excludedProductIds.includes(line.productId)||rule.excludedCategoryIds.includes(line.categoryId))return false;if(rule.targetType==="ENTIRE_ORDER")return true;if(rule.targetType==="PRODUCT")return line.productId===rule.targetId;if(rule.targetType==="VARIANT")return line.variantId===rule.targetId;return line.categoryId===rule.targetId;}
export function allocateCents(total:string,weights:Array<{key:string;amount:string}>){const cents=Money.from(total).toDecimal().times(100).toDecimalPlaces(0);const sum=weights.reduce((s,w)=>s.plus(w.amount),new Prisma.Decimal(0));if(cents.lte(0)||sum.lte(0))return weights.map(w=>({lineId:w.key,amount:"0.00"}));const rows=weights.map(w=>{const exact=cents.times(w.amount).div(sum),floor=exact.floor();return{key:w.key,cents:floor,fraction:exact.minus(floor)}});const remaining=cents.minus(rows.reduce((s,r)=>s.plus(r.cents),new Prisma.Decimal(0))).toNumber();rows.sort((a,b)=>b.fraction.comparedTo(a.fraction)||a.key.localeCompare(b.key));for(let i=0;i<remaining;i++)rows[i%rows.length].cents=rows[i%rows.length].cents.plus(1);return rows.sort((a,b)=>a.key.localeCompare(b.key)).map(r=>({lineId:r.key,amount:r.cents.div(100).toFixed(2)}));}
export function historicalRefundAmount(lineNet:string,soldQuantity:string,returnedQuantity:string){const sold=new Prisma.Decimal(soldQuantity),returned=new Prisma.Decimal(returnedQuantity);if(sold.lte(0)||returned.lt(0)||returned.gt(sold))throw new Error("INVALID_RETURN_QUANTITY");return Money.from(new Prisma.Decimal(lineNet).times(returned).div(sold)).toString();}
export function evaluateRule(rule:EngineRule,lines:EngineLine[]):EvaluatedAdjustment|null{const eligible=lines.filter(line=>matches(rule,line));if(!eligible.length)return null;let weights:Array<{key:string;amount:string}>=eligible.map(l=>({key:l.id,amount:l.gross})),discount=Money.zero();if(rule.mechanic==="PERCENT_OFF"){const pct=new Prisma.Decimal(rule.percentage!);discount=Money.from(weights.reduce((s,w)=>s.plus(w.amount),new Prisma.Decimal(0)).times(pct).div(100));}else if(rule.mechanic==="FIXED_AMOUNT_OFF"){discount=Money.from(rule.amount!);}else{const bundle=new Prisma.Decimal(rule.bundleQuantity!),totalQty=eligible.reduce((s,l)=>s.plus(l.quantity),new Prisma.Decimal(0)),groups=totalQty.div(bundle).floor();if(groups.lte(0))return null;let units=groups.times(bundle);weights=[];for(const line of [...eligible].sort((a,b)=>a.id.localeCompare(b.id))){if(units.lte(0))break;const take=Prisma.Decimal.min(units,new Prisma.Decimal(line.quantity)),unitGross=new Prisma.Decimal(line.gross).div(line.quantity);weights.push({key:line.id,amount:unitGross.times(take).toString()});units=units.minus(take);}const gross=weights.reduce((s,w)=>s.plus(w.amount),new Prisma.Decimal(0));discount=Money.from(gross.minus(groups.times(rule.amount!)));}
 const gross=Money.from(weights.reduce((s,w)=>s.plus(w.amount),new Prisma.Decimal(0)));if(discount.compare(gross)>0)discount=gross;if(rule.maxAmount&&discount.compare(Money.from(rule.maxAmount))>0)discount=Money.from(rule.maxAmount);if(discount.equals(Money.zero()))return null;const allocations=allocateCents(discount.toString(),weights);return{ruleId:rule.id,definitionId:rule.definitionId,code:rule.code,name:rule.name,kind:rule.kind,mechanic:rule.mechanic,percentage:rule.percentage,allocations,amount:discount.toString(),explanation:`${rule.kind}:${rule.mechanic}:${rule.code}`};}
export function evaluateAutomaticPromotions(input:{branchId:string;at:Date;lines:EngineLine[];rules:EngineRule[]}){const candidates=input.rules.filter(r=>r.kind==="PROMOTION"&&isRuleActive(r,input.branchId,input.at)).map(r=>({rule:r,result:evaluateRule(r,input.lines)})).filter((x):x is {rule:EngineRule;result:EvaluatedAdjustment}=>Boolean(x.result)).sort((a,b)=>b.rule.priority-a.rule.priority||new Prisma.Decimal(b.result.amount).comparedTo(a.result.amount)||a.rule.id.localeCompare(b.rule.id));if(!candidates.length)return[];if(candidates[0].rule.stacking==="EXCLUSIVE")return[candidates[0].result];const remaining=new Map(input.lines.map(l=>[l.id,Money.from(l.gross)])),out:EvaluatedAdjustment[]=[];for(const candidate of candidates.filter(c=>c.rule.stacking==="STACKABLE")){const allocations=candidate.result.allocations.map(a=>{const cap=remaining.get(a.lineId)??Money.zero(),value=Money.from(a.amount),actual=value.compare(cap)>0?cap:value;remaining.set(a.lineId,cap.subtract(actual));return{lineId:a.lineId,amount:actual.toString()};}).filter(a=>a.amount!=="0.00");if(allocations.length)out.push({...candidate.result,allocations,amount:allocations.reduce((s,a)=>s.add(Money.from(a.amount)),Money.zero()).toString()});}return out;}
