"use client";
import { blockedByPermanentDependency, readyCommands, retryDelayMs } from "./domain";
import { classifySyncFailure } from "./policy";
import { getMapping, listCommands, putCommand, saveMapping, setMeta } from "./store";
import type { Pos2CommandEnvelope, SyncTransportResult } from "./types";

export type SyncTransport = (command:Pos2CommandEnvelope,payload:Record<string,unknown>)=>Promise<SyncTransportResult>;
export async function processPos2Queue(transport:SyncTransport,now=()=>new Date(),random=Math.random){const commands=await listCommands();for(const command of commands.filter(item=>item.status==="PENDING"&&blockedByPermanentDependency(item,commands))){await putCommand({...command,status:"FAILED_PERMANENT",lastError:{code:"DEPENDENCY_FAILED",message:"Una operación prerequisite requiere recuperación.",retryable:false}});}let processed=0;while(true){const current=await listCommands(),next=readyCommands(current,now())[0];if(!next)break;await putCommand({...next,status:"SYNCING",lastAttemptAt:now().toISOString()});let payload={...next.payload};const mapping=await getMapping(next.localDraftId);if(mapping){payload={...payload,orderId:mapping.serverOrderId,expectedOrderVersion:mapping.serverVersion};}let response:SyncTransportResult;try{response=await transport(next,payload);}catch{response={ok:false,status:0,code:"NETWORK_ERROR",message:"No fue posible alcanzar el servidor.",retryable:true};}processed+=1;if(response.ok){const acknowledgedAt=now().toISOString();await putCommand({...next,status:"ACKNOWLEDGED",result:response.result,lastError:null,acknowledgedAt,nextAttemptAt:null,attemptCount:next.attemptCount+1,lastAttemptAt:acknowledgedAt});if(next.commandType==="CreateOrder"&&typeof response.result.id==="string"&&typeof response.result.version==="number")await saveMapping({localDraftId:next.localDraftId,serverOrderId:response.result.id,serverVersion:response.result.version,mappedAt:acknowledgedAt});else if(mapping&&typeof response.result.version==="number")await saveMapping({...mapping,serverVersion:response.result.version,mappedAt:acknowledgedAt});await setMeta("lastSuccessfulSync",acknowledgedAt);continue;}const classified=classifySyncFailure(response.status,response.code),attemptCount=next.attemptCount+1;await putCommand({...next,status:classified.status,attemptCount,lastAttemptAt:now().toISOString(),nextAttemptAt:classified.retryable?new Date(now().getTime()+retryDelayMs(attemptCount,random())).toISOString():null,lastError:{code:response.code,message:response.message,retryable:classified.retryable}});if(classified.retryable)break;}return processed;}

const LOCK_NAME="maestro-pos2-sync",LEASE_KEY="maestro:pos2-sync-lease";
export async function withSyncLeader<T>(work:()=>Promise<T>):Promise<T|null>{if("locks" in navigator&&navigator.locks)return navigator.locks.request(LOCK_NAME,{ifAvailable:true},lock=>lock?work():null);const owner=crypto.randomUUID(),now=Date.now();try{const current=JSON.parse(localStorage.getItem(LEASE_KEY)??"null") as {owner:string;expiresAt:number}|null;if(current&&current.expiresAt>now)return null;localStorage.setItem(LEASE_KEY,JSON.stringify({owner,expiresAt:now+15_000}));const confirmed=JSON.parse(localStorage.getItem(LEASE_KEY)??"null") as {owner:string}|null;if(confirmed?.owner!==owner)return null;return await work();}finally{const current=JSON.parse(localStorage.getItem(LEASE_KEY)??"null") as {owner:string}|null;if(current?.owner===owner)localStorage.removeItem(LEASE_KEY);}}

export function httpSyncTransport(credential:()=>Promise<string|null>):SyncTransport{return async(command,payload)=>{const secret=await credential();if(!secret)return{ok:false,status:401,code:"TERMINAL_CREDENTIAL_REQUIRED",message:"La terminal debe autenticarse de nuevo.",retryable:false};const response=await fetch("/api/pos2/sync/commands",{method:"POST",headers:{"Content-Type":"application/json","x-maestro-terminal-id":command.terminalId,"x-maestro-terminal-credential":secret},body:JSON.stringify({schemaVersion:command.schemaVersion,operationId:command.operationId,commandType:command.commandType,payloadHash:command.payloadHash,originalPayload:command.payload,actorId:command.actorId,branchId:command.branchId,payload})});const body=await response.json().catch(()=>null) as {replayed?:boolean;result?:Record<string,unknown>;error?:{code?:string;message?:string;retryable?:boolean}}|null;if(response.ok)return{ok:true,replayed:Boolean(body?.replayed),result:body?.result??{}};return{ok:false,status:response.status,code:body?.error?.code??"SYNC_ERROR",message:body?.error?.message??"No fue posible sincronizar.",retryable:Boolean(body?.error?.retryable)};};}
