"use client";
import { canonicalOfflinePayload, generateClientOperationId, hashOfflinePayload } from "./canonical";
import { compactPending } from "./domain";
import { POS2_OFFLINE_SCHEMA_VERSION, type Pos2CacheSnapshot, type Pos2CommandEnvelope, type Pos2CommandType, type Pos2EntityMapping, type Pos2LocalDraft } from "./types";

const DB_NAME = "maestro-pos2-offline", DB_VERSION = 2;
const stores = { commands: "commands", drafts: "drafts", mappings: "mappings", cache: "cache", meta: "meta" } as const;
function request<T>(value: IDBRequest<T>) { return new Promise<T>((resolve,reject) => { value.onsuccess=()=>resolve(value.result); value.onerror=()=>reject(value.error); }); }
export function openPos2OfflineDatabase() { return new Promise<IDBDatabase>((resolve,reject) => { const opening=indexedDB.open(DB_NAME,DB_VERSION); opening.onupgradeneeded=()=>{const db=opening.result;if(!db.objectStoreNames.contains(stores.commands)){const store=db.createObjectStore(stores.commands,{keyPath:"operationId"});store.createIndex("status","status");store.createIndex("draftCreated",["localDraftId","createdAt"]);}if(!db.objectStoreNames.contains(stores.drafts))db.createObjectStore(stores.drafts,{keyPath:"localDraftId"});if(!db.objectStoreNames.contains(stores.mappings))db.createObjectStore(stores.mappings,{keyPath:"localDraftId"});if(!db.objectStoreNames.contains(stores.cache))db.createObjectStore(stores.cache,{keyPath:"key"});if(!db.objectStoreNames.contains(stores.meta))db.createObjectStore(stores.meta,{keyPath:"key"});}; opening.onsuccess=()=>resolve(opening.result);opening.onerror=()=>reject(opening.error); }); }
async function transactObjectStore<T>(name:string,mode:IDBTransactionMode,work:(store:IDBObjectStore)=>Promise<T>){const db=await openPos2OfflineDatabase();try{const tx=db.transaction(name,mode),completion=new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);}),result=await work(tx.objectStore(name));await completion;return result;}finally{db.close();}}
const changed=()=>window.dispatchEvent(new Event("maestro:pos2-offline-changed"));

export async function saveDraft(draft:Pos2LocalDraft){await transactObjectStore(stores.drafts,"readwrite",async store=>{await request(store.put(draft));});changed();}
export async function getDraft(id:string){return transactObjectStore(stores.drafts,"readonly",store=>request<Pos2LocalDraft|undefined>(store.get(id)));}
export async function listDrafts(){return transactObjectStore(stores.drafts,"readonly",store=>request<Pos2LocalDraft[]>(store.getAll()));}
export async function saveMapping(mapping:Pos2EntityMapping){await transactObjectStore(stores.mappings,"readwrite",async store=>{await request(store.put(mapping));});changed();}
export async function getMapping(localDraftId:string){return transactObjectStore(stores.mappings,"readonly",store=>request<Pos2EntityMapping|undefined>(store.get(localDraftId)));}
export async function listCommands(){return transactObjectStore(stores.commands,"readonly",store=>request<Pos2CommandEnvelope[]>(store.getAll()));}
export async function putCommand(command:Pos2CommandEnvelope){await transactObjectStore(stores.commands,"readwrite",async store=>{await request(store.put(command));});changed();}
export async function enqueuePos2Command(input:{commandType:Pos2CommandType;localDraftId:string;entityId?:string|null;payload:Record<string,unknown>;dependsOn?:string[];actorId:string;terminalId:string;branchId:string;operationId?:string}){const operationId=input.operationId??generateClientOperationId(),createdAt=new Date().toISOString();const envelope:Pos2CommandEnvelope={schemaVersion:POS2_OFFLINE_SCHEMA_VERSION,id:operationId,operationId,commandType:input.commandType,localDraftId:input.localDraftId,entityId:input.entityId??null,payload:JSON.parse(canonicalOfflinePayload(input.payload)) as Record<string,unknown>,payloadHash:await hashOfflinePayload(input.payload),dependsOn:input.dependsOn??[],actorId:input.actorId,terminalId:input.terminalId,branchId:input.branchId,createdAt,attemptCount:0,lastAttemptAt:null,nextAttemptAt:null,status:"PENDING",lastError:null,result:null,acknowledgedAt:null};await putCommand(envelope);return envelope;}
export async function compactQueue(){const commands=await listCommands(),compacted=compactPending(commands),ids=new Set(compacted.map(item=>item.operationId));const removed=commands.filter(item=>!ids.has(item.operationId));if(!removed.length)return 0;await transactObjectStore(stores.commands,"readwrite",async store=>{for(const item of removed)await request(store.delete(item.operationId));});changed();return removed.length;}
export async function replaceCacheAtomically<T>(snapshot:Pos2CacheSnapshot<T>){await transactObjectStore(stores.cache,"readwrite",async store=>{await request(store.put(snapshot));});changed();}
export async function getCache<T>(key:string){return transactObjectStore(stores.cache,"readonly",store=>request<Pos2CacheSnapshot<T>|undefined>(store.get(key)));}
export async function setMeta(key:string,value:unknown){await transactObjectStore(stores.meta,"readwrite",async store=>{await request(store.put({key,value}));});changed();}
export async function getMeta<T>(key:string){const row=await transactObjectStore(stores.meta,"readonly",store=>request<{key:string;value:T}|undefined>(store.get(key)));return row?.value;}

export function createLocalDraft(input:{branchId:string;registerId:string;terminalId:string;cashSessionId:string;actorId:string}):Pos2LocalDraft{const now=new Date().toISOString();return{schemaVersion:POS2_OFFLINE_SCHEMA_VERSION,localDraftId:generateClientOperationId(),serverOrderId:null,serverVersion:null,localRevision:0,...input,lines:[],state:"DRAFT",estimatesOnly:true,cachedAt:null,createdAt:now,updatedAt:now};}
