import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { generateOperationId } from "@/lib/pos2/operationId";
import { adjustAction, captureInitialCountAction, configureUnitAction, countAction, receiveAction, transferAction } from "./actions";

const field = "rounded border border-outline-variant bg-background px-2 py-1";
const handlingLabels: Record<string, string> = { BOTELLA: "botellas", GARRAFA: "garrafas", CAJA: "cajas", PAQUETE: "paquetes", PIEZA: "piezas", KILOGRAMO: "kilogramos", LITRO: "litros", OTRA: "unidades" };
const unitLabels: Record<string, string> = { UNIT: "unidades", ML: "ml" };

export default async function InventoryV2Page({ searchParams }: { searchParams: Promise<{ branchId?: string }> }) {
  await requireAdmin();
  const query = await searchParams;
  const branches = await prisma.branch.findMany({ where: { active: true }, orderBy: { name: "asc" } });
  const branchId = query.branchId ?? branches[0]?.id;
  if (!branchId) return <main className="p-6">No hay sucursales activas.</main>;
  const [products, balances, movements, declarations, recipeIngredients] = await Promise.all([
    prisma.inventoryProduct.findMany({ where: { isActive: true }, orderBy: { name: "asc" } }),
    prisma.inventoryBalance.findMany({ where: { branchId }, include: { inventoryProduct: true }, orderBy: { inventoryProduct: { name: "asc" } } }),
    prisma.inventoryMovement.findMany({ where: { branchId }, select: { inventoryProductId: true }, distinct: ["inventoryProductId"] }),
    prisma.inventoryCountDeclaration.findMany({ where: { branchId }, select: { inventoryProductId: true }, distinct: ["inventoryProductId"] }),
    prisma.posVariantIngredient.findMany({ where: { variant: { active: true, product: { active: true, sellable: true } } }, select: { unit: true, unitStatus: true, inventoryProductId: true, inventoryProduct: true, variant: { select: { id: true, name: true, product: { select: { name: true, inventoryTracked: true } } } } } }),
  ]);
  const configured = products.filter((product) => product.inventoryBaseUnit);
  const productSelect = (name: string) => <select className={field} name={name}>{configured.map((product) => <option key={product.id} value={product.id}>{product.code} · {product.name} [{product.inventoryBaseUnit}]</option>)}</select>;
  const balanceMap = new Map(balances.map((balance) => [balance.inventoryProductId, balance]));
  const movementIds = new Set(movements.map((movement) => movement.inventoryProductId));
  const declarationIds = new Set(declarations.map((declaration) => declaration.inventoryProductId));
  const ingredientMap = new Map<string, { product: typeof products[number]; recipes: Set<string> }>();
  const recipeMap = new Map<string, { productName: string; variantName: string; ready: boolean; blockers: Set<string> }>();
  for (const row of recipeIngredients) {
    const ingredient = ingredientMap.get(row.inventoryProductId) ?? { product: row.inventoryProduct, recipes: new Set<string>() };
    ingredient.recipes.add(`${row.variant.product.name} · ${row.variant.name}`);
    ingredientMap.set(row.inventoryProductId, ingredient);
    const recipe = recipeMap.get(row.variant.id) ?? { productName: row.variant.product.name, variantName: row.variant.name, ready: row.variant.product.inventoryTracked, blockers: new Set<string>() };
    if (!row.variant.product.inventoryTracked) { recipe.ready = false; recipe.blockers.add("inventario del producto apagado"); }
    if (row.unitStatus !== "RESOLVED" || !row.unit) { recipe.ready = false; recipe.blockers.add("unidad de receta sin resolver"); }
    if (!row.inventoryProduct.trackStock || !row.inventoryProduct.inventoryBaseUnit) { recipe.ready = false; recipe.blockers.add(`${row.inventoryProduct.name} sin unidad V2`); }
    if (row.unit && row.inventoryProduct.inventoryBaseUnit && row.unit !== row.inventoryProduct.inventoryBaseUnit) { recipe.ready = false; recipe.blockers.add(`${row.inventoryProduct.name} con unidad distinta`); }
    recipeMap.set(row.variant.id, recipe);
  }
  const ingredients = [...ingredientMap.values()].sort((a, b) => a.product.name.localeCompare(b.product.name));
  return <main className="mx-auto max-w-7xl space-y-6 p-6"><header><h1 className="text-2xl font-bold">Inventory Ledger V2</h1><p className="text-sm">{branches.find((branch) => branch.id === branchId)?.name} · Los balances se modifican solo mediante comandos auditados.</p></header><form><select className={field} name="branchId" defaultValue={branchId}>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select><button className="ml-2 underline">Ver sucursal</button></form>
    <section className="rounded border border-amber-300 bg-amber-50 p-4 text-sm"><b>Conteo físico inicial, una sola vez</b><p className="mt-1">Captura existencias reales de esta sucursal. No importa legacy automáticamente, no copia saldos de otra sucursal y no vuelve a inicializar un producto que ya tenga movimiento o declaración, aunque su saldo sea cero.</p></section>
    <section className="space-y-3"><h2 className="text-lg font-semibold">Insumos de recetas activas</h2>{ingredients.length === 0 ? <p className="rounded border p-4 text-sm">No hay insumos de recetas activas.</p> : <div className="grid gap-3 md:grid-cols-2">{ingredients.map(({ product, recipes }) => { const balance = balanceMap.get(product.id); const baseUnit = product.inventoryBaseUnit; const canUsePresentation = Boolean(baseUnit && product.normalizedContentPerUnit && product.contentUnit && ((baseUnit === "ML" && ["ML", "L"].includes(product.contentUnit)) || (baseUnit === "UNIT" && product.contentUnit === "PIEZAS"))); const initialized = movementIds.has(product.id) || declarationIds.has(product.id); const captureLabel = canUsePresentation ? (handlingLabels[product.handlingUnit ?? ""] ?? "unidades") : (unitLabels[baseUnit ?? ""] ?? "unidad base"); return <article key={product.id} className="rounded border p-4"><div className="flex items-start justify-between gap-3"><div><b>{product.name}</b><p className="text-xs text-slate-600">Receta: {[...recipes].join(", ")}</p><p className="mt-1 text-sm">POS2: <strong>{balance?.quantity.toFixed(3) ?? "0.000"} {unitLabels[baseUnit ?? ""] ?? "sin configurar"}</strong></p>{product.contentPerUnit && product.contentUnit && <p className="text-xs text-slate-600">Presentación: 1 {handlingLabels[product.handlingUnit ?? ""] ?? "unidad"} = {product.contentPerUnit.toFixed(3)} {product.contentUnit.toLowerCase()} · base normalizada {product.normalizedContentPerUnit?.toFixed(3) ?? "?"} {unitLabels[baseUnit ?? ""] ?? ""}</p>}</div><span className={initialized ? "rounded bg-slate-100 px-2 py-1 text-xs" : "rounded bg-amber-100 px-2 py-1 text-xs"}>{initialized ? "Inicializado" : "Sin conteo inicial"}</span></div>{!product.trackStock || !baseUnit ? <p className="mt-3 text-sm text-red-700">Bloqueado: configura trackStock y unidad base antes de capturar.</p> : initialized ? <p className="mt-3 text-sm text-slate-600">Ya existe evidencia de inicialización. Usa un ajuste o conteo posterior, no vuelvas a importar legacy.</p> : <form action={captureInitialCountAction} className="mt-3 flex flex-wrap items-end gap-2"><input type="hidden" name="operationId" value={generateOperationId()} /><input type="hidden" name="branchId" value={branchId} /><input type="hidden" name="inventoryProductId" value={product.id} /><input type="hidden" name="captureUnit" value={canUsePresentation ? "PRESENTATION" : "BASE"} /><label className="text-sm">Conteo real ({captureLabel})<input className={`${field} ml-2 w-32`} name="countedUnits" type="number" min="0" step="0.001" required /></label><input className={field} name="notes" placeholder="Nota / acta" /><button className="rounded bg-black px-3 py-2 text-sm text-white">Registrar conteo inicial</button></form>}</article>; })}</div>}</section>
    <section className="space-y-3"><h2 className="text-lg font-semibold">Recetas POS2 activas</h2><div className="grid gap-2 md:grid-cols-2">{[...recipeMap.values()].sort((a, b) => `${a.productName}${a.variantName}`.localeCompare(`${b.productName}${b.variantName}`)).map((recipe) => <div key={`${recipe.productName}-${recipe.variantName}`} className="rounded border p-3 text-sm"><b>{recipe.productName} · {recipe.variantName}</b><span className={`ml-2 rounded px-2 py-1 text-xs ${recipe.ready ? "bg-green-100 text-green-800" : "bg-red-100 text-red-800"}`}>{recipe.ready ? "Lista" : "Bloqueada"}</span>{recipe.blockers.size > 0 && <p className="mt-2 text-red-700">{[...recipe.blockers].join("; ")}</p>}</div>)}</div></section>
    <details className="rounded border p-3"><summary>Configurar unidad V2</summary>{products.filter((product) => !product.inventoryBaseUnit).map((product) => <form key={product.id} action={configureUnitAction} className="flex gap-2 p-1"><input type="hidden" name="inventoryProductId" value={product.id} /><span>{product.code} · {product.name} (legacy: {product.unit})</span><select name="unit"><option>UNIT</option><option>ML</option></select><button className="underline">Configurar</button></form>)}</details>
    <section className="grid gap-3 lg:grid-cols-4"><form action={receiveAction} className="space-y-2 rounded border p-3"><b>Recibir</b><input type="hidden" name="operationId" value={generateOperationId()} /><input type="hidden" name="branchId" value={branchId} />{productSelect("inventoryProductId")}<input className={field} name="quantity" required /><select name="unit"><option>UNIT</option><option>ML</option></select><input className={field} name="sourceId" required placeholder="Documento" /><input className={field} name="reason" required placeholder="Motivo" /><button>Registrar</button></form><form action={adjustAction} className="space-y-2 rounded border p-3"><b>Ajustar</b><input type="hidden" name="operationId" value={generateOperationId()} /><input type="hidden" name="branchId" value={branchId} />{productSelect("inventoryProductId")}<input className={field} name="delta" required placeholder="+/-" /><select name="unit"><option>UNIT</option><option>ML</option></select><input className={field} name="reason" required /><button>Aplicar</button></form><form action={countAction} className="space-y-2 rounded border p-3"><b>Conteo posterior</b><input type="hidden" name="operationId" value={generateOperationId()} /><input type="hidden" name="branchId" value={branchId} />{productSelect("inventoryProductId")}<input className={field} name="declaredQuantity" required /><select name="unit"><option>UNIT</option><option>ML</option></select><input className={field} name="notes" /><button>Declarar</button></form><form action={transferAction} className="space-y-2 rounded border p-3"><b>Transferir</b><input type="hidden" name="operationId" value={generateOperationId()} /><input type="hidden" name="fromBranchId" value={branchId} /><select className={field} name="toBranchId">{branches.filter((branch) => branch.id !== branchId).map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select>{productSelect("inventoryProductId")}<input className={field} name="quantity" required /><select name="unit"><option>UNIT</option><option>ML</option></select><input className={field} name="reason" required /><button>Transferir</button></form></section>
    <section><h2 className="font-semibold">Balances</h2>{balances.map((balance) => <div key={balance.id} className="border-b p-2">{balance.inventoryProduct.code} · {balance.inventoryProduct.name}: <b>{balance.quantity.toString()} {balance.unit}</b> · v{balance.version}</div>)}</section><section><h2 className="font-semibold">Últimos movimientos</h2>{movements.map((movement) => <div key={movement.inventoryProductId} className="border-b p-2 text-sm">{movement.inventoryProductId} · movimiento registrado</div>)}</section></main>;
}
