import assert from 'node:assert/strict';
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { prisma } from '../lib/prisma';
import { withDatabaseActor } from '../lib/database-context';
for(const url of [process.env.DATABASE_URL!,process.env.OWNER_DATABASE_URL!])if(new URL(url).hostname!=='127.0.0.1'||!url.endsWith('/veliz_audit'))throw Error('LOCAL_TEST_DATABASE_REQUIRED');
const owner=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.OWNER_DATABASE_URL!})});
const actor={id:'qa-other',role:'ENCARGADO'};
const read=(identity:typeof actor|null)=>withDatabaseActor(identity,()=>prisma.inventoryBalance.findMany({select:{branchId:true}}));
assert.deepEqual(await read(null),[]);console.log('PASS Anonymous runtime has no branch inventory');
const own=await read(actor);assert.ok(own.length>0&&own.every(r=>r.branchId==='other'));console.log('PASS Assigned runtime sees only its branch');
assert.ok((await read({...actor,role:'ADMIN'})).every(r=>r.branchId==='other'));console.log('PASS Spoofed admin role cannot widen database access');
assert.deepEqual(await read({id:'nonexistent-local-user',role:'ADMIN'}),[]);console.log('PASS Unknown identity cannot access rows');
const inactive='qa-inactive-'+Date.now();await owner.user.create({data:{id:inactive,username:inactive,name:'Inactive QA',password:'fixture-only',role:'ADMIN',active:false}});await owner.userBranch.create({data:{userId:inactive,branchId:'veliz'}});
assert.deepEqual(await read({id:inactive,role:'ADMIN'}),[]);console.log('PASS Inactive identity has no row access despite assignment');
const productId='qa-rls-'+Date.now();await owner.inventoryProduct.create({data:{id:productId,code:productId,name:'Local RLS test',category:'TEST',unit:'Pza',itemType:'CONSUMABLE',trackStock:true,inventoryBaseUnit:'UNIT'}});
await assert.rejects(withDatabaseActor(actor,()=>prisma.inventoryBalance.create({data:{branchId:'veliz',inventoryProductId:productId,quantity:1,unit:'UNIT'}})));assert.equal(await owner.inventoryBalance.count({where:{inventoryProductId:productId}}),0);console.log('PASS Cross-branch write blocked by WITH CHECK');
const alternating=await Promise.all(Array.from({length:20},(_,i)=>read(i%2?actor:null)));alternating.forEach((rows,i)=>assert.ok(i%2?rows.every(r=>r.branchId==='other'):rows.length===0));console.log('PASS Parallel pooled requests do not leak identity');
const movement=await owner.inventoryMovement.findFirstOrThrow();await assert.rejects(owner.inventoryMovement.update({where:{id:movement.id},data:{reasonCode:'TRY_TO_REWRITE'}}));assert.notEqual((await owner.inventoryMovement.findUniqueOrThrow({where:{id:movement.id}})).reasonCode,'TRY_TO_REWRITE');console.log('PASS Database prevents inventory history mutation');
const event=await owner.auditEvent.findFirstOrThrow();await assert.rejects(owner.auditEvent.delete({where:{id:event.id}}));assert.ok(await owner.auditEvent.findUnique({where:{id:event.id}}));console.log('PASS Database prevents audit history deletion');
await owner.$disconnect();await prisma.$disconnect();
