"use server";
import { revalidatePath } from "next/cache";
import { requireAdminAction } from "@/lib/auth";
import { completeSale } from "@/lib/pos2/sales/completeSale";
import { prisma } from "@/lib/prisma";
import { DomainError } from "@/lib/domain/errors";
import { cancelSale } from "@/lib/pos2/sales/cancelSale";
import { createReturn } from "@/lib/pos2/sales/createReturn";
import { createRefund } from "@/lib/pos2/sales/createRefund";
const actor=async()=>{const user=await requireAdminAction();return{id:user.id,role:user.role,branchIds:null}as const};
export async function completeSaleAction(form: FormData) { const user = await requireAdminAction(); const payments=[]; const cash=String(form.get("cashAmount")||""); const card=String(form.get("cardAmount")||""); const transfer=String(form.get("transferAmount")||""); if(Number(cash)>0)payments.push({method:"CASH" as const,amount:cash,cashTendered:String(form.get("cashTendered")||cash)}); if(Number(card)>0)payments.push({method:"CARD" as const,amount:card,reference:String(form.get("cardReference")||"")}); if(Number(transfer)>0)payments.push({method:"TRANSFER" as const,amount:transfer,reference:String(form.get("transferReference")||"")}); await completeSale({ actor: { id: user.id, role: user.role, branchIds: null }, operationId: String(form.get("operationId")), orderId: String(form.get("orderId")), expectedOrderVersion: Number(form.get("version")), cashSessionId: String(form.get("cashSessionId")), terminalId: String(form.get("terminalId")), payments }); revalidatePath("/administration/pos2/sales"); }
export async function configureRecipeUnitAction(form: FormData) { await requireAdminAction(); const id=String(form.get("ingredientId")),unit=String(form.get("unit")); const ingredient=await prisma.posVariantIngredient.findUniqueOrThrow({where:{id},include:{inventoryProduct:true}}); if(unit!=="UNRESOLVED"&&ingredient.inventoryProduct.inventoryBaseUnit!==unit)throw new DomainError("INVENTORY_UNIT_MISMATCH",{inventoryProductId:ingredient.inventoryProductId}); await prisma.posVariantIngredient.update({where:{id},data:unit==="UNRESOLVED"?{unit:null,unitStatus:"UNRESOLVED"}:{unit:unit as "UNIT"|"ML",unitStatus:"RESOLVED"}}); revalidatePath("/administration/pos2/sales"); }
export async function cancelSaleAction(form:FormData){await cancelSale({actor:await actor(),operationId:String(form.get("operationId")),saleId:String(form.get("saleId")),terminalId:String(form.get("terminalId")),cashSessionId:String(form.get("cashSessionId")||"")||undefined,reasonCode:String(form.get("reasonCode")) as never,reasonText:String(form.get("reasonText")||"")});revalidatePath("/administration/pos2/sales");}
export async function returnSaleLineAction(form:FormData){await createReturn({actor:await actor(),operationId:String(form.get("operationId")),saleId:String(form.get("saleId")),terminalId:String(form.get("terminalId")),reasonCode:String(form.get("reasonCode")) as never,lines:[{saleLineId:String(form.get("saleLineId")),quantity:String(form.get("quantity")),unit:String(form.get("unit")) as never,disposition:String(form.get("disposition")) as never,reasonText:String(form.get("reasonText")||"")} ]});revalidatePath("/administration/pos2/sales");}
export async function refundSaleAction(form:FormData){const allocations=[];for(const[key,value]of form.entries())if(key.startsWith("allocation:")&&Number(value)>0){const paymentId=key.slice(11);allocations.push({paymentId,amount:String(value),reference:String(form.get(`reference:${paymentId}`)||"")});}await createRefund({actor:await actor(),operationId:String(form.get("operationId")),saleId:String(form.get("saleId")),terminalId:String(form.get("terminalId")),cashSessionId:String(form.get("cashSessionId")||"")||undefined,amount:String(form.get("amount")),reasonCode:String(form.get("reasonCode")) as never,reasonText:String(form.get("reasonText")||""),allocations});revalidatePath("/administration/pos2/sales");}
