import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { generateOperationId } from "@/lib/pos2/operationId";
import { cancelSaleAction, completeSaleAction, configureRecipeUnitAction, refundSaleAction, returnSaleLineAction } from "./actions";
const field="rounded border border-outline-variant bg-background px-2 py-1";
export default async function SalesV2Page(){await requireAdmin();const[orders,terminals,sessions,sales,ingredients]=await Promise.all([
 prisma.pos2Order.findMany({where:{status:"PAYMENT_PENDING"},include:{branch:true},orderBy:{updatedAt:"desc"}}),prisma.terminal.findMany({where:{status:"ACTIVE"},orderBy:{name:"asc"}}),prisma.cashSession.findMany({where:{status:"OPEN"},include:{register:true},orderBy:{openedAt:"desc"}}),prisma.pos2Sale.findMany({include:{payments:{include:{refundAllocations:true}},lines:{include:{returnLines:true}},cancellation:true,returns:true,refunds:true},orderBy:{completedAt:"desc"},take:50}),prisma.posVariantIngredient.findMany({include:{variant:{include:{product:true}},inventoryProduct:true},orderBy:{variant:{product:{name:"asc"}}}})]);
 return <main className="mx-auto max-w-7xl space-y-6 p-6"><header><h1 className="text-2xl font-bold">Sales V2 — compensaciones</h1><p className="text-sm text-on-surface-variant">Superficie aislada para CompleteSale, Cancel, Return y Refund. No afecta POS V1.</p></header>
 {orders.map(order=><form key={order.id} action={completeSaleAction} className="flex flex-wrap items-center gap-2 rounded-xl border p-4"><input type="hidden" name="operationId" value={generateOperationId()}/><input type="hidden" name="orderId" value={order.id}/><input type="hidden" name="version" value={order.version}/><input type="hidden" name="cashSessionId" value={order.cashSessionId}/><b>{order.orderNumber} · ${order.total.toFixed(2)}</b><select className={field} name="terminalId">{terminals.filter(t=>t.branchId===order.branchId).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input className={field} name="cashAmount" placeholder="Efectivo"/><input className={field} name="cashTendered" placeholder="Entregado"/><input className={field} name="cardAmount" placeholder="Tarjeta"/><input className={field} name="cardReference" placeholder="Auth"/><input className={field} name="transferAmount" placeholder="Transferencia"/><input className={field} name="transferReference" placeholder="Referencia"/><button className="rounded bg-primary px-3 py-2 text-on-primary">CompleteSale</button></form>)}
 <section className="space-y-2"><h2 className="font-semibold">Unidades de receta</h2>{ingredients.map(i=><form key={i.id} action={configureRecipeUnitAction} className="flex flex-wrap justify-between gap-2 rounded border p-2"><input type="hidden" name="ingredientId" value={i.id}/><span>{i.variant.product.name} · {i.variant.name} → {i.quantity.toString()} {i.inventoryProduct.name}</span><select className={field} name="unit" defaultValue={i.unitStatus==="RESOLVED"?i.unit!:"UNRESOLVED"}><option value="UNRESOLVED">Sin resolver</option><option>UNIT</option><option>ML</option></select><button>Guardar</button></form>)}</section>
 <section className="space-y-4"><h2 className="font-semibold">Historia compensatoria</h2>{sales.map(sale=>{const branchTerminals=terminals.filter(t=>t.branchId===sale.branchId),branchSessions=sessions.filter(s=>s.branchId===sale.branchId);return <article key={sale.id} className="space-y-3 rounded-xl border p-4"><header className="flex justify-between"><span><b>{sale.saleNumber}</b> · {sale.status} · Returns {sale.returns.length} · Refunds {sale.refunds.length}</span><strong>${sale.total.toFixed(2)}</strong></header>
 {!sale.cancellation&&sale.status==="COMPLETED"&&!sale.returns.length&&!sale.refunds.length&&<form action={cancelSaleAction} className="flex flex-wrap gap-2"><input type="hidden" name="operationId" value={generateOperationId()}/><input type="hidden" name="saleId" value={sale.id}/><select className={field} name="terminalId">{branchTerminals.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select className={field} name="cashSessionId"><option value="">Sin caja</option>{branchSessions.map(s=><option key={s.id} value={s.id}>{s.register.name}</option>)}</select><select className={field} name="reasonCode"><option>WRONG_ORDER</option><option>DUPLICATE</option><option>OPERATOR_ERROR</option><option>CUSTOMER_REQUEST</option></select><input className={field} name="reasonText" placeholder="Detalle"/><button className="text-error underline">Cancelar venta</button></form>}
 {sale.status!=="CANCELLED"&&sale.lines.map(line=>{const returned=line.returnLines.reduce((sum,item)=>sum+Number(item.quantity),0),remaining=Number(line.quantity)-returned;return remaining>0?<form key={line.id} action={returnSaleLineAction} className="flex flex-wrap gap-2 rounded bg-surface-container p-2"><input type="hidden" name="operationId" value={generateOperationId()}/><input type="hidden" name="saleId" value={sale.id}/><input type="hidden" name="saleLineId" value={line.id}/><input type="hidden" name="unit" value={line.unit}/><span>{line.productNameSnapshot} · retornable {remaining} {line.unit}</span><select className={field} name="terminalId">{branchTerminals.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input className={field} name="quantity" type="number" step="0.000001" max={remaining} required/><select className={field} name="disposition"><option>DISCARD</option><option>DAMAGED</option><option>RESTOCK</option></select><select className={field} name="reasonCode"><option>CUSTOMER_RETURN</option><option>DEFECTIVE</option><option>WRONG_ITEM</option></select><input className={field} name="reasonText" placeholder="Detalle"/><button>Crear Return</button></form>:null})}
 {sale.status!=="CANCELLED"&&<form action={refundSaleAction} className="space-y-2 rounded bg-surface-container p-2"><input type="hidden" name="operationId" value={generateOperationId()}/><input type="hidden" name="saleId" value={sale.id}/><div className="flex flex-wrap gap-2"><select className={field} name="terminalId">{branchTerminals.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select className={field} name="cashSessionId"><option value="">Sin caja</option>{branchSessions.map(s=><option key={s.id} value={s.id}>{s.register.name}</option>)}</select><input className={field} name="amount" placeholder="Refund total" required/><select className={field} name="reasonCode"><option>RETURN</option><option>SERVICE_RECOVERY</option><option>PRICE_CORRECTION</option></select><input className={field} name="reasonText" placeholder="Detalle"/></div><div className="flex flex-wrap gap-2">{sale.payments.map(p=><span key={p.id}>{p.method} ${p.amount.toFixed(2)} <input className={field} name={`allocation:${p.id}`} placeholder="Asignar"/><input className={field} name={`reference:${p.id}`} placeholder="Referencia"/></span>)}</div><button>Crear Refund</button></form>}
 </article>})}</section></main>}
