import { Card } from "@/components/ui/Card";
import { requireAdmin } from "@/lib/auth";
import { dateKey, formatMinutes, mondayOf } from "@/lib/workforce/timesheet/rules";
import { getOvertimeBoard } from "@/lib/workforce/overtime/service";
import { finalizeWorkforceOvertimeAction, setWorkforceJornadaAction } from "@/app/actions/workforceOvertime";

const field = "min-h-11 w-full rounded-lg border border-outline-variant bg-surface px-3 py-2";
const days = ["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"];

export default async function WorkforceOvertimePage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  await requireAdmin();
  const query = await searchParams;
  const week = query.week && /^\d{4}-\d{2}-\d{2}$/.test(query.week) ? mondayOf(new Date(`${query.week}T00:00:00.000Z`)) : mondayOf(new Date());
  const board = await getOvertimeBoard(week, query.search || undefined);
  const route = `/administration/workforce/overtime?week=${dateKey(board.start)}${query.search ? `&search=${encodeURIComponent(query.search)}` : ""}`;
  const rows = query.status ? board.rows.filter((row) => row.ok ? row.data.mode === query.status : query.status === "BLOCKED") : board.rows;
  return <section className="space-y-5">
    {query.saved ? <p role="status" className="rounded-xl bg-primary/10 p-3 font-semibold">{query.saved}</p> : null}
    {query.error ? <p role="alert" className="rounded-xl bg-error/10 p-3 font-semibold text-error">{query.error}</p> : null}
    <div><h2 className="text-2xl font-black">Overtime semanal</h2><p className="text-sm text-on-surface-variant">Clasificación de minutos aprobados; no calcula sueldo, impuestos ni nómina.</p></div>
    <Card><form method="get" className="grid gap-3 sm:grid-cols-3"><label>Semana<input name="week" type="date" defaultValue={dateKey(board.start)} className={field} /></label><label>Empleado<input name="search" defaultValue={query.search ?? ""} className={field} /></label><label>Estado<select name="status" defaultValue={query.status ?? ""} className={field}><option value="">Todos</option><option>PREVIEW</option><option>FINAL</option><option>STALE</option><option>BLOCKED</option></select></label><button className="min-h-11 rounded-lg bg-primary font-bold text-on-primary sm:col-span-3">Abrir periodo</button></form></Card>
    <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[850px] text-sm"><thead><tr><th className="p-2 text-left">Empleado</th><th>Aprobado</th><th>Ordinario</th><th>Doble</th><th>Triple</th><th>Estado</th><th>Issues</th></tr></thead><tbody>{rows.map((row) => row.ok ? <tr key={row.data.timesheet.id} className="border-t"><td className="p-3 font-bold">{row.data.timesheet.employment.employee.displayName}</td><td className="text-center">{formatMinutes(row.data.result.approvedMinutes)}</td><td className="text-center">{formatMinutes(row.data.result.ordinaryMinutes)}</td><td className="text-center">{formatMinutes(row.data.result.doubleMinutes)}</td><td className="text-center">{formatMinutes(row.data.result.tripleMinutes)}</td><td className="text-center">{row.data.mode}</td><td className="text-center">—</td></tr> : <tr key={row.sheet.id} className="border-t"><td className="p-3 font-bold">{row.sheet.employment.employee.displayName}</td><td colSpan={5} className="p-3 text-error">{row.error}</td><td>BLOCKED</td></tr>)}</tbody></table></div>
    <div className="space-y-4">{rows.map((row) => {
      if (!row.ok) return <Card key={row.sheet.id} className="space-y-3"><div><h3 className="text-lg font-black">{row.sheet.employment.employee.displayName}</h3><p className="font-semibold text-error">BLOCKED · {row.error}</p></div>{row.error.startsWith("JORNADA_POLICY_") ? <form action={setWorkforceJornadaAction} className="grid gap-2 sm:grid-cols-4"><input type="hidden" name="returnTo" value={route} /><input type="hidden" name="employmentId" value={row.sheet.employmentId} /><select name="jornadaType" className={field}><option>DAY</option><option>NIGHT</option><option>MIXED</option></select><input required type="date" name="effectiveFrom" defaultValue={dateKey(row.sheet.periodStart)} className={field} /><button className="rounded-lg border border-primary px-3 font-bold text-primary sm:col-span-2">Registrar jornada efectiva</button></form> : null}</Card>;
      const { timesheet, result, mode } = row.data;
      return <Card key={timesheet.id} className="space-y-3"><div className="flex flex-col gap-2 sm:flex-row sm:justify-between"><div><h3 className="text-lg font-black">{timesheet.employment.employee.displayName}</h3><p className="text-sm">{dateKey(timesheet.periodStart)} → {dateKey(timesheet.periodEnd)} · {result.policyVersion}</p></div><span className="self-start rounded-full border px-3 py-1 text-xs font-black">{mode}</span></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><p><span className="text-xs">Aprobado</span><br /><strong>{formatMinutes(result.approvedMinutes)}</strong></p><p><span className="text-xs">Ordinario</span><br /><strong>{formatMinutes(result.ordinaryMinutes)}</strong></p><p><span className="text-xs">Doble</span><br /><strong>{formatMinutes(result.doubleMinutes)}</strong></p><p><span className="text-xs">Triple</span><br /><strong>{formatMinutes(result.tripleMinutes)}</strong></p></div><details className="rounded-lg border p-3"><summary className="cursor-pointer font-bold">Desglose y explicación</summary><div className="mt-3 space-y-2">{result.lines.map((line, index) => <div key={line.businessDate.toISOString()} className="rounded-lg bg-surface-container p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{days[index]} · {dateKey(line.businessDate)} · {line.jornadaType}</strong><strong>{formatMinutes(line.approvedMinutes)}</strong></div><p>Ordinario {formatMinutes(line.ordinaryMinutes)} · doble {formatMinutes(line.doubleMinutes)} · triple {formatMinutes(line.tripleMinutes)}</p><p className="text-xs text-on-surface-variant">{line.explanation}</p></div>)}</div></details>{mode === "PREVIEW" && (timesheet.status === "APPROVED" || timesheet.status === "LOCKED") ? <form action={finalizeWorkforceOvertimeAction}><input type="hidden" name="returnTo" value={route} /><input type="hidden" name="timesheetId" value={timesheet.id} /><input type="hidden" name="expectedTimesheetVersion" value={timesheet.version} /><button className="min-h-12 w-full rounded-xl bg-primary px-4 font-black text-on-primary">Finalizar clasificación</button></form> : null}{mode === "PREVIEW" && timesheet.status === "OPEN" ? <p className="rounded-lg bg-secondary/10 p-3 text-sm">Preview: requiere Timesheet APPROVED o LOCKED para finalizar.</p> : null}{mode === "STALE" ? <p className="rounded-lg bg-error/10 p-3 font-semibold text-error">OVERTIME_RECALCULATION_REQUIRED · el resultado histórico no fue reescrito.</p> : null}</Card>;
    })}{!rows.length ? <Card>No hay Timesheets para esta semana.</Card> : null}</div>
  </section>;
}
