import { Card } from "@/components/ui/Card";
import { requireAdmin } from "@/lib/auth";
import { getPayrollBoard } from "@/lib/workforce/payroll/service";
import { formatMinutes } from "@/lib/workforce/timesheet/rules";
import {
  addPayrollAdjustmentAction, approvePayrollAction, approveReadyPayrollPeriodAction, calculatePayrollAction, markPayrollPaidAction,
} from "@/app/actions/workforcePayroll";

const money = (value: { toString(): string } | null | undefined, currency = "MXN") =>
  new Intl.NumberFormat("es-MX", { style: "currency", currency }).format(Number(value?.toString() ?? 0));
const input = "min-h-10 rounded-lg border bg-surface px-3";

export default async function PayrollPage({ searchParams }: { searchParams: Promise<{ week?: string; error?: string; saved?: string }> }) {
  await requireAdmin();
  const query = await searchParams;
  const requested = query.week ? new Date(`${query.week}T00:00:00.000Z`) : new Date();
  const selected = Number.isNaN(requested.getTime()) ? new Date() : requested;
  const board = await getPayrollBoard(selected);
  const ready = board.rows.filter((row) => row.facts.sheet.payrollLine?.status === "READY").length;
  const approved = board.rows.filter((row) => ["APPROVED", "PAID"].includes(row.facts.sheet.payrollLine?.status ?? "")).length;
  const blocked = board.rows.filter((row) => row.facts.blockers.length).length;
  const total = board.rows.reduce((sum, row) => sum + Number(row.facts.sheet.payrollLine?.operationalPayable?.toString() ?? 0), 0);
  return <section className="min-w-0 space-y-5">
    <div><h2 className="text-2xl font-black">Payroll operativo V1</h2><p className="text-sm text-on-surface-variant">Cálculo bruto operativo; no es nómina fiscal ni CFDI.</p></div>
    {query.error ? <p role="alert" className="rounded-lg bg-error/10 p-3 text-error">{query.error}</p> : null}
    {query.saved ? <p role="status" className="rounded-lg bg-primary/10 p-3">Operación guardada.</p> : null}
    <Card className="space-y-3"><form className="flex flex-wrap items-end gap-3"><label>Semana (lunes)<input className={input} name="week" type="date" defaultValue={board.start.toISOString().slice(0,10)} /></label><button className="min-h-10 rounded-lg bg-primary px-4 font-bold text-on-primary">Ver periodo</button></form><div className="grid gap-2 sm:grid-cols-5"><p><strong>Periodo</strong><br />{board.start.toISOString().slice(0,10)} → {board.end.toISOString().slice(0,10)}</p><p><strong>Pago</strong><br />{board.payDay.toISOString().slice(0,10)}</p><p><strong>Ready</strong><br />{ready}</p><p><strong>Blocked / Approved</strong><br />{blocked} / {approved}</p><p><strong>Total</strong><br />{money({toString:()=>String(total)})}</p></div>{ready && board.rows[0] ? <form action={approveReadyPayrollPeriodAction}><input type="hidden" name="payrollPeriodId" value={board.rows[0].sheet.payrollPeriodId}/><input type="hidden" name="week" value={board.start.toISOString().slice(0,10)}/><input type="hidden" name="idempotencyKey" value={`bulk:${board.rows[0].sheet.payrollPeriodId}`}/><button className="rounded-lg border border-primary px-4 py-2 font-bold text-primary">Approve all ready</button></form> : null}</Card>
    <div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[1050px] text-sm"><thead><tr className="text-left"><th>Employee</th><th>Ordinary</th><th>Double</th><th>Triple</th><th>Gross</th><th>Earnings</th><th>Deductions</th><th>Payable</th><th>Status</th><th>Action</th></tr></thead><tbody>{board.rows.map((row) => <PayrollRow key={row.sheet.id} row={row} categories={board.categories} week={board.start.toISOString().slice(0,10)} />)}</tbody></table></div>
    <div className="grid gap-4 lg:hidden">{board.rows.map((row) => <PayrollCard key={row.sheet.id} row={row} categories={board.categories} week={board.start.toISOString().slice(0,10)} />)}</div>
  </section>;
}

type Row = Awaited<ReturnType<typeof getPayrollBoard>>["rows"][number];
type Category = Awaited<ReturnType<typeof getPayrollBoard>>["categories"][number];
function Actions({ row, categories, week }: { row: Row; categories: Category[]; week: string }) {
  const line = row.facts.sheet.payrollLine;
  if (!line) return <form action={calculatePayrollAction}><input type="hidden" name="timesheetId" value={row.sheet.id}/><input type="hidden" name="week" value={week}/><button className="rounded-lg bg-primary px-3 py-2 text-on-primary">Calcular</button></form>;
  return <div className="space-y-2">
    <details><summary className="cursor-pointer font-bold">Explicación</summary><div className="mt-2 space-y-1 text-xs">{line.rateSegments.map((segment)=><p key={segment.id}>{segment.businessDate.toISOString().slice(0,10)} · {money(segment.hourlyRate,segment.currency)}/h · O {formatMinutes(segment.ordinaryMinutes)} = {money(segment.ordinaryPay,segment.currency)} · D {formatMinutes(segment.doubleMinutes)} = {money(segment.doublePay,segment.currency)} · T {formatMinutes(segment.tripleMinutes)} = {money(segment.triplePay,segment.currency)}</p>)}{line.adjustments.map((item)=><p key={item.id}>{item.direction === "EARNING" ? "+" : "−"}{money(item.amount,line.currencySnapshot)} · {item.categoryName} · {item.reason}</p>)}</div></details>
    {line.status === "READY" ? <><form action={addPayrollAdjustmentAction} className="grid gap-2"><input type="hidden" name="payrollLineId" value={line.id}/><input type="hidden" name="week" value={week}/><input type="hidden" name="idempotencyKey" value={`adjust:${line.id}:${line.version}`}/><select required name="categoryId" className={input}><option value="">Concepto…</option>{categories.map((item)=><option key={item.id} value={item.id}>{item.direction === "EARNING" ? "+" : "−"} {item.name}</option>)}</select><input required min="0.01" step="0.01" type="number" name="amount" placeholder="Monto" className={input}/><input required minLength={5} name="reason" placeholder="Razón" className={input}/><button className="rounded-lg border px-3 py-2">Agregar</button></form><form action={approvePayrollAction}><input type="hidden" name="payrollLineId" value={line.id}/><input type="hidden" name="version" value={line.version}/><input type="hidden" name="week" value={week}/><input type="hidden" name="idempotencyKey" value={`approve:${line.id}:${line.version}`}/><button className="w-full rounded-lg bg-primary px-3 py-2 text-on-primary">Aprobar y bloquear</button></form></> : null}
    {line.status === "APPROVED" ? <form action={markPayrollPaidAction} className="grid gap-2"><input type="hidden" name="payrollLineId" value={line.id}/><input type="hidden" name="version" value={line.version}/><input type="hidden" name="week" value={week}/><input type="hidden" name="idempotencyKey" value={`paid:${line.id}:${line.version}`}/><input name="reference" placeholder="Referencia opcional" className={input}/><button className="rounded-lg bg-secondary px-3 py-2 text-on-secondary">Marcar pagado</button></form> : null}
  </div>;
}
function PayrollRow({ row, categories, week }: { row: Row; categories: Category[]; week: string }) { const line=row.facts.sheet.payrollLine; const cur=line?.currencySnapshot ?? "MXN"; return <tr className="border-t align-top"><td className="py-3 font-bold">{row.sheet.employment.employee.displayName}{row.facts.blockers.length?<p className="max-w-52 text-xs text-error">{row.facts.blockers.join(", ")}</p>:null}</td><td>{formatMinutes(line?.regularMinutes ?? row.facts.overtime?.ordinaryMinutes ?? 0)}<br/>{money(line?.ordinaryPay,cur)}</td><td>{formatMinutes(line?.overtimeTier1Minutes ?? row.facts.overtime?.doubleMinutes ?? 0)}<br/>{money(line?.doublePay,cur)}</td><td>{formatMinutes(line?.overtimeTier2Minutes ?? row.facts.overtime?.tripleMinutes ?? 0)}<br/>{money(line?.triplePay,cur)}</td><td>{money(line?.grossAmount,cur)}</td><td>{money(line?.earningsAmount,cur)}</td><td>{money(line?.deductionsAmount,cur)}</td><td className="font-black">{money(line?.operationalPayable,cur)}</td><td>{line?.status ?? "BLOCKED"}</td><td className="w-56 py-3"><Actions row={row} categories={categories} week={week}/></td></tr>; }
function PayrollCard({ row, categories, week }: { row: Row; categories: Category[]; week: string }) { const line=row.facts.sheet.payrollLine; const cur=line?.currencySnapshot ?? "MXN"; return <Card className="min-w-0 space-y-3"><div className="flex flex-wrap justify-between gap-2"><strong>{row.sheet.employment.employee.displayName}</strong><span>{line?.status ?? "BLOCKED"}</span></div>{row.facts.blockers.length?<p className="break-words text-sm text-error">{row.facts.blockers.join(", ")}</p>:null}<div className="grid grid-cols-2 gap-2 text-sm"><p>Ordinary<br/><strong>{formatMinutes(line?.regularMinutes ?? 0)} · {money(line?.ordinaryPay,cur)}</strong></p><p>Double<br/><strong>{formatMinutes(line?.overtimeTier1Minutes ?? 0)} · {money(line?.doublePay,cur)}</strong></p><p>Triple<br/><strong>{formatMinutes(line?.overtimeTier2Minutes ?? 0)} · {money(line?.triplePay,cur)}</strong></p><p>Gross<br/><strong>{money(line?.grossAmount,cur)}</strong></p><p>Adjustments<br/><strong>+{money(line?.earningsAmount,cur)} / −{money(line?.deductionsAmount,cur)}</strong></p><p>Payable<br/><strong>{money(line?.operationalPayable,cur)}</strong></p></div><details><summary className="cursor-pointer font-bold">Calculation & actions</summary><div className="mt-3"><Actions row={row} categories={categories} week={week}/></div></details></Card>; }
